### ISSUE TITLE
add some limit to memoization

### ISSUE THREAD

**Issue by facundoolano** [facundoolano/google-play-scraper#103]
on prolonged use it ends up eating all memory and killing the process

**Comment by stanislasdrg** [comment]
I updated the lib from 0.2.4 straight to 3.0.0. 
I now encounter a severe memory leak in node, with a 
`CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`
Is it related ?
Thanks !

**Comment by facundoolano** [comment]
I think so, it looks like without setting a limit to the memoization it will eventually take all the memory if using in a long lived process.

Until I (or someon else) submits a patch, you can just [disable memoization](https://github.com/facundoolano/google-play-scraper#memoization) to avoid the problem.

**Comment by facundoolano** [comment]
I've fixed the cached results to 1000 per method for now. We'll see if it fixes the issue, and maybe we can make that limit configurable in the future.

**Comment by facundoolano** [comment]
closing in favor of #142
