### ISSUE TITLE
PlayStore page loading issue

### ISSUE THREAD

**Issue by Shadow358** [facundoolano/google-play-scraper#108]
Hey it's me again,

I just noticed another problem that the scraper encounters with the PlayStore. 
If you set the scraper to scrape games by developer ID the url that it goes to looks like that:
`https://play.google.com/store/apps/developer?id=<DEVid>`
Now if you insert a developer who has more than 24 games under its ID it will first load the first 24 games and then after a second or two, the next 24. 
Here is an example( I added the gl=NL because the location also palys a role.)
`https://play.google.com/store/apps/developer?id=GameHouse&gl=NL`
And the scraper will scrape only the first 24 games and it will be done before the next 24 load.

**Comment by facundoolano** [comment]
The developer method has a `num` option to specify the amount of items to retrieve, have you tried using that?

**Comment by Shadow358** [comment]
I did not use the `num` option. After I inserted it it worked like a charm. It's strange though because it seems like it is set to 60 by default which is more than 24. Anyway thanks

**Comment by facundoolano** [comment]
Cool
