### ISSUE TITLE
I am not able to get review after 110 pages.

### ISSUE THREAD

**Issue by SkywardSolutions** [facundoolano/google-play-scraper#110]
Hi,

I have created one application for fetching all the reviews of any application. I have used asyn method to fetch data. My script uses to fetch data from one by one pages. Once data fetching reaches to around 100 pages, it stops. let me know is there any limit for this api?

What should be the solution for that?

**Comment by facundoolano** [comment]
If you can't get more pages it usually means there are not more reviews available. Bare in mind that when you use the reviews method, you only fetch one language at a time (english by default). Also the counter displayed in the app page refers to all ratings (with or without reviews), so if it says the app has 100k ratings it means 100k people gave 1 to 5 stars to the app, not that they left a written review.

**Comment by hiteshagja** [comment]
I don't think this is true. Because I have tried "com.whatsapp" and "com.sbi.SBIFreedomPlus" and same thing happening with both. So there may be some issue in API or Module. 

Please help!

**Comment by hiteshagja** [comment]
Try fetching page 112 of any of the above mentioned app.

**Comment by facundoolano** [comment]
If that's the case maybe the underlying Google API doesn't support more than that many pages. Are you able to get past the 111 page through the app listing page?

**Comment by hiteshagja** [comment]
What is the solution?

**Comment by hiteshagja** [comment]
Also how do I get "All Versions" data.

**Comment by facundoolano** [comment]
The module can only expose what Google Play exposes. If Google Play exposes only 111 pages, there's nothing else we can do.

If this is instead a bug in the module, I need some evidence of the error to fix it: an example app where you see more reviews in the app page than in the module reviews result.

If you're interested you can check the [reviews.js file](https://github.com/facundoolano/google-play-scraper/blob/dev/lib/reviews.js#L16) to get an idea of how the underlying request is formed and do some tests to find a case where the module is not returning the proper result.

**Comment by hiteshagja** [comment]
I had reviewed this file but as you said it may be underlying API's limitation. 

Can somebody suggest other official/unofficial api to get different android app reviews?

**Comment by facundoolano** [comment]
I'm closing this then, you can create a new issue if you find a bug or another source to complete the reviews.
