### ISSUE TITLE
Module crashes when appId is not valid

### ISSUE THREAD

**Issue by francescotonini** [facundoolano/google-play-scraper#111]
Hi guys, I'm experiencing some issues when the appId is not valid (e.g. spelled wrong). In this scenario the module crashes at line 47 on lib/app.js (I'm just using this functionality so far). The Play Store returns a 404 page so I think it may be useful to implement a "check" mechanism that prevents the module from crashing. I already have an idea. If you agree with me I'll try to pull request a possible fix in the next days.

Thanks in advance :)

**Comment by facundoolano** [comment]
What do you mean by crashing? Inputting an invalid appId should reject the promise with an error specifying that the application was not found. Isn't that the behaviour you are experiencing? 

(BTW I don't know what version of the code you're running, so I'm not sure what line 47 is... can you link to the code in this repo?)

**Comment by francescotonini** [comment]
I'm using the latest version (3.0.0). By crashing I mean getting a "TypeError: Cannot read property 'split' of undefined" on [line 47 of lib/app.js](https://github.com/facundoolano/google-play-scraper/blob/dev/lib/app.js#L47) instead of an error specifying that the app was not found (which I guess should be the actual behaviour).

**Comment by facundoolano** [comment]
Gotcha, I'll take a lookt at it.

**Comment by alincode** [comment]
I have same experience.
I look forward to seeing your pull request.

**Comment by facundoolano** [comment]
Fixed on latest version, let me know if it works for you.

**Comment by francescotonini** [comment]
It works! Thanks :+1:
