### ISSUE TITLE
reviews using node 6 syntax

### ISSUE THREAD

**Issue by ravivaxonite** [facundoolano/google-play-scraper#114]
hey,
i am using node  4.4.5 and i was not upgrade the lib because of the unhanded error when app not found,
now it fixed , but you are using ... syntax ( return Math.min(...numbers); )  and this is node 6 .
can you change it so i will can still use the npm lib and not fork it ?
10x
raviv

**Comment by facundoolano** [comment]
Actually it's node 5. 

Can you confirm this is the only place in the code that causes problems to you? I'm not willing to give up all the syntax benefits of recent node versions, but don't mind changing that one spot if it allows more people to use it.

**Comment by alincode** [comment]
I have same problems. So I locked my version at 3.0.0.

**Comment by ravivaxonite** [comment]
yes ,  when i removed it , it worked fine , this is the only place :)
it will be great !

**Comment by facundoolano** [comment]
Fixed, let me know if you still have issues.

**Comment by ravivaxonite** [comment]
10x!

**Comment by alincode** [comment]
@facundoolano it's work. thanks.
