### ISSUE TITLE
No output with certain apps - "Google Allo"

### ISSUE THREAD

**Issue by sgargbugreporter** [facundoolano/google-play-scraper#115]
When trying to retrieve information for [Google Allo (https://play.google.com/store/apps/details?id=com.google.android.apps.fireball)] (https://play.google.com/store/apps/details?id=com.google.android.apps.fireball) which is mentioned as being in "Pre-Register", I am getting errors.

Tried the following snippets of code using the scraper:

1. **Works:** `gplay.similar({appId: "com.google.android.apps.fireball"}).then(console.log);`  
2. **No output even after waiting for a loong time** `gplay.permissions({appId: "com.google.android.apps.fireball"}).then(console.log);` 
3. **No output even after waiting for a loong time** `gplay.app({appId: "com.google.android.apps.fireball"}).then(console.log);` 

Not sure what is happening here.

**Comment by facundoolano** [comment]
I added a `preregister` boolean field to the app detail and fixed the parsing so it doesn't break for that kind of app.

The permissions function is still failing for now.

As a side note, the cases you mentioned as "no output for along time" actually fail right away, you need to add a `.catch` clause to your promise to see the error they are throwing.
