### ISSUE TITLE
Understanding number of installs

### ISSUE THREAD

**Issue by sgargbugreporter** [facundoolano/google-play-scraper#116]
Though not exactly an issue, I would like some pointers on what the `maxInstalls` and `minInstalls` fields mean.

Also, is there any way to get the number of installs for an app geographically?

Thanks.

**Comment by facundoolano** [comment]
Whenever you enter an app's profile page you will see the installs listed as something like `10000 - 50000` installs; those numbers are the max and min installs you see in the function result.

About the geographic information, this module can only return information that can be found in the app's public page or any of the google APIs it uses. I'm not aware of any place where this information is available, but if you find it let me know the details so I can try to add it.

**Comment by sgargbugreporter** [comment]
Thank you.

As I understand it then, the Play Store does not provide the number of _actual_ installs, but just a ballpark figure? So an app that has `500,000 - 1,000,000` (com.wms.safestcallblocker) has had at least  500,000 installs and no more than 1 million. Is this thinking correct? 

Can you please point me to any webpages etc. that discuss these aspects of the play store?  For example, if finer grained data about number of installs (or actual number of installs) is available anywhere?
  
If you feel that an issue is not right for this conversation, please feel free to move it to a relevant page.

**Comment by facundoolano** [comment]
That's exactly right. I don't think that information is available anywhere. You only get to see exact installs of your own app if you publish one (and even in that case Google only refreshes that information once a day or so).

I'm closing this, but feel free to add any other questions you have.
