### ISSUE TITLE
scrape all pages of developer apps

### ISSUE THREAD

**Issue by facundoolano** [facundoolano/google-play-scraper#117]
See https://play.google.com/store/apps/developer?id=Google+Inc.

Only the first 60 or so results are brought in the first request, the rest are taken from the async API. Use that to get all of them (it uses the same pagination as the search page).

**Comment by keshavm** [comment]
Please help with this. How could I increase the limit of 120 to, say 250, when looking grab a list of all apps from a developer.
Big thanks!

**Comment by facundoolano** [comment]
The code needs to be reworked a bit, since the source to get all apps is different than just the first few as it is implemented now. In case you want to dig into it, check the search code, which is uses a very similar algorithm.

**Comment by mnemonicflow** [comment]
If this doesn't work, why then the README says that the max value for num parameter is 250? 
`num (optional, defaults to 20, max is 250): the amount of apps to retrieve.`
https://github.com/facundoolano/google-play-scraper#developer

**Comment by mnemonicflow** [comment]
I've managed to use the search functionality to get the complete list of Google Inc. apps as follows: https://gist.github.com/mnemonicflow/ae7d27492d13a947759db3ccfde14fd1

Results:
- https://gist.github.com/mnemonicflow/f17a2ac5337205177e541520eeb0e987
- https://gist.github.com/mnemonicflow/9edd47b4e70e1028e6428c92260cd9f6

**Comment by facundoolano** [comment]
@keshavm @mnemonicflow I've published a version that handles this properly, please test

**Comment by keshavm** [comment]
@facundoolano thanks!
