### ISSUE TITLE
Reviews not returning user data

### ISSUE THREAD

**Issue by MatiMenich** [facundoolano/google-play-scraper#118]
I have an issue concering the reviews function. It seems that it's not retrieving the user data anymore. Also `replyDate` and `replyText` seems to be undefined

I'm calling it like this:

```javascript
gplay.reviews({
  appId: 'com.slice.payments',
  page: 0,
  sort: gplay.sort.RATING
}).then(function(response){
  // Do something with response
});
``` 

And getting this response: 

```javascript
[
...
{
  userId: '',
  userName: '',
  date: 'February 19, 2016',
  url: 'https://play.google.com/store/apps/details?id=com.slice.payments&reviewId=Z3A6QU9xcFRPRnVvTHk1Sm5DVVU5dE1kckRKVjlCRS1UZGJ1bW9ZVmJMTkc1bW9fbkdUeDB2MGtZdkU0RTRQRnNndjN6UmNSMkpqc3M5X0FIWXRaSXppeFE',
  score: 5,
  title: 'Excelente!',
  text: 'Buena aplicación, muy practica para las cuentas, 100% recomendada',
  replyDate: undefined,
  replyText: undefined 
},
...
]
```

**Comment by facundoolano** [comment]
userId and userName missing is definitely a bug. 

The reply date and text will only be defined if the app developer has replied to that particular comment. That one look like it's still working.

**Comment by facundoolano** [comment]
Fixed userName, unfortunately userid is not exposed anymore in the reviews html, so I had to remove the field from the reviews object.
