### ISSUE TITLE
Shows only 100 results using gplay.search

### ISSUE THREAD

**Issue by kostya572** [facundoolano/google-play-scraper#124]
In docs you write the maximum limit is 250 results for gplay.search, but with console.log i see only 100 results. 
At the bottom of text i see " ... 150 more items ]"
Seems it's found, but how can i see it? Thanks.
![screen](https://cloud.githubusercontent.com/assets/20546488/20027630/5464beae-a321-11e6-982f-60a5db9c22a7.png)

**Comment by WaqasIbrahim** [comment]
There is a limit to how much you can print out using console.log. You can either try to save all the retrieved data in a file or you can use slice to print next hundred results like console.log(arr.slice(100,100)) will print out 100 items starting from 101st.

**Comment by facundoolano** [comment]
The module returns a promise that resolves to an array. You can do whatever you want with the array, the `console.log` is just for the sake of the example. If you want to print all results you could do something like:

```js
gplay.search(opts).then((results) => results.map((value) => console.log(value)))
```

Closing this as it's not really related to the library.
