### ISSUE TITLE
Memory leak when use list query with argument fullDetail set to true.

### ISSUE THREAD

**Issue by konieshadow** [facundoolano/google-play-scraper#127]
When I use the list query method, I noticed that the argument fullDetail is very useful. But when I use it in batch of query with a loop, the node process's memory was expansion rapidly and got outOfMemery in half hour.

node: 7.2.0
os: win10 x64

**Comment by facundoolano** [comment]
Are you using the latest version of the module? Have you tried [turning cache off](https://github.com/facundoolano/google-play-scraper#memoization)

**Comment by konieshadow** [comment]
@facundoolano Thanks. It's my fault didn't read the README through. I turn the cache off and the memory use keep low.
