### ISSUE TITLE
Is there a way to pass a proxy to request?

### ISSUE THREAD

**Issue by chriskinsman** [facundoolano/google-play-scraper#128]
Would like to set one for my requests without setting one globally.

Thanks!

**Comment by facundoolano** [comment]
Not right now, you'll have to either use environment variables or modify the code [here](https://github.com/facundoolano/google-play-scraper/blob/dev/lib/utils/request.js)

**Comment by chriskinsman** [comment]
probably send a pull request for this later today.

**Comment by chriskinsman** [comment]
Pull request sent as #120

**Comment by facundoolano** [comment]
Pull request was merged.
