### ISSUE TITLE
How to use Google Play Scraper to store data in a MongoDB collection

### ISSUE THREAD

**Issue by toofast1** [facundoolano/google-play-scraper#131]
I am trying to create an Android App Submit Website. What I want to achieve, is that when a user submits his app id in a form, all app data should be parsed and posted in my MongoDB collection so that I can easily display it on another page.

[Here](http://stackoverflow.com/questions/41100485/how-to-use-google-play-scrapper-with-mongodb) are more details about what I want to achieve and some snippets from my basic application.

Thanks for your help!

**Comment by facundoolano** [comment]
It seems to me that you're asking several questions at a time, but not sure exactly what they are... Looking at the code, and without knowing much of your app, it looks like you could call `gplay.app({appId: req.body.url})` or something similar, before actually saving the form data to db. Then you merge form and scraper data and save that to db.

**Comment by toofast1** [comment]
That was exactly what I was looking for, but now I got into another issue. How do I merge the form data with scraper data in order to save that to db?

**Comment by facundoolano** [comment]
That's a little out of the scope of this module. Sound like you're jumping too quick to a project before knowing the basics of JavaScript, perhaps you need to google around some tutorials or read some book  to get more familiar with it.

Closing this now.
