### ISSUE TITLE
Search Function not moving to next page

### ISSUE THREAD

**Issue by ChairmanMeow** [facundoolano/google-play-scraper#132]
There is an issue with getting more page results with the search function. 
When I try to search, it returns the same 20 apps over and over again. It looks like a change in the way the appstore processes urls and your regex to get the page token.

**Comment by facundoolano** [comment]
I'll take a look, that's the creepy bit of the code :P

**Comment by facundoolano** [comment]
@ChairmanMeow do you have an example?

**Comment by ChairmanMeow** [comment]
Wow! Fast reply :)

var gplay = require('google-play-scraper');
var fs = require('fs-extra');

const config = {
  term : 'crossword',
  num: 250,
  throttle : 5
};

gplay
  .search(config)
  .then((apps) => {
    console.log(`Retrieved ${apps.length} applications!`);
    fs.writeJsonSync('./results.json', apps.map(function(a){return a.appId}));
    process.exit(0);
  })
  .catch((e) => {
    console.log('There was an error fetching the list!');
  });

**Comment by facundoolano** [comment]
ok, @ChairmanMeow I think I got it. I just published a patched version to npm, could you check it and let me know if it fixes the issue for you?

**Comment by ChairmanMeow** [comment]
Yes it works! Thank you :)
