### ISSUE TITLE
Results not showing 

### ISSUE THREAD

**Issue by ibrr1** [facundoolano/google-play-scraper#135]
Hey, when I tried to run the first example for (app method) i was not able to see any results! the only thing I was able to see is the following:
Retrieved application: Panda vs Zombies

the were not any results as you showed in the example. However, i was able to get results for the search method.

can you please help me to obtain the results for the app method ?
thanks

**Comment by facundoolano** [comment]
You're right, the example for `app` and `list` is a bit misleading, it's printing a message instead of the whole results. Just print the result instead and you'll see all the data.

**Comment by facundoolano** [comment]
Fixed the example code to match the shown results.
