### ISSUE TITLE
always received 49 results

### ISSUE THREAD

**Issue by uditharandika** [facundoolano/google-play-scraper#138]
when searching , always search result include 49 results.new google play store interface, load its apps after scrolling  & see more button,so i think this library  not detect that,help me

 gplay.search({
                    term: facebook
                }).then(function (res) {
                    console.log(res.length)
                })

**Comment by facundoolano** [comment]
I can reproduce by setting `num` to 50 or higher. This will need fiddling with the requests google makes on scrolling the search results, may take a while to figure out.

**Comment by uditharandika** [comment]
i tried this one also,but no change in results

 gplay.search({
                    term: search_text,
                    num:249,
                }).then(function (res) {
                    callback(null, res);
                })
//output
search_text facebook
res.length 49

**Comment by facundoolano** [comment]
Yes, the ajax search urls changed and it doesn't work past the initial request. I'm working on a fix.

**Comment by facundoolano** [comment]
@uditharandika published a fix, please confirm the issue is solved.

**Comment by uditharandika** [comment]
now it's work fine,thank you.
