### ISSUE TITLE
app size

### ISSUE THREAD

**Issue by rolandoam** [facundoolano/google-play-scraper#139]
It seems that Google removed the app size from the regular web page but kept it in the app & mobile pages. Do you have plans to fix it? (scrape for the app size)

**Comment by facundoolano** [comment]
If you find some place I can read it from I'd be happy to add it to the scrapped data.

**Comment by funkaster** [comment]
:+1: I'll try to see if I can find the actual source.

**Comment by facundoolano** [comment]
Closing this, will reopen if someone finds this information in the website.
