### ISSUE TITLE
Could we have login process too ?

### ISSUE THREAD

**Issue by IMAN4K** [facundoolano/google-play-scraper#143]
Hi and thanks for the great scraper.
Could we have add login process to this scraper so we can login and also download the `.apk` ?
From the point that Google removed `ClientLogin` (and introduced `OAuth2.0`) Is there a chance for this ?

**Comment by facundoolano** [comment]
That's a bit out of the scope of this scraper, at least I don't plan to implement it (I doubt it can be done without heavily changing the way the library works). But I'm open to review pull requests that provide this functionality and assist to properly integrate it.

**Comment by IMAN4K** [comment]
Ok i know it takes time.
But do you have any idea is that possible at all ?
Which API should we take for that ?

**Comment by facundoolano** [comment]
Not really, as far as I know there's no way from a browser (or a pc) to get the apk, logged in or not. Maybe you can do some proxy weirdness from an android device to inspect the requests being made and infer what url serves the apk file, but I don't have any knowledge in that area.
