### ISSUE TITLE
Some apps would simply disappear and come back in the output

### ISSUE THREAD

**Issue by keshavm** [facundoolano/google-play-scraper#144]
I am using the developer search on the scraper. I sue it to fetch the list of apps from a given developer.
Just so that requests are less, I have disabled info elements in the app.js, so that it pulls only 2 elements.
While script will get me apps from list of developers all day fine, it would skip some apps at around 12AM GMT, which will be back a couple of hours later in the same output.
So, if my output is in a text file, and developer has 10 apps, I will get 10 apps throughout the day, but at around 12AM GMT, it would give me 8 apps only, and then after an hour or two, it will output 10 apps again. I have a huge list of developers, BTW. Some 100 developers.
I suspected it was to do with large requests, so I am pulling only 2 elements by editing the app.js file in lib folder to make it not request other elements.
I am requesting this output every hour. But the problem occurs only at around 12AM GMT.

Help pls.

_I wanted to ask, if one can sort this out by last updated date, or app's name, or anything?_
It would be cool if one can do so.

**Comment by facundoolano** [comment]
The scraper a [uses a cache](https://github.com/facundoolano/google-play-scraper#memoization) of 12 hours by default, if you want to have the most recent state every time, disable it.

> I wanted to ask, if one can sort this out by last updated date, or app's name, or anything?
https://www.w3schools.com/jsref/jsref_sort.asp

**Comment by keshavm** [comment]
@facundoolano 
I have disabled it already, which is why it serves my fine throughout the day, getting me latest output every time.

As an example, here is the code for Twitter developer:
var gplay = require('google-play-scraper'); gplay.developer({devId: "Twitter, Inc.",num: 750,cache: false,throttle: 10,fullDetail: true}).then(console.log);

That w3schools.com links goes above my head. Not a coder :/

**Comment by facundoolano** [comment]
If you're not a programmer there's not much I can help you with...

**Comment by keshavm** [comment]
Thanks anyway!
Guessed so much.
