### ISSUE TITLE
App detail - fulfill missing review details

### ISSUE THREAD

**Issue by drjunior** [facundoolano/google-play-scraper#148]
It would be cool if instead of just text comments the the method app could return the details of the reviews: Author Name, Author Image, Stars and Comment.
It would just be necessary to search for $('.single-review') instead of $('.quoted-review'). Ah it would be nice also if the app developer responded then the review would have it's response: find $('.developer-reply') for each review/indexed per review.

Thanks for your support.

**Comment by facundoolano** [comment]
That sounds good. Maybe you can send a PR for this, since you already have an idea of what needs to be done?

**Comment by drjunior** [comment]
Well, I could do it, but I'm not so proficient in nodejs as I would like :(
Regarding the possible structure it could be something like this:
reviews: [{author: "JohnDoe", stars: 3, comment: "This app is cool", devReply: "Thanks for your review."} ...]

Thanks.

**Comment by drjunior** [comment]
What do you think about this code/implementation:

  ```
var reviews = [];
  const comments = $('.single-review');
  $(comments).each(function(i, elem) {    
    elem = $(elem);

    const authorName = elem.find('.author-name').text().trim();
    var authorImg= elem.find('.responsive-img-hdpi .responsive-img.author-image').attr('style');
    authorImg = authorImg.replace('background-image:url(', '');    
    authorImg = authorImg.substring(0, authorImg.length - 1);
    const date = elem.find('.review-date').text();
    var stars = elem.find('.current-rating').attr('style');
    stars = stars.replace('width: ', '');
    stars = stars.replace('%;', '');
    stars = parseInt(stars) * (5/100);
    const reviewComment = elem.find('.review-body.with-review-wrapper').contents().not('.review-link').text().trim();


    var devReply = elem.siblings('.developer-reply');
    const devReplyName = devReply.find('span.author-name').text().trim();
    const devReplyDate = devReply.find('span.review-date').text();
    const devReplyComment = devReply.contents().not('div').text().trim();

    const review = {authorName:authorName, authorImg:authorImg, date:date, stars:stars, reviewComment:reviewComment, devReplyName:devReplyName, devReplyDate:devReplyDate, devReplyComment:devReplyComment};

    reviews.push(review);    
  });
```

**Comment by facundoolano** [comment]
@drjunior I'm a bit confused, how is this different than we currently have in reviews.js? We're already returning userName, userImage, score, date, reply text, etc.

**Comment by drjunior** [comment]
It was a misunderstanding... I wanted to have the reviews that are available in the app detail request. I was not aware that the format/structure of the https://play.google.com/store/getreviews response is similar to the one that is also present in the app detail request https://play.google.com/store/apps/details?id=.

Ok, so now that the it's everything clear. What do you think about the implementation that I suggested? Could it be faster ou slower? 
Thanks.

**Comment by facundoolano** [comment]
If the data is the same, I don't see a need to change the actual implementation. If you have some particular spot where you see room for improvement, you can send a PR with an explanation so I can see an actual diff between old code and new code. But I can tell in advance I don't like the idea of changing a piece of code that's already working if there isn't an improvement in the style or the data obtained.
