### ISSUE TITLE
add an option to get all from list

### ISSUE THREAD

**Issue by facundoolano** [facundoolano/google-play-scraper#15]
currently only pages can be grabbed, add an option to chain the calls internally and return all results in one list.

**Comment by angelastripes** [comment]
Hi, I am not able to run this on my server, I am creating a php file named "index.php" & including JS file in it to call required function.. which is mentioned below: but not getting any response..
<code>
var gplay = require('google-play-scraper');

gplay.app('com.dxco.pandavszombies')
  .then(function(app){
    console.log('Retrieved application: ' + app.title);
  })
  .catch(function(e){
    console.log('There was an error fetching the application!');
  });
</code>

**Comment by facundoolano** [comment]
Please, next time open a new issue instead of commenting on an unrelated one.

This module is intended to be used server side on a node application. If you want to use it client side, you can bundle it with browserify.

**Comment by angelastripes** [comment]
Yeah, sure.. I am sorry to write in this thread. Thanks for the solution. :)

**Comment by facundoolano** [comment]
meh
