### ISSUE TITLE
Can't crawel more then 200 apps from one collection

### ISSUE THREAD

**Issue by pkdhankher** [facundoolano/google-play-scraper#150]
When i try to crawl more then 200 apps from one collection its gives 'RequestException: Request failed with "429" status code............' something like this. Thanks in Advance 😊

**Comment by adeelhussain** [comment]
Its because Google block your IP for some time and shows a captcha

**Comment by facundoolano** [comment]
That's correct, status 429 is "Too many requests". Consider [throttling](https://github.com/facundoolano/google-play-scraper#throttling) to avoid it in the future.
