### ISSUE TITLE
Developer ID field?

### ISSUE THREAD

**Issue by AlexanderMatveev** [facundoolano/google-play-scraper#153]
Is it possible now or any plans about getting developer id instead of developer name?

**Comment by facundoolano** [comment]
That depends of what information is available in the Google Play page that's being scraped. If the method is `app` and the developer id exists in the html then it can be added to the scraped data.

**Comment by AlexanderMatveev** [comment]
@facundoolano I think this information must be added to https://github.com/facundoolano/google-play-scraper#app

What field name would it be?

**Comment by facundoolano** [comment]
developerId

**Comment by AlexanderMatveev** [comment]
@facundoolano is this field possible only in ```app``` method? What about ```list``` method?

**Comment by facundoolano** [comment]
I don't know if this field exists at all. You can check the html in the app listing and in the search results to confirm. I'm not spending time in adding features to this project right now, but feel free to send a PR if you find that field and want to add it to the results.

**Comment by facundoolano** [comment]
This should be fixed by #155 (please confirm @AlexanderMatveev)

**Comment by AlexanderMatveev** [comment]
@facundoolano I decided to switch to my own parser, because it looks like there is no need for client side actions and using URL query parameters is fine. Thank you for response!
