### ISSUE TITLE
ReferenceError: update is not defined

### ISSUE THREAD

**Issue by vishesh1king** [facundoolano/google-play-scraper#159]
I an running nested gplay. In Parent i am searching and in child I am retrieving its details using appId. I get this error in the child catch. What am i missing ??

`
   gplay.search({
      term: 'facebook',
      num: 1
    })
 
   .then(function(android_app){
      console.log('android_app[0].appId: '+android_app[0].appId);
      gplay.app({
        appId: android_app[0].appId,
      })
      .then(function(android_app_data){
           console.log('success: '+android_app_data[0].updated)
        })
        .catch(function(err){
          console.log('android function: '+err);
        });
    })
    .catch(function(err){
      console.log('android function '+err);
    });`

**Comment by facundoolano** [comment]
maybe you put `update` in some place where you meant `updated` ?

**Comment by vishesh1king** [comment]
Nope, i searched through the whole doc

**Comment by facundoolano** [comment]
can you print err.stack to see where the error is coming from?

**Comment by vishesh1king** [comment]
Actually i changed the logic of my code and its working for now. I believe something wrong in my code side. When i put this separately in a different program it worked.
