### ISSUE TITLE
can't get token in https://play.google.com/store/apps/collection/search_results_cluster_apps?authuser=0

### ISSUE THREAD

**Issue by hyhlinux** [facundoolano/google-play-scraper#162]
start:0
num:0
numChildren:0
pagTok:-p6BnQMCCDE=:S:ANO1ljJ4Cw8
clp:ggEICgJxcRoCCAA=:S:ANO1ljL3sk8
pagtt:3
cctcss:square-cover
cllayout:NORMAL
ipf:1
xhr:1
token:87XJTOvCt88IRHx3fiqElowxdQM:1500858944827

**Comment by facundoolano** [comment]
Can you put this in terms of the module? What error do you get, what code caused it exactly and what would you expect instead.
