### ISSUE TITLE
Get list of countries supported by app

### ISSUE THREAD

**Issue by ashvin777** [facundoolano/google-play-scraper#163]
Hi,

Is it possible to do this ?
Or else can we do somekind of global search of app regardless of any country as well as getting the app details and reviews ?

Regards,
Ashvin

**Comment by facundoolano** [comment]
I can't imagine anyway to do this (we can only access what the site exposes, and it always assumes a country) but I'm open to suggestions.

**Comment by edelciomolina** [comment]
Hi!
The country list can be found here
https://developers.google.com/custom-search/docs/xml_results_appendices#country-codes
