### ISSUE TITLE
Getting reviews of last 2 days

### ISSUE THREAD

**Issue by Adnation** [facundoolano/google-play-scraper#170]
Hey thank for this package, however when I am trying to get reviews of an app it is giving reviews of last 2 days only. So is it expected behavior or there is something need to be done?

Thanks again!!!

**Comment by facundoolano** [comment]
Does the Google Play website show older reviews for that language?

Can you show the code you are using to get the reviews (including the app id)?

**Comment by Adnation** [comment]
var gplay = require('google-play-scraper');
gplay.reviews({
  appId: 'com.goibibo',
  page: 0,
  sort: gplay.sort.NEWEST
}).then(console.log, console.log);


This is what I was using and yeah Google Play shows older reviews..

**Comment by facundoolano** [comment]
If you pass other page numbers, you'll get older responses:

```
gplay.reviews({appId: 'com.goibibo',sort: gplay.sort.NEWEST, page:20}).then(console.log, console.log)
```
