### ISSUE TITLE
 Error requesting Google Play:undefined, possible blocked?

### ISSUE THREAD

**Issue by Yourivdzee** [facundoolano/google-play-scraper#172]
Getting the following error after looping through the review pages:

Error: Error requesting Google Play:undefined
    at Error (native)
    at request.js:43:13
    at process._tickCallback (internal/process/next_tick.js:109:7)

Code:

`function scrapPages(i){
		gplay.reviews({
			appId: appId,
			page: i,
			sort: gplay.sort.NEWEST,
			throttle: 10
		}).then(function(text){
			if(text.length > 0){
				console.log("Page #" + i);
				getReviewProperties(text);
				scrapPages(i+1);
			}
			else{
				console.log("Less than one");
				saveToCSV();
			}
		});
}`

Does this mean I did too many requests and I am blocked from the server? How can I avoid this?

**Comment by facundoolano** [comment]
It can be, run your code with `DEBUG=google-play-scraper` to get more insight in that error.

**Comment by Yourivdzee** [comment]
Running my code with `DEBUG=google-play-scraper` resulted in the following error;

Unhandled Rejection at: Promise Promise {
  <rejected> Error: Error requesting Google Play:undefined
    at Error (native)
    at \node_modules\google-play-scraper\lib\utils\request.js:43:13
    at process._tickCallback (internal/process/next_tick.js:109:7) } reason: Error: Error requesting Google Play:undefined
    at Error (native)
    at\node_modules\google-play-scraper\lib\utils\request.js:43:13
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by facundoolano** [comment]
You should be getting more output with debug on. Are you on windows? I'm not sure how DEBUG is set up on windows.

**Comment by Yourivdzee** [comment]
I am on windows, I'll look into it more.

**Comment by facundoolano** [comment]
I'm closing this assuming google was blocking you for making too many requests. Please comment if you find out something and need me to reopen.
