### ISSUE TITLE
If I set throttle to 1, will running DEBUG show 1 request each second?

### ISSUE THREAD

**Issue by EasyGitHub99** [facundoolano/google-play-scraper#173]
I've set throttling to 1, but running in DEBUG=google-play-scraper, I'm seeing all the requests being made at once, and then very quickly I see the requests finish afterward.

I thought I would see a request happening each second, but instead they happen all at once. This is the only code I'm running:
`gplay.list({
    collection: gplay.collection.TOP_FREE,
    num: 10,
    throttle: 1,
    fullDetail: true
  })
  .then(console.log("Done!"));`

Just thought I would watch the requests take place over 10 seconds, but its under 1 second all the requests are made. Is that normal?

Also I've run this in Windows Powershell & regular Windows CLI (in case this makes a difference), but I see the same exact thing in both.

**Comment by facundoolano** [comment]
Check: https://github.com/facundoolano/google-play-scraper/blob/dev/lib/utils/request.js#L29

The debug call is made right before attempting the request; the throttling is handled by the request function, so the first batch of library calls will produce the debug output at the same time but then the requests will be done one at a time. You should be seeing one "Request finished" message per second.
