### ISSUE TITLE
Filtering apps based on permissions

### ISSUE THREAD

**Issue by mohammadnaseri** [facundoolano/google-play-scraper#177]
Hi, 

I would like to ask, if there is anyway, to get the apps with specific permission with this api?

Thanks,

**Comment by facundoolano** [comment]
If you mean something like "give me all apps with X permission", that's not possible right now, and won't ever be.

If you mean using some of the current methods like search or list, and then filtering the results based on permissions, then that's doable although not a feature of the library (#160 is about adding the permissions to the search result). If this is what you're looking for, it wouldn't be very hard to achieve: 1- get a list of apps, 2- map apps to the permissions method, 3- filter the results by the permissions you are looking for.

**Comment by mohammadnaseri** [comment]
Okay, 
Just another point, I noticed that if there are apps declaring a permission not in application element of Manifest, but in elements like service element, then ```gplay.permissions``` won't return those. 
Although play store is also not listing that permission in the app's page, which is kind of weird.

**Comment by facundoolano** [comment]
We're limited to what's displayed in the Google Play page, or what we kind find in public APIs. If the manifest permissions aren't exposed in those places we can't really include them in this library (if you do find a place that exposes that data, feel free to open a new issue).
