### ISSUE TITLE
add a test to keep constants up to date

### ISSUE THREAD

**Issue by facundoolano** [facundoolano/google-play-scraper#178]
The test should request and scrape the Google Play website to obtain the current list of app categories and make sure they are the same as those in the constants file.

This way whenever they become outdated the tests will start to fail.

**Comment by facundoolano** [comment]
The method used to scrape the categories could also be exposed as part of the API, so if someone wants to get the most up to date list of categories it can use it (as suggested by @icaroponce in #176). I want to also keep the constants around, though, since it's useful to have a list without extra requests.

**Comment by psrb191921** [comment]
I think it's possible to automaticly update constants by checking some static app url, and search for known values like name/category/etc...
