### ISSUE TITLE
A change in the site leads to incorrect behaviour

### ISSUE THREAD

**Issue by yura415** [facundoolano/google-play-scraper#182]
Google recently changed how reCaptcha redirect works. Now it shows 302 Moved page with redirect to 503 page with recaptcha. So the scraper misunderstands this as an empty list and resolves with empty array.

Example contents of 302 Moved page:
```html
 <HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://ipv4.google.com/sorry/index?continue=https://play.google.com/store/apps/category/ANDROID_WEAR/collection/topselling_new_free%3Fhl%3Den%26gl%3Dal%26num%3D120&amp;hl=en&amp;q=EgQulH9UGIScndMFIhkA8aeDSxAT_ehABOGBG4kansp-C0dRCl3oMgFy">here</A>.
</BODY></HTML>
```

Solution is to put `followAllRedirects: true` in request options.

**Comment by facundoolano** [comment]
Closing this since #183 was merged
