### ISSUE TITLE
Unable to run from the browser?

### ISSUE THREAD

**Issue by joncursi** [facundoolano/google-play-scraper#184]
I'm trying to use this library in my nextjs app. The code works well when the page is server rendered, but when the page is client-side rendered (via navigation to the page), I get the following exception:

```
 ERROR  Failed to compile with 6 errors                                            2:51:16 PM

These dependencies were not found:

* fs in ./node_modules/request/lib/har.js
* net in ./node_modules/forever-agent/index.js, ./node_modules/tough-cookie/lib/cookie.js and 1 other
* tls in ./node_modules/forever-agent/index.js, ./node_modules/tunnel-agent/index.js

To install them, you can run: npm install --save fs net tls
```

**Comment by facundoolano** [comment]
This is a node library prepared to run on the server. I'm not familiar on how next.js works, so I can't help there. There's nothing intrinsically dependent on the server in the library, so I guess if you find browser replacements of the dependencies you could pull it off.

**Comment by joncursi** [comment]
Thanks for the quick reply!

I think the usage of `request` is what is killing the compatibility on the client-side. If we used `fetch`, then I suppose we could use `isomorphic-unfetch` to easily polyfill the client with the `fetch` API so that the code runs everywhere. Thoughts?

https://github.com/developit/unfetch/tree/master/packages/isomorphic-unfetch

**Comment by facundoolano** [comment]
I don't have much time as it is to maintain this library, and this is kind of out of its scope. If you want you can try that in a fork and I will consider merging it if the changes don't disturb the typical back end user of the library.

**Comment by joncursi** [comment]
I submitted a PR for the app store library (https://github.com/facundoolano/app-store-scraper/pull/45). I'd like to submit a PR for this one, but there's some kind of throttling stuff going on in the code that I'm not sure how to port over to `fetch`.

**Comment by facundoolano** [comment]
We need to be able to throttle requests to avoid being rejected by google. We do that with the [throttled-request](https://github.com/alltherooms/throttled-request) module, which takes the request library as a parameter. Maybe there's an equivalent for the isomorphic library, or you can wrap it or adapt throttled-request to support that library as well.

**Comment by facundoolano** [comment]
I'm going to close this now, but feel free to send a PR if you can work around this.
