### ISSUE TITLE
The search return only 100 records

### ISSUE THREAD

**Issue by erkansen** [facundoolano/google-play-scraper#190]
Hi,

Thanks for the scraper it works like charm but the search function returns only 100 results and if there are some others it says "... 100 more items" and interrupt. Is there any method to see full search result?

**Comment by facundoolano** [comment]
That is not correct, this scraper returns up to 250 results with the `search` method, which is the amount exposed by google play in its website (at least when the method was last updated).

**Comment by erkansen** [comment]
Hi,

I don't know whats wrong with my query but result is contains only 100 items and says there are 150 more.

`...
  { url: 'https://play.google.com/store/apps/details?id=com.whatsapp',
    appId: 'com.whatsapp',
    title: 'WhatsApp Messenger',
    summary: 'Simple. Personal. Secure.',
    developer: 'WhatsApp Inc.',
    developerId: 'WhatsApp+Inc.',
    icon: '//lh6.ggpht.com/mp86vbELnqLi2FzvhiKdPX31_oiTRLNyeK8x4IIrbF5eD1D5RdnVwjQP0hwMNR_JdA=w340',
    score: 4.4,
    price: '0',
    free: true },
  ... 150 more items ]`

Here is my test code:

`var gplay = require('google-play-scraper');

gplay.search({term: "finans", num:249, country:"tr"}).then(console.log, console.log);`

**Comment by yura415** [comment]
Hi @erkansen . What you're seeing is Node.js REPL hiding results to compress screen space. You can either log each app from search results separately using `for` loop or stringify results to JSON before logging them to console (`JSON.stringify`). Also writing a script first in a file and then running it with `node script.js` would eliminate this issue.

Here is example code that you can run in REPL to see full results:
```js
var gplay = require('google-play-scraper');

gplay.search({term: "finans", num: 250, country:"tr"}).then(res => {
    console.log('total ' + res.length + ' items')
    for (let i = 0; i < res.length; i++) {
      console.log(res[i])
    }
  }).catch(err => console.error(err));
```

**Comment by erkansen** [comment]
Thank you @yura415. JSON.stringfy solved my problem.
It was my mistake. I am newbie for node.js.

@facundoolano What do you think about sorting the query not the result? Is there a way to query recent applications?

**Comment by facundoolano** [comment]
You can use the `list` method with the NEW_FREE and NEW_PAID collections.

Closing this.
