### ISSUE TITLE
Unhandled Promise Rejection When I try to list and to get permission

### ISSUE THREAD

**Issue by taykafasi** [facundoolano/google-play-scraper#191]
This is my repo which I work with google-play-scraper
https://github.com/taykafasi/play-store-scraping

In my app, firstly  I get permissions and append to permission.txt file with specific category in get-perm.js. While I'm doing this I get no error. Everything is OK. But after that I  run get-apps.js file to create an object what I named application. And application object looks like :
```
    var application = {};
    application.appId = '';
    application.title = '';
    application.score = '';
    application.maxInstalls = '';
```
and I assign the permissions with some regex to application object.  Then I append application object to data.txt file. 

`application.preventdevicefromsleeping : 1`

And I do that in async function recursively with a counter(number of apps how many I want to get). The function sometimes append 10 object to data.txt , sometimes 25. The error is :

**(node:4376) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): TypeError: Cannot read property 'split' of undefined
(node:4376) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.**

Is the problem about my code? I tried to solve it. I'm not sure exactly. Why it's happening? Thanks.

**Comment by facundoolano** [comment]
Sorry, I can't help you debug your code. If you find a problem with this library, please specify the error and an exact example of how to reproduce it (without unrelated code).
