### ISSUE TITLE
Problems with Google Play + Reviews issue

### ISSUE THREAD

**Issue by Nicoaguiar** [facundoolano/google-play-scraper#196]
I was scraping with a code of mine GP site during the last days when I saw that they have modified something on their website. Now I've to deal with a Content-Security-Policy problem. The html has being modified and there are some encripted classes in the code (for example rating-bar-container) 

There are issues with this scraper too, I've tried reviews, permissions and list of new apps; all are presenting problems. 
The reviews scripting is producing this output **"There was an error fetching the reviews!"**
Is it related to the modifications on the GP website? Someone else with the same error?

**Comment by facundoolano** [comment]
There have been issues with google changing there layout (see other issues). I'm closing this, if you have specific errors not covered by other open issues, please open a new one with code examples.
