### ISSUE TITLE
Google play CSS tags have changed

### ISSUE THREAD

**Issue by akshaykadidal** [facundoolano/google-play-scraper#200]
Hi Team,

I noticed that the CSS tags in the google play page have changed. 

I guess that is why this sample code is not working.

[var gplay = require('google-play-scraper');

gplay.app({appId: 'com.dxco.pandavszombies'})
  .then(console.log, console.log);](url)

**Comment by mklueh** [comment]
Not only do they have changed, they are now randomized and may be changed more often. I wonder how sb would make it working again under that circumstances without some machine learning...is there anything in work already?

**Comment by facundoolano** [comment]
Duplicate of #192
