### ISSUE TITLE
How to take reviews?

### ISSUE THREAD

**Issue by keyloguer** [facundoolano/google-play-scraper#202]
Hello guys,

I have this code above, and i want to change the 'console.log' to a information in a HTML page. Could anyone help me to solve this problem?

`var gplay = require('google-play-scraper')

const result = gplay.reviews({
    appId: 'com.mojang.minecraftpe',
    page: 0,
    sort: gplay.sort.HELPFUL
}).then(console.log, console.log);`

**Comment by facundoolano** [comment]
This is not directly related to this library, please look for assistance with JavaScript/Node.js elsewhere.
