### ISSUE TITLE
Installs count of application is parsed incorrect when using different country or language

### ISSUE THREAD

**Issue by yura415** [facundoolano/google-play-scraper#21]
Parsed app data:

```
title=Говорящий Том для Messenger, 
icon=https://lh5.ggpht.com/r2dtldlDODWJvySoohj_X8YuUTIdiLztJNBmlLAtAv0JpIkuZFDTqaC9JtxX1UP2ewQq=w300,
minInstalls=10,
maxInstalls=undefined,
score=4.3,
reviews=127,
description=< Long app"s description >,
developer=Outfit7,
genre=Связь,
price=0,
free=true,
video=https://www.youtube.com/embed/_SUqWk5bcS4,
url=https://play.google.com/store/apps/details?id=com.outfit7.tomformessengerfree&hl=ru,
appId=com.outfit7.tomformessengerfree
```

Mention that "minInstalls" is parsed as "10" and "maxInstalls" as "undefined". 
Original app url: https://play.google.com/store/apps/details?id=com.outfit7.tomformessengerfree&hl=ru

Install count is "10 000 000–50 000 000".

Issue is in ["cleantInt" function in "app.js"](/facundoolano/google-play-scraper/blob/1f91ce07eb868046fbe18683088722e947d17b0b/lib/app.js#L58) — only dots and commas are replaced but in different GPlay locales it can be spaces too.

**Comment by yura415** [comment]
Can you close this? https://github.com/facundoolano/google-play-scraper/pull/22

**Comment by facundoolano** [comment]
Yeah
