### ISSUE TITLE
needed category like game

### ISSUE THREAD

**Issue by sunnyrty** [facundoolano/google-play-scraper#217]
needed App category like game

 GAME: 'GAME',

i need like 

APP: 'APP'

all apps only

**Comment by facundoolano** [comment]
There's no "app" category in Google Play as far as I know, they're all apps. If you want a category that's missing please provide the url where it's taken from (e.g. https://play.google.com/store/apps/category/GAME)

**Comment by sunnyrty** [comment]
https://play.google.com/store/apps/collection/recommended_for_you_TRENDING_APPS_GAMES?clp=ogoGCAUqAggB:S:ANO1ljJuJiE

https://play.google.com/store/apps/collection/promotion_3000792_new_releases_apps?clp=SisKKQojcHJvbW90aW9uXzMwMDA3OTJfbmV3X3JlbGVhc2VzX2FwcHMQBxgD:S:ANO1ljJcFLs

like this
