### ISSUE TITLE
needed category like

### ISSUE THREAD

**Issue by sunnyrty** [facundoolano/google-play-scraper#218]
https://play.google.com/store/apps/collection/recommended_for_you_TRENDING_APPS_GAMES?clp=ogoGCAUqAggB:S:ANO1ljJuJiE

https://play.google.com/store/apps/collection/promotion_3000792_new_releases_apps?clp=SisKKQojcHJvbW90aW9uXzMwMDA3OTJfbmV3X3JlbGVhc2VzX2FwcHMQBxgD:S:ANO1ljJcFLs

like this

**Comment by facundoolano** [comment]
Those aren't categories, those are collections, and they can't be added to the library because they aren't generic, they depend on a specific user or time.
