### ISSUE TITLE
Use Scraper on Wordpress site

### ISSUE THREAD

**Issue by IbHacker** [facundoolano/google-play-scraper#222]
I have  tried to used it on my wordpress site but unfortunately I cannot, someone should help me please!
I am a student still learning coding.

**Comment by EasyGitHub99** [comment]
@IbHacker This isn't a wordpress plugin. But from a basic google search I've found this plugin: https://wordpress.org/plugins/google-play-store-app-search-and-insert/
Maybe you can use that, I'm not sure, I didn't check all the details.

**Comment by IbHacker** [comment]
@EasyGitHub99 Thank you so much, I gonna check it out.

**Comment by huoyinghui** [comment]
页面有变动： 
before:
-------
<script nonce="Xzm6ZeQVjCudYR3zKaOmtcpCcFo">
    AF_initDataCallback({
        key: 'ds:7',
        isError: false,
        hash: '18',
        data: function () {
            return ["34M", "1.4", "2.3 及更高版本"]
        }
    });
</script>

**Comment by facundoolano** [comment]
This is out of the scope of this library.
