### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by sunnyrty** [facundoolano/google-play-scraper#225]
"Cannot read property 'replace' of undefined"  new error

**Comment by huoyinghui** [comment]
结构有变动，淡定

**Comment by sunnyrty** [comment]
type in english

**Comment by sunnyrty** [comment]
ok

**Comment by sunnyrty** [comment]
ur change code works ?

**Comment by EasyGitHub99** [comment]
@sunnyrty can you post some code here that produces this error? thanks

**Comment by caucasianasian** [comment]
I have the same issue, using FullDetail: true when using gplay.list or gplay.developer. I think it's coming from the gplay.App function.

**Comment by shellerbrand** [comment]
Unfortunately, some of the mappings on the Google Play Pages have changed. There is already a pull request https://github.com/facundoolano/google-play-scraper/pull/224 addressing the issue. 

If you are looking for an immediate fix, then this may be useful.

**Comment by huoyinghui** [comment]
yee, we can see:
https://github.com/facundoolano/google-play-scraper/issues/223

**Comment by facundoolano** [comment]
Please provide example code that produces the issue and the version of the module you are using.

**Comment by victorfreitas** [comment]
@facundoolano See this image below, this error begins at line **178:51** of the file **lib/apps.js**, by which parameter **description** is arriving as undefined.

This error started this week. and there was no change in my application code.

**Node:** 8.11.1
**Express:** 4.16.3
**Google Play Scraper:** 6.0.1

![image](https://user-images.githubusercontent.com/21069978/39369133-dc8f961c-4a11-11e8-881d-60fa9e1e5aac.png)

**Comment by sunnyrty** [comment]
@facundoolano did u fix it

**Comment by sunnyrty** [comment]
Me fixed @huoyinghui  Code

**Comment by droidmanspace** [comment]
Same problem again after fix. After fix it only works for 1h ,again same error

**Comment by victorfreitas** [comment]
@droidmanspace Go back to the master version, it's working again.

**Comment by droidmanspace** [comment]
ok thank you.

**Comment by huoyinghui** [comment]
@facundoolano, ds:3 Has been restored 

'ds:3' : {id: 1.59150235E8 ,request:[["com.animocabrands.google.StarStableRun",7]
,2]
},'ds:4' : {id: 1.39809457E8 ,request:[null,["com.animocabrands.google.StarStableRun",7]
