### ISSUE TITLE
Again !!!!! TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by droidmanspace** [facundoolano/google-play-scraper#228]
```js
const MAPPINGS = {
    title: ['ds:4', 0, 0, 0],
    description: {
       path: ['ds:4', 0, 10, 0, 1],
       fun: descriptionText
    },
    description_html: ['ds:4', 0, 10, 0, 1],
    downloads: ['ds:4', 0, 12, 9, 0],
    votes: ['ds:6', 0, 0, 0],
    rating: ['ds:6', 0, 2, 1],
    size: ['ds:7', 0],
    supported_os: ['ds:7', 2],

    author: ['ds:4', 0, 12, 5, 1],
    author_link: ['ds:4', 0, 12, 5, 0, 0],
    categories: ['ds:4', 0, 12, 13, 0, 0],
    image: ['ds:4', 0, 12, 1, 3, 2],
    screenshots: {
        path: ['ds:4', 0, 12, 0],
        fun: R.map(R.path([3, 2]))
    },
    video_link: ['ds:4', 0, 12, 3, 0, 3, 2],
    video_image: ['ds:4', 0, 12, 3, 1, 3, 2],
    last_updated: {
        path: (['ds:4', 0, 12, 8, 0]),
        fun: (ts) => new Date(ts*1000).toISOString().split('T')[0]
    },
    version: ['ds:7', 1],
    whatsnew: ['ds:4', 0, 12, 6, 1]

};
```

### Error message:

```
TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (E:\google_play_node\node_modules\google-play-scraper\lib\app.js:123:52)
    at R.map (E:\google_play_node\node_modules\google-play-scraper\lib\app.js:117:21)
    at XWrap.f (E:\google_play_node\node_modules\ramda\dist\ramda.js:5955:28)
    at XWrap.@@transducer/step (E:\google_play_node\node_modules\ramda\dist\ramda.js:392:25)
    at _arrayReduce (E:\google_play_node\node_modules\ramda\dist\ramda.js:5137:46)
    at _reduce (E:\google_play_node\node_modules\ramda\dist\ramda.js:5167:24)
    at map (E:\google_play_node\node_modules\ramda\dist\ramda.js:5954:20)
    at E:\google_play_node\node_modules\ramda\dist\ramda.js:586:23
    at Object.f2 [as map] (E:\google_play_node\node_modules\ramda\dist\ramda.js:473:22)
    at extractFields (E:\google_play_node\node_modules\google-play-scraper\lib\app.js:111:14)
```

**Comment by droidmanspace** [comment]
change all ds:4 to ds:3 and ds:7 to ds: 5, Fixed for me.
Thanks for your motivation @facundoolano

**Comment by huoyinghui** [comment]
@droidmanspace 

https://github.com/huoyinghui/test_data/blob/master/gp_change/last_change_gpdetail/last_change_02_cat_jumping.jpg

**Comment by sunnyrty** [comment]
still not working

**Comment by gavnoe** [comment]
@huoyinghui what app you using to test code ?

**Comment by huoyinghui** [comment]
Can you speak chinese


| |
huoyinghui@stu
邮箱：hyhlinux@163.com
|

签名由 网易邮箱大师 定制

On 04/28/2018 14:55, gavnoe wrote:

@huoyinghui what app you using to test code ?

**Comment by huoyinghui** [comment]
把你的页面原始内容给我




| |
huoyinghui@stu
邮箱：hyhlinux@163.com
|

签名由 网易邮箱大师 定制

在2018年04月28日 15:40，huoyinghui@stu 写道：
Can you speak chinese


| |
huoyinghui@stu
邮箱：hyhlinux@163.com
|

签名由 网易邮箱大师 定制

On 04/28/2018 14:55, gavnoe wrote:

@huoyinghui what app you using to test code ?

**Comment by huoyinghui** [comment]
保存成html 然后给我链接，我确认一下页面数据




| |
huoyinghui@stu
邮箱：hyhlinux@163.com
|

签名由 网易邮箱大师 定制

在2018年04月28日 15:41，huoyinghui@stu 写道：
把你的页面原始内容给我




| |
huoyinghui@stu
邮箱：hyhlinux@163.com
|

签名由 网易邮箱大师 定制

在2018年04月28日 15:40，huoyinghui@stu 写道：
Can you speak chinese


| |
huoyinghui@stu
邮箱：hyhlinux@163.com
|

签名由 网易邮箱大师 定制

On 04/28/2018 14:55, gavnoe wrote:

@huoyinghui what app you using to test code ?

**Comment by gavnoe** [comment]
@huoyinghui 你用什么应用程序来测试你的数据？
你能给我你的Skype吗？

**Comment by gavnoe** [comment]
@huoyinghui what app you use to test data on this picture ? https://github.com/huoyinghui/test_data/blob/master/gp_change/last_change_gpdetail/last_change_02_cat_jumping.jpg?raw=true
