### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jodagm** [facundoolano/google-play-scraper#235]
* google-play-scraper version: 6.0.3

Cannot read property 'replace' of undefined 
when scraping this app:
https://play.google.com/store/apps/details?id=com.cultsotry.yanolja.nativeapp

```
google play scrape error TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/home/jonathan/axonite/axonite-scala-bridge/node_modules/google-play-scraper/lib/app.js:182:50)
    at R.map (/home/jonathan/axonite/axonite-scala-bridge/node_modules/google-play-scraper/lib/app.js:176:17)
    at XWrap.f (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:5954:20)
    at /home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/home/jonathan/axonite/axonite-scala-bridge/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/home/jonathan/axonite/axonite-scala-bridge/node_modules/google-play-scraper/lib/app.js:170:12)

```

**Comment by nowkin** [comment]
have the same problems with tons of apps

**Comment by zhaopengme** [comment]
+1

**Comment by sunnyrty** [comment]
same problem

**Comment by sunnyrty** [comment]
@huoyinghui help us

**Comment by huoyinghui** [comment]
https://github.com/facundoolano/google-play-scraper/issues/223

在 2018-05-31 19:01:34，"sunnyrty" <notifications@github.com> 写道：


@huoyinghui help us

**Comment by huoyinghui** [comment]
https://github.com/facundoolano/google-play-scraper/pull/224

if you need data now, you can merge in your own code, we should wait for more time,... maybe, it will change again

**Comment by sunnyrty** [comment]
@huoyinghui  tell me replace details .. bcz i have differenet servers

**Comment by sunnyrty** [comment]
65e4821 i will work ?

**Comment by nowkin** [comment]
replace all ds:3 with ds:4?

**Comment by sunnyrty** [comment]
@nowkin  email or facebook id

**Comment by huoyinghui** [comment]
https://github.com/facundoolano/google-play-scraper/issues/223
{
//ds:3
"1.59150235E8": -> ds:3 -> ds:4
//ds:5
"1.63762857E8": -> ds:5 -> ds:7
//ds:8
"1.4425375E8": -> ds:8 -> ds:10
//ds:10
"1.42707228E8": -> ds:10 -> ds:6
//comment
" 1.36880256E8": -> ds13 -> ds14
}

first1.replace"ds:10"
->2.replace"ds:8"
->3.replace"ds:5"
->4.replace"ds:3"

**Comment by sunnyrty** [comment]
first1.replace"ds:10"
->2.replace"ds:8"
->3.replace"ds:5"
->4.replace"ds:3" 

?/

**Comment by sunnyrty** [comment]
https://raw.githubusercontent.com/huoyinghui/static/master/gp_detail.jpg

how u find via google chrome ..
explain

**Comment by nowkin** [comment]
first1.replace"ds:10" -> ds:6
->2.replace"ds:8"->ds:10
->3.replace"ds:5"->ds:7
->4.replace"ds:3"->ds:4

thanks for that. that worked for me for the moment

**Comment by huoyinghui** [comment]
The Google page may change again, so you need to keep monitoring the changes, so it is not recommended to merge to the main branch. After the page is stable, we can submit the update mapping

**Comment by sunnyrty** [comment]
@huoyinghui  how we find in google chrome  about ds value..

**Comment by huoyinghui** [comment]
Read js...




| |
huoyinghui@stu
邮箱：hyhlinux@163.com
|

签名由 网易邮箱大师 定制

On 05/31/2018 19:37, sunnyrty wrote:

@huoyinghui how we find in google chrome about ds value..

**Comment by sunnyrty** [comment]
@huoyinghui thanks works... i didnot understand about read js in google chrome

**Comment by huoyinghui** [comment]
@sunnyrty , if you konw chinese..., i  will tell you more

**Comment by rdurelli** [comment]
I have the same problem. Could you please help me to make the API work again?

**Comment by sunnyrty** [comment]
@huoyinghui i did not know about chinese..... tell me .. i will understand.

**Comment by huoyinghui** [comment]
i will try, Wait a minute

**Comment by facundoolano** [comment]
If someone has a fix, please send a PR.

**Comment by huoyinghui** [comment]
@sunnyrty  https://github.com/huoyinghui/static/blob/master/detail.md

**Comment by sunnyrty** [comment]
@huoyinghui thanks man.... great helper....

**Comment by huoyinghui** [comment]
welcome, We should thank facundoolano !  I hope you can help the project in the future

**Comment by sunnyrty** [comment]
@facundoolano yes he is great guy... always thankfull him.. @huoyinghui ru using for site or app

**Comment by lmoldovan** [comment]
I have the same error. Please help!

**Comment by lmoldovan** [comment]
Above WA worked for me too! Thank you @huoyinghui! Is there any chance that they will change it again in the next days?  Thanks a lot again, you are great!!

**Comment by facundoolano** [comment]
Should be fixed on the dev branch. I'll publish a new version to npm over the weekend.
