### ISSUE TITLE
gplay.list({ category: gplay.category.GAME, collection: gplay.collection.TOP_FREE, start: 0, num: 50, country: 'ko', lang: 'kr', fullDetail: true })

### ISSUE THREAD

**Issue by elitebrain** [facundoolano/google-play-scraper#242]
I need Help.
How can I fix?
gplay.list({ country: 'ko', lang: 'kr' }) -> OK
gplay.list({ fullDetail: true }) -> OK

gplay.list({ country: 'ko', lang: 'kr', fullDetail: true }) -> error
--log--
(node:12816)` UnhandledPromiseRejectionWarning: Error: Error requesting Google Play:undefined
    at C:\Users\YeongHyeon\gamearth\node_modules\google-play-scraper\lib\utils\request.js:42:19
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:12816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

gplay.app({ appID: id, country: 'ko', lang: 'kr }) -> error
--log--
{ Error: Error requesting Google Play:undefined
    at C:\Users\YeongHyeon\gamearth\node_modules\google-play-scraper\lib\utils\request.js:42:19
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7) status: 400 }

**Comment by facundoolano** [comment]
Closing as this doesn't provide the required information.

**Comment by grashupfer99** [comment]
The `fullDetail` option works if you change your settings as follows: 
`country: 'kr', lang: 'ko'`
