### ISSUE TITLE
Automatic npm publish

### ISSUE THREAD

**Issue by filoozom** [facundoolano/google-play-scraper#243]
Hi, would it be possible to setup the automatic `npm` publishing feature of `Travis`? The documentation can be found here: https://docs.travis-ci.com/user/deployment/npm/, and it would automatically publish every commit / pull request pushed to a given branch. It's really easy to set up too!

This way, you would not need to publish new versions manually and we would always get the latest versions. Would also be great on https://github.com/facundoolano/app-store-scraper, which hasn't had an update for some time but has important fixes waiting.

**Comment by facundoolano** [comment]
I don't see much benefit in that, I still need to do the version commit and tag, which I currently do with `npm version` right before publishing. The main reason why I don't publish automatically is that I'm not usually around the laptop where I keep my personal projects, which wouldn't really change by enabling this feature.

I'm sorry that you don't like to wait for published version, but you can always point to a github commit in your package version until I get around to publishing.

**Comment by filoozom** [comment]
Hi, got it! In case you'd like to investigate this in the future, it is also possible to automatically create tags, and the version commit would be done directly in Pull Request. For example: https://github.com/travis-ci/travis-ci/issues/1476.

Then, each PR would bump the `package.json` (or trigger a Travis fail), and Travis would automatically push a tag and publish to `npm`.
