### ISSUE TITLE
Missing category: APPLICATION

### ISSUE THREAD

**Issue by nonphp** [facundoolano/google-play-scraper#250]
* Operating System: MacOS
* Node version: v8.11.3
* google-play-scraper version: 6.1.0 (npm)

### Description: 
Category "Applications" is missing in "category" constant but it is available in Google Play.

Example URL:
https://play.google.com/store/apps/category/APPLICATION/collection/topselling_free

### Example code:
```js
const gPlay = require('google-play-scraper')

gPlay.list({
  collection: 'topselling_free',
  category: 'APPLICATION',
})
  .catch(err => console.error(err))
```

### Error message:

```
Error: Invalid category APPLICATION
```

**Comment by facundoolano** [comment]
Fixed by #251
