### ISSUE TITLE
Option to get all the reviews?

### ISSUE THREAD

**Issue by vishrantgupta** [facundoolano/google-play-scraper#253]
Hi, is there an option to get all the reviews instead of page by page?

I saw the option of `page: 0,` but I need reviews from all the page not just from the first page.

**Comment by facundoolano** [comment]
No there's no such option. Just get all pages and join the result

**Comment by vishrantgupta** [comment]
In case someone with the same requirement, I have created a script using this repo.

https://github.com/vishrantgupta/scrap-google-play-review
