### ISSUE TITLE
Similar apps is broken

### ISSUE THREAD

**Issue by sampathkolanu** [facundoolano/google-play-scraper#254]
* Operating System: MAC
* Node version: 8.10.0
* google-play-scraper version: 6.1.0

### Description: 
Similar apps functionality doesn't work

### Example code:
```js
  gplay.similar({
    appId: "com.dxco.pandavszombies"
  }).then(console.log);
result: []
```
Looks like the url used to fetch similar apps is not working anymore, google is displaying blank page.
**example**: 
https://play.google.com/store/apps/similar?id=com.dxco.pandavszombies
which redirects to
https://play.google.com/store/apps/collection/similar?clp=qgEfCh0KF2NvbS5keGNvLnBhbmRhdnN6b21iaWVzEAEYAw%3D%3D:S:ANO1ljITHNU
with blank white page.

Also noticed that no similar apps are being displayed on the right side bar for apps in google play store. So, hoping this would be temporary

**Comment by yurganov** [comment]
Google has return similar apps. It is working now.
