### ISSUE TITLE
Is there a way to get list of all applications?.

### ISSUE THREAD

**Issue by harishvk27** [facundoolano/google-play-scraper#255]
I am looking at building a system, which stores in it's DB all applications and version details.

If there is any new version available on googlePlay update my local DB also.

Which means i am looking at some kind of subscribe-notify models from google-play apis.

**Comment by facundoolano** [comment]
No there is no way to do that. The closest you can get is to get all apps from all lists plus all apps from all possible searches (which would be a non trivial effort).
