### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by hexdump2002** [facundoolano/google-play-scraper#257]
Is there any way to use a proxy for all the connections made by the lib?

Cheers.

**Comment by facundoolano** [comment]
Yes, all methods support a `requestOptions` field where you can pass options for the request library; you can pass proxy options there. 

Not sure why it's not documented 🤔

**Comment by hexdump2002** [comment]
Well, yes, I just noticed it checking source code. I tried something like this:

gpScrapper.app(
    {appId: 'com.dxco.pandavszombies', 
        headers: {"Cache-Control" : "no-cache"}, 
        proxy: 'http://XX.XXX.XXX.XXX'})
  .then(result =>
  {
      console.log(result);
  })
  .catch(error =>
  {
    console.log(error);
  })

It shoudl work that way. am I right?

**Comment by facundoolano** [comment]
No, the object should be:

```js
{
  appId: 'com.dxco.pandavszombies', 
  headers: {"Cache-Control" : "no-cache"}, 
  requestOptinos: {proxy: 'http://XX.XXX.XXX.XXX'}
}
```

**Comment by Ji4n1ng** [comment]
`requestOptinos` is misspelled.

The correct one is:

```
{
  appId: 'com.dxco.pandavszombies', 
  headers: {"Cache-Control" : "no-cache"}, 
  requestOptions: {proxy: 'http://XX.XXX.XXX.XXX'}
}
```
