### ISSUE TITLE
JSON isn´t standard

### ISSUE THREAD

**Issue by sergioromcar** [facundoolano/google-play-scraper#260]
* Operating System: Ubuntu 18
* Node version: v8.10.0
* google-play-scraper version:

### Description: 
JSON isn´t standard
The fields should have double quotes

### Example code:
```js
{ "appId": "com.dxco.pandavszombies"}
instead 
{ appId: 'com.dxco.pandavszombies'}
```
Regards

**Comment by facundoolano** [comment]
This is not JSON, this is a javascript library that returns javascript objects.

**Comment by sergioromcar** [comment]
Perfect, used as a javascript object.
Thank you!!!
