### ISSUE TITLE
Some scraped App fields are undefined (score, scoreText, ratings, reviews) 

### ISSUE THREAD

**Issue by Alanz2223** [facundoolano/google-play-scraper#268]
* Operating System: Ubuntu 16
* Node version: 8.11
* google-play-scraper version: 6.1.0

### Description: 
I previously used this library on August 21 2018 to scrape full app details and everything worked great however I am trying to scrape again and some fields most importantly to me like (score, scoreText, ratings, reviews) are undefined for ALL apps so I am guessing the identifiers must have changed. Could someone verify this for me? Thanks

### Example code:
```js
let results = await gplay.list({
        category: cat,
        start : point.currently.index * opts.num,
        ...opts
        });

//results will not have the mentioned fields defined


```

### Error message:

```
no errors are being thrown
```

**Comment by facundoolano** [comment]
Please check with latest code from the dev branch (I merged some fixes today, but haven't got around publishing a new version yet).

**Comment by Alanz2223** [comment]
Works again thanks
