### ISSUE TITLE
[Question] App size

### ISSUE THREAD

**Issue by KaKi87** [facundoolano/google-play-scraper#272]
Hey,

Is app size always in `M` (megabyte) unit ?

Thanks !

**Comment by facundoolano** [comment]
I'm not sure to be honest, we use whatever google puts in the JavaScript data. I presume it's always the same dimension, although you could make a few tests to confirm (comparing with what's displayed in the website).

**Comment by KaKi87** [comment]
Well, I finally got a new example

https://play.google.com/store/apps/details?id=com.ksmobile.pro.launcher&hl=en&gl=us
size : `173k`

But I didn't found any heavier app than ~100M so it's still `M`

**Comment by facundoolano** [comment]
Can you check what's the library returning for that application?

**Comment by KaKi87** [comment]
Yes, `173k`

**Comment by KaKi87** [comment]
If you wanna see what I've done : https://playsearch.kaki87.net/ 😉
