### ISSUE TITLE
[Question] Getting errors when trying to use this library

### ISSUE THREAD

**Issue by emre1512** [facundoolano/google-play-scraper#273]
Hi, I am a JS newbie, sorry for this stupid question. I installed this library using npm. I try the code you provided:

```       
<script>
	var gplay = require('google-play-scraper');
	gplay.app({appId: 'com.dxco.pandavszombies'})
        .then(console.log, console.log);	
</script>
```

But I get `main.html:10 Uncaught ReferenceError: require is not defined` error.

Then I add `Require.js` to page and tried this:

```
<script src="require.js"></script>
<script>
        var gplay = require[('google-play-scraper')];
        gplay.app({appId: 'com.dxco.pandavszombies'})
        .then(console.log, console.log);
</script>
```

But now it says `Uncaught TypeError: Cannot read property 'app' of undefined`

As a newbie, I would be very happy if somebody helps me with this. 

My project structure looks like **[this](https://cdn1.imggmi.com/uploads/2018/9/22/e37c2ee90c18cfb42854263a7a54473f-full.png)**.

**Comment by facundoolano** [comment]
This is a node.js project, it's not intended to run in the browser.
