### ISSUE TITLE
CORB error while fetching

### ISSUE THREAD

**Issue by kizivat** [facundoolano/google-play-scraper#274]
* Operating System: Ubuntu 18.04
* Node version: v8.10.0
* google-play-scraper version: 6.2.0

### Description: 
I tried to use google-play-scraper version in browser app using browserify. I get the below errors in Chrome.

I suppose you don't really know exactly how the module behaves when browserified. However, it seems to me that the problem shouldn't be caused by browerifying. Is this a known issue. Do you have any idea what might cause this? It seems to me like something changed on the Google server side. Is the module still working for others?

Thanks.

### Example code:
```js
gplay.app({appId: 'com.sgn.pandapop.gp'})
            .then(console.log, console.log);
```

### Error message:

```
Failed to load https://play.google.com/store/apps/details?id=com.sgn.pandapop.gp&hl=en&gl=us: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:18080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
VM813:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://play.google.com/store/apps/details?id=com.sgn.pandapop.gp&hl=en&gl=us with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by facundoolano** [comment]
CORS is a browser thing, totally outside the scope of this library.

**Comment by adeiry** [comment]
@kizivat  do you resolve this problem? do you find a solution????

**Comment by adeiry** [comment]
@facundoolano I have the exact same problem while using this library. please help me fix it. any ideas? or solutions???

**Comment by adeiry** [comment]
@kizivat I have the exact same problem while using this library. please help me fix it. any ideas? any solutions???

**Comment by arddluma** [comment]
> @kizivat I have the exact same problem while using this library. please help me fix it. any ideas? any solutions???

Same.

**Comment by ddamddam** [comment]
Same here. I found out 'jsonp' can be solution. If I fix it. I'll post about it.
