### ISSUE TITLE
Search pagination

### ISSUE THREAD

**Issue by mortalis13** [facundoolano/google-play-scraper#275]
Hi.
Can I request next pages with `search()`?
If I use the default `num` of **20** to prevent overloading the request I'd like to get the next **20** results in the search.
I found `requestOptions` with `start` option but not sure how to use it.
Thanks.

**Comment by facundoolano** [comment]
No, there's no pagination for search, you can only control the amount of results of the single request. But I think one 250 results search is going to be more efficient than twelve 20 results searches anyway.
