### ISSUE TITLE
[Question] Error requesting Google Play:undefined Status 500

### ISSUE THREAD

**Issue by ouchadam** [facundoolano/google-play-scraper#277]
* Operating System: Google cloud function
* Node version: 6.11.5
* google-play-scraper version: 6.2.0

### Description: 

Hello, when running the scraper locally I have no issues, but recently whilst running on a cron'd server I'm seeing the below error with the status 500.

This error only occurs for `reviews`. `listing` etc is working fine.

I'm assuming this is some sort of IP ban however I wasn't expecting to see a 500, perhaps its worth logging more information in this case?

### Example code:
```js

const googlePlay = require('google-play-scraper')

const fetchReviews = (appId) => {
    return googlePlay.reviews({
        appId: appId,
        page: 0,
        sort: googlePlay.sort.NEWEST,
        throttle: 1
    })
}

fetchReviews("com.facebook.katana").then(console.log).catch(console.log)
```

### Error message:

```
{ 
    Error: Error requesting Google Play:undefined
    at Error (native)
    at /user_code/node_modules/dashboard-plugins/node_modules/google-play-scraper/lib/utils/request.js:42:19
    at process._tickDomainCallback (internal/process/next_tick.js:135:7) 
    status: 500 
}
```

**Comment by facundoolano** [comment]
If you run in debug mode(set the environment variable: DEBUG=google-play-scraper), perhaps you would get more insight into what the error is exactly (and perhaps how to better respond to it)

**Comment by mang-design** [comment]
Not sure if it will be relevant to you, but for me it was a network issue (500 error is a server error). I was connected to a VPN, when I disconnected the 500 error disappeared.

**Comment by facundoolano** [comment]
Closing this due to lack of details to make it actionable (example code works).
