### ISSUE TITLE
Simillar don't work with language

### ISSUE THREAD

**Issue by vitaliy901** [facundoolano/google-play-scraper#279]
When i'm trying to access to GP Simillar it don't work with language choose (

```
const gpScrap = require('google-play-scraper');

gpScrap.similar({appId: 'com.facebook.katana', lang: 'fr'})
.then(res => {
  console.log(res);
})
```

Result: 
`[ { url:
     'https://play.google.com/store/apps/details?id=com.snapchat.android',
    appId: 'com.snapchat.android',
    title: 'Snapchat',
    summary: 'Life\'s more fun when you live in the moment :)',
    developer: 'Snap Inc',
    developerId: 'Snap+Inc',
    icon:
     '//lh4.ggpht.com/vdK_CsMSsJoYvJpYgaj91fiJ1T8rnSHHbXL0Em378kQaaf_BGyvUek2aU9z2qbxJCAFV=w340',
    score: 4,
    scoreText: 'Оцінка: 4,1 із п’яти зірочок',
    priceText: '',
    free: true }...]`

**Comment by facundoolano** [comment]
Can you please provide version and sample code (including the app and language you used) to reproduce this issue?

**Comment by gavnoe** [comment]
@facundoolano yes i'm added sample to issue, as you see it doesn't changing language

**Comment by yurganov** [comment]
@gavnoe Yes, google similar page does not regard language.

This is log of requests which made by @facundoolano google-play-scrapper.

  ```
google-play-scraper Making request: {"url":"https://play.google.com/store/apps/similar?id=com.whatsapp&hl=us","followAllRedirects":true} +797ms
  google-play-scraper Request finished +724ms
  google-play-scraper Making request: {"url":"https://play.google.com/store/apps/similar?id=com.whatsapp&hl=ru","followAllRedirects":true} +33s
  google-play-scraper Request finished +948ms
  google-play-scraper Making request: {"url":"https://play.google.com/store/apps/similar?id=com.whatsapp&hl=fr","followAllRedirects":true} +2s
  google-play-scraper Request finished +749ms
```

As you can see, I've change lang parameter, and it is correctly passed inside of lib, but if you open this pages by yourself you'll see that they are same, and made for your country.

Only option here is to use geo-proxy. ¯\_(ツ)_/¯

**Comment by hunnapikes** [comment]
Now works, uses Lang and Country params.

**Comment by facundoolano** [comment]
Thanks @hunnapikes
