### ISSUE TITLE
how to get all the rviews concerning an app 

### ISSUE THREAD

**Issue by soumitra9** [facundoolano/google-play-scraper#282]
* Operating System:
* Node version:
* google-play-scraper version:

### Description: 
Describe your issue here

### Example code:
```js
// Put code to reproduce the issue here
```

### Error message:

```
Put error message here
```
Hi, I s it possible to get all the review concerning an app on playstore. I have an app that contains nearly 1000 reviews but I am getting only 40, irrespective of page number , basically they give same results

**Comment by facundoolano** [comment]
This doesn't provide necessary information to reproduce. Paging seems to work on a quick check.

https://github.com/facundoolano/google-play-scraper#reviews
```
Note that this method returns reviews in a specific language (english by default), so you need to try different languages to get more reviews. Also, the counter displayed in the Google Play page refers to the total number of 1-5 stars ratings the application has, not the written reviews count. So if the app has 100k ratings, don't expect to get 100k reviews by using this method.
```
