### ISSUE TITLE
Is 'review' feature still working?

### ISSUE THREAD

**Issue by r76941156** [facundoolano/google-play-scraper#287]
* Operating System:
* Node version:
* google-play-scraper version:

### Description: 
I was unable to run the example.

### Example code:
```js
// Put code to reproduce the issue here
```

### Error message:
{ Error: Error requesting Google Play:undefined
    at Error (native)
    at /srv/readcomp/node_modules/google-play-scraper/lib/utils/request.js:42:19
    at process._tickCallback (internal/process/next_tick.js:109:7) status: 503 }

**Comment by r76941156** [comment]
Looks like they will reject my calls if I want to get a lot of reviews. Is anyone know how to avoid this ? Thanks.

**Comment by facundoolano** [comment]
You cal use [throttling](https://github.com/facundoolano/google-play-scraper#throttling) to add some delay between calls when you need to do a lot of requests.
