### ISSUE TITLE
app methods failed

### ISSUE THREAD

**Issue by gocpplua** [facundoolano/google-play-scraper#292]
first i download nodejs, then:
var gplay = require('google-play-scraper');
gplay.app({appId: 'com.dxco.pandavszombies'})
  .then(console.log, console.log);

but there is something wrong:
PS D:\Program Files\nodejs\node_modules\npm\node_modules\google-play-api-master> node "D:\Program Files\nodejs\node_modu
les\npm\node_modules\google-play-api-master\a.js"
(node:1472) UnhandledPromiseRejectionWarning: Error: Error requesting Google Play:read ECONNRESET
    at D:\Program Files\nodejs\node_modules\npm\node_modules\google-play-api-master\node_modules\google-play-scraper\lib\utils\request.js:42:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

how can i resolve it

**Comment by yurganov** [comment]
It seems, that you have some network issues, oe google is blocking your IP

Try to use proxy
