### ISSUE TITLE
Reviews method ALWAYS return only 1 page

### ISSUE THREAD

**Issue by jelecool** [facundoolano/google-play-scraper#295]
* Operating System: Mac OSX Mojave
* Node version: v11.6.0
* google-play-scraper version: 6.2.2

### Description: 
It is impossible to receive more than 40 reviews even though opts are passed through the function call.

### Code:
```js
// File named : scraper.js
const scraper = require('google-play-scraper');


let pages = async () => {
    let result = await scraper.reviews({appId:'com.myfitnesspal.android', page:5});
    console.log(result.length);
}

pages();

```
### Output:
```sh
$ node scraper
$ 40
```

**Comment by facundoolano** [comment]
Each page has at most 40 results. If you change the page you don't get _more_ results, you get _different_ results. If you want more than 40 just chain the results of multiple pages.

```
> gp.reviews({appId:'com.myfitnesspal.android', page:5}).then((r) => console.log(r[0].text))
'Great app for weight loosing fans :)',

> gp.reviews({appId:'com.myfitnesspal.android', page:6}).then((r) => console.log(r[0].text))
 'my Fitbit won\'t sync it\'s annoying af'
```
