### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by thomasMistplay** [facundoolano/google-play-scraper#296]
* Operating System: MAC OS 10.13.6
* Node version: 8.11.1
* google-play-scraper version: 6.2.3

### Description: 
When calling the `.app` function of the scraper, I almost always get an error now. The error reads `TypeError: Cannot read property 'replace' of undefined`. This issue seems similar to one that happened last year, but I believe that it is resurfacing now.

### Example code:
```js
scraper.app({ 
    appId: 'es.socialpoint.DragonCity',
    country: 'us',
    lang: 'en',
    throttle: 10,
})
```

### Error message:

```
TypeError: Cannot read property 'replace' of undefined
```

**Comment by yurganov** [comment]
Hello,

Are you sure that you using latest version of the google-play-scrapper.
I've try your code, and it is working for me.

This problem is probably because of bad mappings, and it was fixed in the latest release.

Could you please provide output of 

```npm list google-play-scraper``` in your project's npm directory?

**Comment by jelecool** [comment]
Hi,

I had the same issue but updating it solved the error for me.

Hope it solves it for you too!

**Comment by facundoolano** [comment]
I'm considering this fixed.
