### ISSUE TITLE
Slow queries

### ISSUE THREAD

**Issue by FcoCGN** [facundoolano/google-play-scraper#297]
* Operating System: Linux 18.04
* Node version: 8.10.0
* google-play-scraper version: 6.2.3

### Description: 
In all queries, my TTFB response time is high.
Example query: http://192.168.1.200:3000/api/apps/?collection=topselling_free&num=100&start=0&country=us&lang=en&fullDetail=true, 5.82s for the TTFB.

![image](https://user-images.githubusercontent.com/33829593/52780948-ab87e080-304b-11e9-90d9-b3a61f6db8b8.png)

**Comment by yurganov** [comment]
You should call your ISP and increase your internet speed.

**Comment by yurganov** [comment]
TTFB is only metric that said how much time passed from request to first bytes of response.

So, if you have some troubles with time of response, you should check your code, your internet speed and your PC.

This is my TTFB:

![image](https://user-images.githubusercontent.com/3879335/52790398-7abda080-3077-11e9-861f-bf0a63948017.png)
