### ISSUE TITLE
similar method doesn't work!!

### ISSUE THREAD

**Issue by MojtabaRazmi** [facundoolano/google-play-scraper#306]
* Operating System: windows
* Node version:10.13.0
* google-play-scraper version:6.2.3

### Description: 
for each app id thath i send to this method i got this error

### Example code:
```js
 gplay.similar({
  appId: 'com.miniclip.eightballpool'
}).then(res=>console.log('res : ',res)).catch(err=>console.log('err:',err))
```

### Error message:
err: { Error: App not found (404)
    at E:\projects\google-play-crawler-node\node_modules\google-play-scraper\lib\utils\request.js:42:19
    at process._tickCallback (internal/process/next_tick.js:68:7) status: 404 }

**Comment by facundoolano** [comment]
duplicated #304

**Comment by MojtabaRazmi** [comment]
> duplicated #304

why close my issue?
i cant find my answer in issue that you comment
i need to this method !!!
