### ISSUE TITLE
some Methods in google-play-scraper not working properly

### ISSUE THREAD

**Issue by sugan22** [facundoolano/google-play-scraper#308]
* Operating System: Mac Os 10.14.4
* Node version: 10.15.3
* google-play-scraper version:6.2.3

### Description: 
some Methods in google-play-scraper not working properly

### Example code:
```js
// Issue 1:var gplay = require('google-play-scraper');
gplay.similar({appId: "com.dxco.pandavszombies"}).then(console.log);
Issue 2:var gplay = require('google-play-scraper');
gplay.permissions({appId: "com.dxco.pandavszombies"}).then(console.log);
Issue:3var gplay = require('google-play-scraper');
gplay.developer({devId: "DxCo Games"}).then(console.log);
Issue 4:var gplay = require('google-play-scraper');
gplay.search({
    term: "panda",
    num: 2
  }).then(console.log, console.log);

Issue 5: var gplay = require('google-play-scraper');
gplay.categories().then(console.log);
```

### Error message:
Issue 1:  UnhandledPromiseRejectionWarning: Error: App not found (404)
Issue 2: UnhandledPromiseRejectionWarning: Error: App not found (404)
Issue3: {}
Issue4: []
Issue5: output : ['APPLICATION']
```
Put error message here
```
Note: I installed latest google-play-scraper 6.2.3 
tried testing in this url https://npm.runkit.com/google-play-scraper/test/lib.permissions.js?t=1556741098039 same error occurred.

can you please help me what I am missing?

**Comment by facundoolano** [comment]
These are already reported and being worked on.

**Comment by sugan22** [comment]
Query: npm install google-play-scraper package pointing to Dev environment?
Is there PROD environment to test our API calls ?
