### ISSUE TITLE
[Bug] Search : fullDetail not working

### ISSUE THREAD

**Issue by KaKi87** [facundoolano/google-play-scraper#309]
Hello,

```js
Promise.all([true, false].map(state => require('google-play-scraper').search({ term: 'web browser', num: 1, fullDetail: state }))).then(results => console.log(JSON.parse(results[0]) === JSON.parse(results[1])));
```

This test code, which returns `true`, proves that wether `fullDetail` is set at `true` or `false`, the returned result is the same.

So, now we have to manually get app details by ID.

I also would like to say, without intentionally being rude, that your project lacks of maintainability.

Thanks !

**Comment by tanqhnguyen** [comment]
Instead of saying the project lacks of maintainability, perhaps you can also create a PR and help fix the bug :). It's an open source project after all, everyone is more than welcomed to contribute

**Comment by facundoolano** [comment]
> I also would like to say, without intentionally being rude, that your project lacks of maintainability.

Without being rude, you need to tune your expectations. I don't get paid for this, nor I hold any technical interest in it. I just organize the work of the contributors, that make an effort to keep it working.

**Comment by KaKi87** [comment]
Wether my work is free or paid, I always make sure that it is 100% working before releasing a new version and I don't release anything if I'm not sure that I can maintain it. On the other hand, I would prefer to deprecate my project if I want to stop working on it, instead of just saying "you are welcome to contribute" lol. If I use your module it's because my own open source project which I actively maintain depends on it. When people send me a message on Reddit or Stackexchange to tell me "your search engine isn't working", it's actually google-play-scraper which doesn't work...

**Comment by facundoolano** [comment]
Too bad for you buddy, don't assume everyone else proceeds the same way as you do.

**Comment by KaKi87** [comment]
I like doing complete work wether I'm paid or not.

Did you fixed the problem ? Because you closed the issue

**Comment by facundoolano** [comment]
If work is complete how come your search engine keeps breaking?

**Comment by KaKi87** [comment]
Because *your* work isn't complete 😅

**Comment by facundoolano** [comment]
that's like your opinion man

**Comment by tanqhnguyen** [comment]
> Because _your_ work isn't complete 😅

Web scraping depends (totally) on a third party service, in this case, it's Google Play. If the scraper doesn't work (anymore), go blame Google Play and their new page structure :) Can't do much if they suddenly decided to change their entire webpage structure.

This project by no mean is incomplete, we have been using it for the past year. Instead of saying rude things about the project, how about you actually contribute and fix it, it's what open-source means

If you think this project is not complete, then don't use it, no one forces you to
