### ISSUE TITLE
How i can scap Contains Ads·Offers in-app purchases

### ISSUE THREAD

**Issue by codex49** [facundoolano/google-play-scraper#316]
I didn't foud the item of Contains Ads·Offers in-app purchases,
How i can scrape it ?

**Comment by facundoolano** [comment]
If you comment [this line](https://github.com/facundoolano/google-play-scraper/blob/dev/lib/app.js#L34-L35) you get the raw data that's used to extract the fields that are included in the scraped app data. If the data you want to add is there somewhere, you can then add its path to the MAPPINGS object to start parsing it and send a PR with that change.
