### ISSUE TITLE
Add error details

### ISSUE THREAD

**Issue by ghost** [facundoolano/google-play-scraper#32]
After some point, Google rejects my requests giving me a 503 code. Does anyone know the JSON format of the error so I can parse it and throw a more detailed and informative error?

**Comment by facundoolano** [comment]
I'm guessing you're facing a throttling limit from google after making too many requests. In that case I doubt you're going to get an informative error response.

In any case, maybe inspecting the error parameter [here](https://github.com/facundoolano/google-play-scraper/blob/dev/lib/helpers.js#L5) can give you some idea of what's going on.

Please let me know what you find out, it may be useful to improve error handling in the module.

**Comment by pavanrangain** [comment]
Just curious. Do we know whats the throttling limit may be?

**Comment by facundoolano** [comment]
No idea.

**Comment by facundoolano** [comment]
FYI added a throttling option to avoid these issues: https://github.com/facundoolano/google-play-scraper#throttling
