### ISSUE TITLE
Similar Apps returning error (data.path undefined)

### ISSUE THREAD

**Issue by pperezlabcave** [facundoolano/google-play-scraper#325]
* Operating System:MacOS Mojave 10.14.1
* Node version: v10.16.0
* google-play-scraper version: ^6.2.6

### Description: 
I am getting 
"Error: not found similar link" 
when I try to use the method ".similar()"

The problem when I look through the code is that it doesn't get the data.path of the similars. 
(The scraper instead of something like this
https://play.google.com/store/apps/collection/cluster?clp=ogoaCBEqAggIMhIKDGNvbS53aGF0c2FwcBABGAM%3D:S:ANO1ljK-eg8&gsr=Ch2iChoIESoCCAgyEgoMY29tLndoYXRzYXBwEAEYAw%3D%3D:S:ANO1ljJY_LY
it gets undefined)

It seems to be that google has change something because it used to work fine.
Thanks in advance

### Example code:
```js
gplay.similar({appId: "com.whatsapp"}).then(console.log);
```

### Error message:

```
Error: not found similar link
    at request.then.then.then.data (/node_modules/google-play-scraper/lib/similar.js:38:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by pperezlabcave** [comment]
It is related to #324 
changing in similar.js 
const PATH_MAPPING = {
  path: ['ds:7', 1, 1, 0, 0, 3, 4, 2]
};
solves the issue.

If this is correct can you commit/push?

**Comment by lgc** [comment]
https://github.com/facundoolano/google-play-scraper/pull/327
