### ISSUE TITLE
socket hang up

### ISSUE THREAD

**Issue by moelfassi** [facundoolano/google-play-scraper#329]
os: Mac
### Description: 
after adding to my list `num : 100` i receive this 
### Error:
```
{ Error: Error requesting Google Play:socket hang up
    at /Users/elfassimounir/Documents/Js_Projects/gplayData/node_modules/google-play-scraper/lib/utils/request.js:44:19
    at process._tickCallback (internal/process/next_tick.js:68:7) status: undefined }
```

when `num:20 ` it works just fine
### Example code:
```js
gplay.list({
        category: gplay.category.BUSINESS,
        collection: gplay.collection.NEW_FREE,
        num: 100,
        fullDetail: true,
    })
        .then(console.log, console.log);
```
please help

**Comment by moelfassi** [comment]
after testing this code on my server it worked (num : 100) why wouldnt on my mac?

**Comment by yurganov** [comment]
Probably you have some network issues with connecting to Google Play.

**Comment by Isaamarod** [comment]
I found the solution here:

https://medium.com/@srijansrinetra/scrapping-amazon-with-nodejs-using-cheerio-and-request-part-1-4f7f4bdd4307

This happens when so many requests are send at a time. Then you have to copy this code BEFORE the scrapping function.

```
var http = require('http');
var https = require('https');
http.globalAgent.maxSockets = 1;
https.globalAgent.maxSockets = 1;
```
