### ISSUE TITLE
Url when fullDetail is true 

### ISSUE THREAD

**Issue by karvounis-iqu** [facundoolano/google-play-scraper#33]
When it scrapes with fullDetail false, the url is just a string that can be extracted. However, when I scrape using fullDetail true, then the url is like that:  
url: 
     { parse: [Function: urlParse],
       resolve: [Function: urlResolve],
       resolveObject: [Function: urlResolveObject],
       format: [Function: urlFormat],
       Url: [Function: Url] },
Can somebody help me how to get the whole url?

**Comment by facundoolano** [comment]
@karvounis-iqu I think this is a bug introduced with the last changes. Just commited a fix, can you check the latest code solves your problem?

**Comment by karvounis-iqu** [comment]
@facundoolano It works like a charm now! 
Cheers man!
