### ISSUE TITLE
[Q] How to scrap more than 120 app details

### ISSUE THREAD

**Issue by SwapnilSoni1999** [facundoolano/google-play-scraper#330]
No issues tho 😅 just the question only.

**Comment by yurganov** [comment]
Try to use for loop

**Comment by SwapnilSoni1999** [comment]
@yurganov elaborate a little more please, would be helpful.

**Comment by facundoolano** [comment]
@SwapnilSoni1999 closing as you didn't give details yourself about what you want to accomplish exactly.
