### ISSUE TITLE
suddenly fires error 'App not found (404)'  on request

### ISSUE THREAD

**Issue by gamechosun** [facundoolano/google-play-scraper#333]
* Operating System: Windows7, centos
* Node version: 10.15.3
* google-play-scraper version: 6.2.7

Description: 
I implemented this module in my service and worked well. 
recently, module fires 'App not found(404)' error 70~80% of request. 
strange thing is request success sometime.

Example code:
var G = require('google-play-scraper');
G.list({
    category: G.category.GAME,
    collection: G.collection.GROSSING,
    start: 0,
    num: 20,
    lang: 'ko',
    country: 'kr',
    throttle: 10
}).then(console.log, console.log)

Error message:

{ Error: App not found (404)
    at d:\workspace\googleplayscraper\node_modules\google-play-scraper\lib\utils\request.js:44:19
    at process._tickCallback (internal/process/next_tick.js:68:7) status: 404 }

**Comment by vitaliy901** [comment]
yes have that error on category only page too ... :(

**Comment by marxsk** [comment]
I have the very same issue when I attempt to download reviews.

**Comment by takeTrace** [comment]
same issue + 1

**Comment by xulifan** [comment]
I think Google updated the links of play store today.

**Comment by mitchross** [comment]
Bump on this too

**Comment by marxsk** [comment]
Can anyone confirm that updated version should use /batchexecute (used by web browser) ?

**Comment by vitaliy901** [comment]
@xulifan i see that links not changes ( but it doesn't works... something strange. Request is throw 404, but when i try curl on my ubuntu server it's opening (

**Comment by marxsk** [comment]
@xulifan can you pls send me your curl command? So I can take a closer look at it?

**Comment by xulifan** [comment]
@marxsk For example, for collection TOP GROSS and category GAME, the generated URL https://play.google.com/store/apps/category/GAME/collection/topgrossing?hl=en&gl=jp is no longer available. 
From https://play.google.com/store/apps/top/category/GAME , we can see the link for TOP GROSS game is https://play.google.com/store/apps/collection/cluster?clp=0g4YChYKEHRvcGdyb3NzaW5nX0dBTUUQBxgD:S:ANO1ljLhYwQ&gsr=ChvSDhgKFgoQdG9wZ3Jvc3NpbmdfR0FNRRAHGAM%3D:S:ANO1ljIKta8

**Comment by andylauxugang2** [comment]
Bump on this too for me

**Comment by icarcal** [comment]
Hey guys!
Had the same problem.
Investigating it yesterday I found the following URL: https://play.google.com/store/apps/top/category/SHOPPING (you can use for all the categories)

I made a *REALLY QUICK* fix, [here](https://github.com/icarcal/google-play-scraper).
There is a lot of duplicated code, I made this just to get yesterday's data and it is not 100% thought.
I'm planning to fix it and send a PR by tomorrow.

There is just one little problem, the cluster URLs allow us to get only 195 apps, and the implementation is a little bit different from the original (we can't get the start + number of apps).

There is also a problem with reviews that I'm investigating.
The url https://play.google.com/store/getreviews also returns 404 :(

**Comment by yurganov** [comment]
Great work.

But why you made limit of 195?

You messed up limit per one request and total limit

So, it *is* possible to get more than 195 apps totally, but you cannot get more than 195 per request, and after that you run next request with another token. 

Am I wrong?

**Comment by icarcal** [comment]
@yurganov

I think that I've used the same logic from search requests (changing the token and everything else).

If you check for example the following url:
https://play.google.com/store/apps/collection/cluster?clp=CiAKHgoYdG9wc2VsbGluZ19mcmVlX1NIT1BQSU5HEAcYAw%3D%3D:S:ANO1ljKk2A4&gsr=CiIKIAoeChh0b3BzZWxsaW5nX2ZyZWVfU0hPUFBJTkcQBxgD:S:ANO1ljI0fpo

 It allows you to get only 200 apps (with the batchexecute).
But I'm still looking into it and going to take what you said in consideration, thanks!

**Comment by yurganov** [comment]
I will send you PR now

**Comment by yurganov** [comment]
@icarcal cannot send PR, check this out, please

I think it is working good

https://github.com/yurganov/google-play-scraper/commit/11ee62f6f68d805b262a29953b8abf82139a2387?diff=split

But sometimes it ends earlier (i try to get 600 apps, and get only 200)

I think there is some problem with detecting token, or something...

**Comment by yurganov** [comment]
I checked it on google

It is working randomly - some time it gives only 200, sometime 660

https://play.google.com/store/apps/collection/cluster?clp=0g4jCiEKG3RvcHNlbGxpbmdfZnJlZV9HQU1FX0FDVElPThAHGAM%3D:S:ANO1ljKHNjI&gsr=CibSDiMKIQobdG9wc2VsbGluZ19mcmVlX0dBTUVfQUNUSU9OEAcYAw%3D%3D:S:ANO1ljLUxfQ&hl=ru&gl=ru

**Comment by abubakaraziz** [comment]
There is an issue on getting permissions data of applications. gplay. permissions return 404 error e.g App not Found

**Comment by yurganov** [comment]
@icarcal you also have wrong collection mapping

check this out:

https://play.google.com/store/apps/top/category/TOOLS
vs
https://play.google.com/store/apps/top/category/GAME

The "Paid" in Tools is 4th, and in Game is 3th

I do not know better solution instead of making first request with hl=en and regexp cluster URLs like this:

`switch (opts.collection) {
          case 'topselling_paid':
            var regex = /Top Paid.*?\"(\/store.*?cluster.*?)\"/g;
          case 'topselling_free':
            var regex = /Top Free.*?\"(\/store.*?cluster.*?)\"/g;
          case 'topselling_grossing':
            var regex = /Top Grossing.*?\"(\/store.*?cluster.*?)\"/g;
          default:
            var regex = /Top Free.*?\"(\/store.*?cluster.*?)\"/g;
        }
        var clusterLink = regex.exec(body);`

**Comment by icarcal** [comment]
@yurganov yes!
The GAMES related category have this difference, I currently working on this right now!
I think the FAMILY related ones have this issue to.
The fix that I made was for my company not to lose all the data for yesterday.
We managed to get some correct data yesterday, and I working to fix all this little problems today, implement tests, remove duplicated code, etc.

Thanks for all the considerations

**Comment by yurganov** [comment]
@icarcal you my hero!

**Comment by icarcal** [comment]
@yurganov 

I was able to sometimes get 400 and sometimes 200 apps (my branch was really with a token problem, thanks for pointing that out), but google seems to respond randomly as you said.
I had some problems with results, because sometimes collections were "changing places".
For example DATING  for country br and language pt-BR, returns no paid app, but for other countries such as us it return paid apps (I made a little workaround for this, but I'm going to look deep into it).

I fixed the categories endpoint and tests as well.

[Here](https://github.com/icarcal/google-play-scraper) you can check the work that I'm currently doing.
It is still not 100%, but it is way better than the first time that we discussed it here.

**Comment by mitchross** [comment]
@icarcal I pulled your code down locally, reviews still do not work.

**Comment by icarcal** [comment]
Hey guys!
I have updated the following methods:
 ```.list```
 ```.reviews```
 ```.permissions```
 ```.categories```

 ```.list ``` and  ```.reviews ``` methods introduce some breaking changes, since google allow you to fetch data only through ```batchexecute``` endpoint.
You can now only send the ```num``` parameter (it will allow you to fetch the desired number of category apps and reviews).
The ```.list``` method is unstable right now, since google sometimes respond with 200 apps, and sometimes more (for example 600 and so on), as pointed out by @yurganov

> It is working randomly - some time it gives only 200, sometime 660
 
For the ```.permissions``` method I've added the ```type``` parameter to the response (since this is not a breaking change but add value to it).
For the ```.reviews``` method I've added the ```thumbsUp``` and ```version``` parameters, this is also not a breaking change.

I've also updated the tests and docs

The PR #337 is up now for approval

**Comment by antoniobonna** [comment]
> Hey guys!
> I have updated the following methods:
> `.list`
> `.reviews`
> `.permissions`
> `.categories`
> 
> `.list ` and `.reviews ` methods introduce some breaking changes, since google allow you to fetch data only through `batchexecute` endpoint.
> You can now only send the `num` parameter (it will allow you to fetch the desired number of category apps and reviews).
> The `.list` method is unstable right now, since google sometimes respond with 200 apps, and sometimes more (for example 600 and so on), as pointed out by @yurganov
> 
> > It is working randomly - some time it gives only 200, sometime 660
> 
> For the `.permissions` method I've added the `type` parameter to the response (since this is not a breaking change but add value to it).
> For the `.reviews` method I've added the `thumbsUp` and `version` parameters, this is also not a breaking change.
> 
> I've also updated the tests and docs
> 
> The PR #337 is up now for review

How can I use reviews now?
