### ISSUE TITLE
Error: App not found (404) For List api 

### ISSUE THREAD

**Issue by andylauxugang2** [facundoolano/google-play-scraper#334]
* Operating System:Ubuntu lastest
* Node version:v10.16.3
* google-play-scraper version:

### Description: 
When I use the List api to test your official demo. That show me the error below:

### Example code:
```js
var gplay = require('google-play-scraper');

gplay.list({
    category: "FAMILY",
    num: 2
  })
  .then(console.log, console.log);

```

### Error message:

```
{ Error: App not found (404)
    at /home/sysop/nodejs/node_modules/google-play-scraper/lib/utils/request.js:44:19
    at process._tickCallback (internal/process/next_tick.js:68:7) status: 404 }
```

**Comment by dipbhi** [comment]
I am getting same error for using the given example in the help doc.

`
var gplay = require('google-play-scraper');

gplay.list({
    category: gplay.category.GAME_ACTION,
    collection: gplay.collection.TOP_FREE,
    num: 2
  })
  .then(console.log, console.log);
`

 It's likely that Google Play has changed the list page format.

My environment:
- OS: Windows 10 Pro
- Node.js: v10.15.0 
- google-play-scraper: 6.2.8

**Comment by vipinhelloindia** [comment]
I am getting the same error for 
var gplay = require('google-play-scraper');

gplay.reviews({appId: 'com.jeevansathi.android'})
  .then(console.log, console.log);

**Comment by facundoolano** [comment]
duplicate #333
