### ISSUE TITLE
Error "App Not Found (404) " for gplay.permissions and gplay.reviews

### ISSUE THREAD

**Issue by abubakaraziz** [facundoolano/google-play-scraper#335]
* Operating System:Ubuntu 18.04.2 LTS
* Node version:v10.15.3
* google-play-scraper version:6.2.8

### Description: 
I was using Gplay. reviews and Gplay.permissions and recently both of them are giving "App not found(404)" on all the requests.

### Example code for permissions:
var gplay = require('google-play-scraper');
 gplay.permissions({appId: 'word.cross.game.wordcrossy.free'})
 .then(console.log);
### Error message:

Error: App not found (404)  at /home/aziz/Network_Security_Project/googletest/node_modules/google-play-scraper/lib/utils/request.js:44:19 at process._tickCallback (internal/process/next_tick.js:68:7) // for permissions

### Example code for Reviews:
var gplay = require('google-play-scraper');
   gplay.reviews({
    appId: 'word.cross.game.wordcrossy.free',
    page: 0,
    sort: gplay.sort.RATING
  }).then(console.log, console.log);
~                                        
### Error message:
{ Error: App not found (404)
    at /home/aziz/Network_Security_Project/googletest/node_modules/google-play-scraper/lib/utils/request.js:44:19
    at process._tickCallback (internal/process/next_tick.js:68:7) status: 404 }

**Comment by MojtabaRazmi** [comment]
yes i have this problem also

**Comment by chekanskiy** [comment]
yes, i'm getting the same error
