### ISSUE TITLE
Some Collections Doesn't Work

### ISSUE THREAD

**Issue by vitaliy901** [facundoolano/google-play-scraper#345]
Some Collections Doesn't Work: 

- topselling_new_free
- topselling_new_paid
- movers_shakers

`gp.list({category: 'GAME', collection: 'topselling_new_paid'}).then(res => {
    console.log(res);
})`

`(node:13656) UnhandledPromiseRejectionWarning: Error: The collection is invalid for the given category or top apps` 

I checked it for every category, but nothing still works ...

**Comment by icarcal** [comment]
Hey @vitaliy901 
I checked for the top apps and these collections does not exist.
You can see it here:
https://play.google.com/store/apps/top/category/GAME?hl=en&gl=us

But, right now just for the GAME and FAMILY related categories, we have the following url (for the new collections):
https://play.google.com/store/apps/new/category/GAME?hl=en&gl=us

BUT, this does not work with other categories, for example:
https://play.google.com/store/apps/new/category/BUSINESS?hl=en&gl=us

Going to take a better look tonight and try to implement this into the `.list` method

**Comment by vitaliy901** [comment]
@icarcal thanks

**Comment by icarcal** [comment]
Hey @vitaliy901 the PR #350 is now openfor review and add support for the `new` collections.
Thanks.

**Comment by sayginburak** [comment]
also facing the same problem. what is the status of the MR? @icarcal 
if it will not be merged soon I will fork, merge and use the package from github. thanks.

**Comment by icarcal** [comment]
@sayginburak the #350  is still under review, you can check the whole discussion there.

**Comment by fotisskal** [comment]
@icarcal do we have any update on this?

I also seem to get the same error "The collection is invalid for the given category or top apps" for the combination
        "category": "events",
        "collection": "trending",
        "country": "id",
        "number": "20"
Is it related?

**Comment by icarcal** [comment]
@fotisskal #350 still under review, I have no update either.

I tested the version 7.0.4 with the data that you sent, and I was able to get the right response.
No error was raised.

What version are you using?

```js
const collection = gplay.collection.TRENDING;
gplay.list({
  collection,
  category: gplay.category.EVENTS,
  country: 'us',
  num: 100
}).then(console.log);
```
