### ISSUE TITLE
Can't parse more than 100 reviews with num: 200

### ISSUE THREAD

**Issue by ArtyCooL** [facundoolano/google-play-scraper#346]
* Operating System: Windows 10 x64
* Node version: v10.16.3
* google-play-scraper version: 7.0.1

### Description: 
Can't get more than 100 number of reviews with _num: 200_
Should I use any other loops to get more than 100?

### Example code:
```js
for( var i = 0; i < g.length; i++) {
	for( var j = 0; j < l.length; j++) {
		gplay.reviews({
			appId: g[i],
			lang: l[j],
			sort: gplay.sort.NEWEST,
			num: 200,
			throttle: 100
		})
		.then(console.log)
		.catch(console.log);
	};
}
```

### Error message: (not exactly an error, just this string at the end of reviews file)

```
  ... 100 more items ]
```

**Comment by icarcal** [comment]
Hey @ArtyCooL can you give one appId and lang, but I have checked this and we can get more than 100 reviews for any app / lang / country.

try [this](https://stackoverflow.com/questions/41669039/dumping-whole-array-console-log-and-console-dir-output-num-more-items) or [this](https://zaiste.net/nodejs_log_over_100_array_items/), it will dump the whole array to your `console.log`.
