### ISSUE TITLE
Getting app info by country

### ISSUE THREAD

**Issue by AdamAbrams** [facundoolano/google-play-scraper#35]
Is it possible to request app info specific to a country, not just language? Is it possible to understand what language(s) & countries the app  is for?

**Comment by facundoolano** [comment]
I don't think you can have country-specific app detail pages in google play, just language specific (at least so it was last time I checked). The app lists in the other hand, are country specific and you have the `country` code for that.

Regarding what languages/countries the app is for, is there any place in google play where you can see that? (remember this module simply grabs information already displayed in the google play pages)
