### ISSUE TITLE
Reviews - any way to get more than one page???

### ISSUE THREAD

**Issue by kani04** [facundoolano/google-play-scraper#352]
### Description: 
Previously there was pagenum in review scraping where it can fetch upto 112 pages, each page getting 40 reviews.
Now it fetches only 1 page of 100 reviews
Is it possible to get more than 100 reviews by providing page number now??

**Comment by icarcal** [comment]
Hey @kani04,
The `.reviews` method received a breaking change.
Right now, you can send at the `num` param to the method and it will fetch the desired quantity of reviews.

The docs have changed as well, and you can take a better look [here](https://github.com/facundoolano/google-play-scraper/blob/dev/README.md#reviews)

**Comment by kani04** [comment]
Thank you so much @icarcal .
I am able to scrape more reviews now. Thanks a lot!!!
