### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by yogiprsetya** [facundoolano/google-play-scraper#362]
* Operating System: Windows 10
* Node version: 12.4.0
* google-play-scraper version: 7.0.4

### Description: 
I have issues with Cross-Origin Request Blocked error.

### Example code:
```js
var gplay = require('google-play-scraper');
gplay.app({appId: 'com.oriente.finmas'}).then(console.log);
```

### Error message:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/store/apps/details?id=com.oriente.finmas&hl=en&gl=us. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)
```

### We have done
create `vue.config.js`
and write

```js
module.exports = {
    devServer: {
        proxy: 'https://play.google.com/',
    }
}
```
and error accured with message:
```Error: Error requesting Google Play:NetworkError when attempting to fetch resource.```

**Comment by facundoolano** [comment]
Are you running this library from the browser?

**Comment by yogiprsetya** [comment]
> 
> 
> Are you running this library from the browser?

yes, on localhost

**Comment by facundoolano** [comment]
This is not supposed to run from the browser. AFAIK you can't avoid that CORS issue, maybe someone else knows how to handle it.

**Comment by yurganov** [comment]
There is what you can do:

- Run local server on node.js on some port, write some handler that return you result of some function of this library, and access this handler from browser
- install some plugin for your browser that enable CORS

https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf
