### ISSUE TITLE
How to get the app by pagination

### ISSUE THREAD

**Issue by supersoftno1** [facundoolano/google-play-scraper#365]
Thanks for this project.
I want to know that how to get more apps?
What I want to ask is how to get the app by pagination.
i find the code like this:
----------------------------------------------
var gplay = require('google-play-scraper');
gplay.list({
    category: gplay.category.GAME_ACTION,
    collection: gplay.collection.TOP_FREE,
    num: 2
  })
  .then(console.log, console.log);
----------------------------------------------
But it did not have page parameter. how to get apps by pagination

**Comment by prostoVladislav** [comment]
in https://github.com/facundoolano/google-play-api/blob/master/lib/index.js line: 67

param "start" in version 6 works fine. in 7 version broken. 

/* App list */
router.get('/apps/', function (req, res, next) {
  function paginate (apps) {
    const num = parseInt(req.query.num || '60');
    const start = parseInt(req.query.start || '0');

    if (start - num >= 0) {
      req.query.start = start - num;
      apps.prev = buildUrl(req, '/apps/') + '?' + qs.stringify(req.query);
    }

    if (start + num <= 500) {
      req.query.start = start + num;
      apps.next = buildUrl(req, '/apps/') + '?' + qs.stringify(req.query);
    }

    return apps;
  }

  gplay.list(req.query)
    .then((apps) => apps.map(cleanUrls(req)))
    .then(toList).then(paginate)
    .then(res.json.bind(res))
    .catch(next);
});

**Comment by icarcal** [comment]
The scrapper was changed, you can now get all the apps by sending the `num` parameter.
You can see more information about the change [here](https://github.com/facundoolano/google-play-scraper/issues/333#issuecomment-529290209)
