### ISSUE TITLE
why i get this error. need help me. 

### ISSUE THREAD

**Issue by manishydv** [facundoolano/google-play-scraper#366]
var gplay = require('google-play-scraper');
gplay.app({ appId: 'com.zhiliaoapp.musically' }).then(function(data) {
        console.log("resolved");
        console.log(data);
    }).catch(function(err) {
        console.log("--catch--err-", err);
    });
==============
Resposne
==========
{ Error: App not found (404)
    at F:\myAPP\node_modules\google-play-scraper\lib\utils\request.js:44:19
    at process._tickCallback (internal/process/next_tick.js:68:7) status: 404 
}

**Comment by facundoolano** [comment]
This works fine on latest package, you're probably using an outdated one. This is the reason the template asks for the version.
