### ISSUE TITLE
Scraper always returning 199 apps

### ISSUE THREAD

**Issue by salmanee** [facundoolano/google-play-scraper#368]
Hi everyone, 

I used this tool few months ago to return the top 600 free apps from GooglePlay between Feb and April and it seemed to work fine then. Today, I tried running it again using:
`http://localhost:3000/api/apps/?start=100&num=300`

The results now contain only 199 apps and it seems to always return the first 199 apps regardless of the value passed in the "start" parameter. 

Has there been any recent changes in the store that resulted in this? I'd really appreciate your help :) 

Thanks,

**Comment by yurganov** [comment]
Yes, now you can only get 200 apps

This is because of changes on Google play side.

**Comment by icarcal** [comment]
@salmanee you can see a little bit more about the change pointed out by @yurganov [here](https://github.com/facundoolano/google-play-scraper/issues/333#issuecomment-529290209)

**Comment by kyzylmonteiro** [comment]
Is there a way to get around this?

**Comment by yurganov** [comment]
> Is there a way to get around this?

no
