### ISSUE TITLE
How to get all list of game, appid, and company

### ISSUE THREAD

**Issue by leahlee14083** [facundoolano/google-play-scraper#370]
Hi,

I am only allowed to retrieve 200 apps at one run. Is it possible to get a list of all apps in google play?

Can you tell me how and what approach should I do to retrieve all apps?

I really need all apps information. thanks.

**Comment by yurganov** [comment]
No, there is no way to do this.

**Comment by facundoolano** [comment]
Google doesn't expose any way to get all apps from the store. The closest you can get is to exhaust all lists and try all search combinations.
