### ISSUE TITLE
Cannot read property 'map' of null

### ISSUE THREAD

**Issue by yurganov** [facundoolano/google-play-scraper#373]
* Operating System: osx
* Node version: 12.4.0
* google-play-scraper version: google-play-scraper@7.1.0

### Description: 

Cannot fetch app details

### Example code:
```js
    let data = {
        appId : "com.companyname.Nospoon2.Android"
        country : "us",
        lang : "en",
    };
     gplay.app(data)
        .then(
            result => {
```

### Error message:

```
Cannot read property 'map' of null
```

**Comment by yurganov** [comment]
Seems to appears when app do not have screenshots

**Comment by yurganov** [comment]
Fixed in https://github.com/facundoolano/google-play-scraper/pull/374

**Comment by facundoolano** [comment]
merged
