### ISSUE TITLE
if quotes " are present in the app summary, they are not escaped

### ISSUE THREAD

**Issue by AndreiD** [facundoolano/google-play-scraper#382]
using latest version

I get them using **gplay.list({**

as you see below there are " in the summary, but they are not escaped, --> and they fuck up the json

~~~~
{ 
"title":"rif is fun golden platinum for Reddit",
"appId":"com.andrewshu.android.redditdonation",
"url":"https://play.google.com/store/apps/details?id=com.andrewshu.android.redditdonation",
"icon":"https://lh3.googleusercontent.com/fV9eF9MQ3NY-jqoTfDDH3k5o5ki81KKCh_eliwNNlBm0HNcZJ8qJsM4FCTwUrMy5YQ",
"developer":"TalkLittle",
"developerId":"TalkLittle",
"priceText":"$2.99",
"free":false,
"summary":"rif is fun golden platinum is ad-free. Formerly known as ""redditisfun"".",
"scoreText":"4.8",
"score":4.8344426
}
~~~~

**Comment by AndreiD** [comment]
a simple solution would be to base64 it

**Comment by AndreiD** [comment]
ugly fix:

```
      resp = resp.map(function(element) {
        element.summary = element.summary.replace(/"/g, '\\"');
        return element;
      });
```

**Comment by AndreiD** [comment]
so apparently also some strange characters appear from time to time so add this one too

element.summary = utf8.encode(element.summary);

**Comment by facundoolano** [comment]
There's no JSON involved here, if you give me an actual example of the code you are running I may understand what you are seeing.

**Comment by AndreiD** [comment]
what do you mean there's no JSON involved ? how do you call that structure that you get from gplay.list.. ?

well... get the top 50 free apps in NEWS_AND_MAGAZINES  ... you should see it returns the above app ...

**Comment by facundoolano** [comment]
This is a javascript API, that returns javascript objects, not JSON. JSON is a text format. What you may see that's messed up is the way your console represents the object (making it non valid JSON), but the values of the strings can't be invalid just because they contain quotes.

**Comment by AndreiD** [comment]
so if you're subtitle on github says that you like "clean apis", why you don't clean up this API ?

**Comment by facundoolano** [comment]
Accept the mystery.
