### ISSUE TITLE
Cannot read property '4' of null in gplay.app

### ISSUE THREAD

**Issue by gabidabet** [facundoolano/google-play-scraper#387]
* Operating System:Windows 10
* Node version: v10.15.0
* google-play-scraper version: last version

### Description: 
I get that error for somme app ids like :
-air.com.peppapig.paintbox "the exemple"
-com.netmarble.mherosgb
-com.wb.goog.injustice

### Example code:
```js
// Put code to reproduce the issue here
gplay
    .app({
        appId: "air.com.peppapig.paintbox"
    })
    .then(console.log, console.log);

### Error message:
Cannot read property '4' of null

**Comment by s-h-a-d-o-w** [comment]
Same for `.list`, e.g.:
```javascript
gplay
  .list({
    collection: gplay.collection.TOP_PAID_GAMES,
    fullDetail: true,
    num: 2,
    throttle: 10, // Max. 10 requests per second, avoid Google's limit
  })
  .then(console.log, console.log);
```

I suppose Google changed the structure of the site? :/

**Comment by icarcal** [comment]
@gabidabet and @s-h-a-d-o-w thanks for reporting.
Yes, gplay changed the structure.

I'll send a PR to fix this, ASAP

**Comment by facundoolano** [comment]
This should be fixed now.

**Comment by cgwyllie** [comment]
@facundoolano / @icarcal / @ We've been seeing this error coming up in our logs recently.

https://github.com/facundoolano/google-play-scraper/pull/409 was merged 2 days ago which seems to have changed the mappings for comments from `ds:18` to `ds:17`.

The `ds:18` field seemed to be part of the original fix for this issue in: https://github.com/facundoolano/google-play-scraper/pull/389

Has this regressed or is the store returning multiple different shapes for different app listings?

Any help here would be appreciated.

**Comment by icarcal** [comment]
@cgwyllie the mapping is correct for countries other than `us`

Specifically for `us`, google play is returning a string 'er' at the position `ds:17` and the correct comments at `ds:19`

Check the examples for the same app in different countries:
<details>
<summary>.app with multiple countries example</summary>

```javascript

gplay.app({
  appId: 'com.facebook.katana'
}).then(console.log)

gplay.app({
  appId: 'com.facebook.katana',
  country: 'us',
  lang: 'en'
}).then(console.log)

gplay.app({
  appId: 'com.facebook.katana',
  country: 'br',
  lang: 'pt-BR'
}).then(console.log)

gplay.app({
  appId: 'com.facebook.katana',
  country: 'es',
  lang: 'es-es'
}).then(console.log)
```

</details>

Unfortunatelly the tests for this lib do not check if the comments section have any comment.

I'll fix this and send another PR, for the tests and the mapping for `us`

**Comment by icarcal** [comment]
@cgwyllie #412 is now up for review

**Comment by cgwyllie** [comment]
@icarcal Fantastic, thank you! Makes sense with the different regions, we hadn't considered that as a contributing factor.

**Comment by s-h-a-d-o-w** [comment]
Just wanted to note that this doesn't affect just using certain languages but also e.g. the following:
```
await scraper.list({
        category,
        collection: scraper.collection.TOP_PAID,
        fullDetail: true,
        num: NUM_GAMES,
        throttle: 5,
      })
```

I tried using @icarcal's fork directly as a dependency but still get that error.

**Comment by icarcal** [comment]
@s-h-a-d-o-w thanks for reporting.
Just to be clear, you meant the comments not being parsed correctly, right?
The same as @cgwyllie reported, but for the `.list`method?

Gonna take a better at this later today

**Comment by s-h-a-d-o-w** [comment]
I don't know the source of the problem (just a user of this library, not a contributor :) ). This is the output:
```
[1] TypeError: Cannot read property '4' of null
[1]     at prop (REDACTED\node_modules\ramda\dist\ramda.js:3399:19)
[1]     at REDACTED\node_modules\ramda\dist\ramda.js:466:28
[1]     at f1 (REDACTED\node_modules\ramda\dist\ramda.js:446:27)
[1]     at _map (REDACTED\node_modules\ramda\dist\ramda.js:262:27)
[1]     at map (REDACTED\node_modules\ramda\dist\ramda.js:5959:20)
```

**Comment by icarcal** [comment]
@s-h-a-d-o-w can you provide the category used in this example?

**Comment by s-h-a-d-o-w** [comment]
@icarcal I scrape all games categories. Just tried it with `GAME_ACTION` and `GAME_ADVENTURE` and both throw this error.

**Comment by icarcal** [comment]
@s-h-a-d-o-w #412 was merged today, be sure to update the module to the version 8+

**Comment by cgwyllie** [comment]
@icarcal glad to see this is this understood & patched, thanks to everyone who's put in time here. Are there any release notes / changelog for the major version change (if it is indeed semver 'breaking')? Thanks!

**Comment by s-h-a-d-o-w** [comment]
@icarcal Sweet, now my site gets updates again! I'm glad I didn't put a way for people to get in touch with me on there. ;)

Anyway - great work, thanks a lot!
