### ISSUE TITLE
Is there a way to get all the apps in Google Play?

### ISSUE THREAD

**Issue by hntee** [facundoolano/google-play-scraper#397]
Hi, I'd like to crawl all the apps with category and description. 

I tried something like the following code in order to get all the apps in a given category,
```
gplay.list({
    category: gplay.category.EDUCATION,
})
```
but it seems that the maximum result size is 200.

Is there a way to get all of the apps in any category?

**Comment by AdityaAnand1** [comment]
@hntee Were you able to find a solution for this?

**Comment by hntee** [comment]
> @hntee Were you able to find a solution for this?

no... so I just use the apps' package names that I have to search for them.

**Comment by AdityaAnand1** [comment]
Where do you get the list of packages? By searching keywords?

**Comment by icarcal** [comment]
Right now, there is no way of doing this.
@facundoolano answered that [here](https://github.com/facundoolano/google-play-scraper/issues/370#issuecomment-555034805).

> Google doesn't expose any way to get all apps from the store. The closest you can get is to exhaust all lists and try all search combinations.

**Comment by adtimizer** [comment]
Hi 
My Company provide such lists if you are interested.
Feel free to contact me at oren@adtimizer.co
