### ISSUE TITLE
From 100 appIds, one consistently returns no result

### ISSUE THREAD

**Issue by Giszmo** [facundoolano/google-play-scraper#400]
I'm monitoring about 100 apps and it worked great until a week ago or so when one app started returning `Error: App not found (404)` yet when checking with a browser, [the app is there just fine](https://play.google.com/store/apps/details?id=tech.insense.sensewalet). What could be the reason for this discrepancy?

Edit: Just to confirm, 27 days later this one appId is still the only one not working.

**Comment by Primokorn** [comment]
I couldn't give a number but I do have issues too for 2 weeks.

I'm stuck on a (random?) package. Example:
![image](https://user-images.githubusercontent.com/5938828/81416335-dfb45900-9149-11ea-9513-ad07166a45e4.png)

I have to stop the process. Several downloaded icons have a size of 0 Kb (I can't open them).

**Comment by Primokorn** [comment]
It happened again with only 8 packages:
![image](https://user-images.githubusercontent.com/5938828/81416918-b5af6680-914a-11ea-86f8-d60e69c53c13.png)

**Comment by yurganov** [comment]
shit happens

>>connect ETIMEDOUT 216.58.215.46:443

that's because of your ISP

**Comment by Primokorn** [comment]
> shit happens
> 
> > > connect ETIMEDOUT 216.58.215.46:443
> 
> that's because of your ISP
Same issue with the CLI client of ProtonVPN. I was hoping it could help.

**Comment by Giszmo** [comment]
@Primokorn's issue is not mine. My issue is not random at all. My issue is with one app consistently since more than a month and I would appreciate if somebody could check if using google-play-scraper works for them with the appId tech.insense.sensewalet.

**Comment by icarcal** [comment]
@Giszmo can you provide the language and country that you are using?
By default, this lib uses `us` as country and `en` as lang.

The `.app` method adds two parameters to the link that you provide: `hl` and `gl`.

So, if I call the method like this:
```js
gplay.app({
  appId: 'tech.insense.sensewalet'
}).then(console.log);
```
The real url being called is
`https://play.google.com/store/apps/details?id=tech.insense.sensewalet&hl=en&gl=us`

Which give you the same error: `Error: App not found (404)`

BUT, if I call with a different country and lang, I receive the data consistently:
```js
gplay.app({
  lang: 'pt',
  country: 'br',
  appId: 'tech.insense.sensewalet'
}).then(console.log);
```

My guess is that this is happening 'cause this app is available only in some countries.

**Comment by Giszmo** [comment]
I'm in Chile. So they de-published the app for the US market. Makes sense. Many Bitcoin business avoid the US. Thanks for clarifying.

**Comment by Primokorn** [comment]
For the records: my issue is solved. I no longer have a timeout. Maybe a temporary issue from my ISP as suggested.
Glad for you @Giszmo :)

**Comment by Primokorn** [comment]
@icarcal Can I completely remove the language `&hl=en&gl=us` from the url?
We can access to the url without these 2 parameters: `https://play.google.com/store/apps/details?id=tech.insense.sensewalet`

Thanks!

**Comment by icarcal** [comment]
@Primokorn right now there is no way of doing that, and the docs explicitly says what lang and country it defaults to.

I don’t see the point of removing those parameters, since this allow us to know exactly from what country and lang we are getting the app data.

**Comment by Primokorn** [comment]
@icarcal Because we miss apps which are not available in English. I can't do a "trial and error" language operation for each "app not found".
I only this tool to download icons so I don't need to know the country.

**Comment by facundoolano** [comment]
That default is intentional and I prefer it to omitting language by default which would produce inconsistent behavior of the same piece of code on different locations/setups.

But I would accept a PR with an option to explicitly tell you want to omit the country, e.g. if you pass {"country": false} then omit the option and use the "machine default". But this would need to be respected in all method calls.

**Comment by Primokorn** [comment]
@facundoolano Thanks for your understanding. Unfortunately I have no dev skill to suggest a PR.
I work on Android icon packs, I'm more a designer than a developer. Thanks anyway.

**Comment by icarcal** [comment]
@Primokorn @facundoolano I’ll move this discussion to another issue, as a suggested feature so we can have a better history on this, ok?
