### ISSUE TITLE
Now Search method does not work

### ISSUE THREAD

**Issue by bumsun** [facundoolano/google-play-scraper#410]
* Operating System: Ubuntu
* Node version: v8.17.0
* google-play-scraper version: 7.1.2

Now Search method does not work. 
Always returns an empty response.

```js
gplay.search({
                term: req.body.query,
                num:250,
            })
            .then(function(info) {
           //info == [] 
```

**Comment by adtimizer** [comment]
it seems like google has changed their mapping. also **app** doesn't work. will update if i'll have a solution later today

**Comment by icarcal** [comment]
@adtimizer `.app` method was solved by #409 
I tested the `.search` method with the contents of the PR and it is working fine.
Can you give it a try @bumsun ?
Or provide an app id that is not working for you?

**Comment by adtimizer** [comment]
@icarcal thanks for pointing it out. works for me now.

**Comment by facundoolano** [comment]
Closing then.
