### ISSUE TITLE
Pagination of reviews

### ISSUE THREAD

**Issue by jamesthecat7** [facundoolano/google-play-scraper#411]
I notice that pagenumber has been been removed when querying app reviews. 

How does one page through app reviews

**Comment by icarcal** [comment]
@jamesthecat7 I sent a PR to bring back the reviews pagination, check #414 

I the mean time and with the lib version 7+, you can send the `num` parameter for how many reviews you want.
The lib will automatically fetch the desired number of reviews for you.

**Comment by jamesthecat7** [comment]
I've used your fork and it works perfectly. Thank you icarcal.
