### ISSUE TITLE
What does max and min installs means ? How is your maxInstalls different than actual installs on android app ( play console ) 

### ISSUE THREAD

**Issue by usman10scorpio** [facundoolano/google-play-scraper#413]
Hi

Thanks for this fabulous package, I was going through the docs and i was unable to find what does max and min installs means?
 
Does maxInstalls mean total no of downloads ?

Then what does minInstalls mean ?

How are you calculating maxInstalls ? I checked my installs on android play conole and then I checked the package maxInstalls, they are different. Why ?

![Screenshot_2020-06-23-16-38-26-876_com google android apps playconsole22](https://user-images.githubusercontent.com/12570317/85401482-824a5f00-b573-11ea-8eb4-d51769784fba.jpg)
![image](https://user-images.githubusercontent.com/12570317/85401585-b3c32a80-b573-11ea-919f-ee7adc9d640f.png)

Please shed some light.

**Comment by facundoolano** [comment]
When the package was first implemented, google play used to show install like this in the site: `Installs 1,000 - 5,000`. The number of installs wasn't exact, it meant it was somehwere in that range.

Then they changed the UI, and started reporting like `installs 1,000+`. The ranges are the same, but they only report the lower limit. We kept the entire range for backward compatibility (and because it was useful information), at least for a while. I think at some point the field was lost, and I'm not sure what's the situation right now.

**Comment by usman10scorpio** [comment]
so should I consider maxInstalls or not ?

**Comment by usman10scorpio** [comment]
Why the maxInstalls count and android play console stats are not matching ?

**Comment by icarcal** [comment]
As @facundoolano said the initial purpose of the maxInstalls is different from what is reflecting now.

`minInstalls` reflects the `1,000,000,000+` installs at google play as you can see in the picture above:
<img width="147" alt="Screen Shot 2020-06-23 at 10 51 53" src="https://user-images.githubusercontent.com/11530480/85412080-94120f00-b53f-11ea-8a56-98206b2f171f.png">

`maxinstalls` field was removed, but the last time that I needed to change the mappings, I noticed another number that we could use at the `ds:6` field, that google play itself, allow us to read, for example:
```javascript
["1,000,000,000+",1000000000,2951198504,"1B+"]
```

The number 291198504 is not the total number of installs, it isn't accurate, and does not reflect the number of installs at google console.
Before adding this field I made the same validation, but figured out that is in fact a better number than 1000000000 itself, and close to what google console show us.
So I added it anyway.

You have two options:

- Ignore this number entirely and stick with `minInstalls`
- use `maxInstalls` as an approximately number of installs for whatever purpose you want
