### ISSUE TITLE
The collection topselling_new_free is invalid for the given category, top apps or new apps

### ISSUE THREAD

**Issue by honeylucky** [facundoolano/google-play-scraper#416]
when I use code:

gplay.list({
    category: gplay.category.TOOLS,
    collection: gplay.collection.NEW_FREE},
    num: 300
}).then(function (item) {
    console.log(JSON.stringify(item));
});

give me error:
The collection topselling_new_free is invalid for the given category, top apps or new apps

**Comment by prabhatCH** [comment]
I get `Error: The collection top_selling_free have no clusters`. Probably the 2 are related!

**Comment by icarcal** [comment]
@honeylucky   google seems to be removed the new apps per category url, for example
https://play.google.com/store/apps/new/category/AUTO_AND_VEHICLES
or
https://play.google.com/store/apps/new/category/LIFESTYLE

I couldn't find another url where we can fetch this data.
If anyone figure the urls, I'll be glad to implement.

Going to take a better look into this.



@prabhatCH Can you please provide a code sample?

**Comment by MobiOptApp** [comment]
Same Problem!!

**Comment by facundoolano** [comment]
closing as duplicate of #488
