### ISSUE TITLE
From 165 appIds, one consistently returns no result

### ISSUE THREAD

**Issue by Giszmo** [facundoolano/google-play-scraper#422]
Just as with !400, again I have one app that consistently returns `Error: App not found (404)`.

As with the other case where `&hl=en&gl=us` was the issue, I tried it out but all links look good in the browser.

I had changed my script to

```
      gplay.app({
          appId: appId,
          lang: 'en',
          country: 'cl',
          throttle: 5}).then(function(app){
```

as less apps are unavailable in Chile than in the US. Now I get the issue with the appId `com.satsapp` but https://play.google.com/store/apps/details?id=com.satsapp&hl=en&gl=cl and https://play.google.com/store/apps/details?id=com.satsapp&hl=en&gl=us open just fine in the browser.

I think [this code](https://github.com/facundoolano/google-play-scraper/blob/041c276375bc534340512eb6f7892a9ecd13b9e2/lib/app.js#L25) is where the actual query url is? There should not be more options than id, hl and gl, right? So what's wrong?

**Comment by icarcal** [comment]
@Giszmo 

Both urls are returning 404 to me:
![Screen Shot 2020-07-23 at 04 41 05](https://user-images.githubusercontent.com/11530480/88262641-f70dd780-cc9e-11ea-9460-f0efcfc009ef.png)

![Screen Shot 2020-07-23 at 04 40 59](https://user-images.githubusercontent.com/11530480/88262647-fa08c800-cc9e-11ea-9411-b959448c3f11.png)

**Comment by Giszmo** [comment]
Ok, I see ... `wget $url` gives me a 404 for both urls, too but in the browser both work:

en_CL:

![Screenshot from 2020-07-23 11-49-30](https://user-images.githubusercontent.com/96378/88308105-a6b46b00-ccda-11ea-9d60-4067b2e64c6a.png)

en_US:

![Screenshot from 2020-07-23 11-49-47](https://user-images.githubusercontent.com/96378/88308125-a9af5b80-ccda-11ea-8dcd-a9264db301b1.png)

**Comment by icarcal** [comment]
@Giszmo, Do you have this app in your account?
This app is no longer available at the store

**Comment by Giszmo** [comment]
OMG! You are right! Google lets you install apps that were de-published forever and that's how it was still available in the browser but not in a private window! Thanks for figuring it out!
