### ISSUE TITLE
I have some errors, but I don't know how to solve it

### ISSUE THREAD

**Issue by AClines** [facundoolano/google-play-scraper#427]
my test.js

var gplay = require('google-play-scraper');
gplay.app({appId: 'com.google.android.apps.translate'})
  .then(console.log, console.log);

And i get some errors

Error: Error requesting Google Play:connect ETIMEDOUT 216.58.200.46:443
    at E:\GooglePlayData\google-play-scraper\node_modules\google-play-scraper\lib\utils\request.js:44:19    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: undefined
}

I don't know how to solve it, can anyone help me

**Comment by GLBBBB** [comment]
你解决了这个问题吗

**Comment by Zexiong-Xiang** [comment]
你解决问题了吗
