### ISSUE TITLE
Unexpected token , in JSON at position 138

### ISSUE THREAD

**Issue by berrybar** [facundoolano/google-play-scraper#429]
* Operating System: windows 10
* Node version: v10.16.0
* google-play-scraper version: 7.1.1, 7.1.2

### Description: 
Ranking collection is not possible with the same error as the title.

How can i solve this problem???

### Error message:

SyntaxError: Unexpected token , in JSON at position 138
    at JSON.parse (<anonymous>)
    at matches.reduce (node_modules\google-play-scraper\lib\utils\scriptData.js:48:26)
    at Array.reduce (<anonymous>)
    at parse (node_modules\google-play-scraper\lib\utils\scriptData.js:42:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by icarcal** [comment]
@berrybar can you provide a code sample?

**Comment by berrybar** [comment]
var G = require('./node_modules/google-play-scraper/index.js');
var pool = require('./lib/db.js');
var fs = require('fs');
const retry = require('async-retry')

async function rankGetStart(){
    function savetoDB(pool, tempArray){
        pool.getConnection(function(err, con) {
            if (err) throw err;
            var sql = "INSERT IGNORE INTO google_rank (title, appId, url, icon, developer, developerId, priceText, free, summary, scoreText, score, rank, check_date, check_time, type) VALUES ?";
            var values = tempArray;
            con.query(sql, [[values]], function(err){
                if (err) {
                    var now = new Date();
                    console.log(now + ' ' + err + ' an error occuerd!');
                    throw err;
                }
                con.release();
            });
        });
    }
    async function getList(type){
        if(type==1){
            collection = G.collection.GROSSING;
        } else if(type==2){
            collection = G.collection.TOP_FREE;
        } else if(type==3){
            collection = G.collection.TOP_PAID;
        } else if(type==4){
            collection = G.collection.NEW_FREE;
        } else if(type==5){
            collection = G.collection.NEW_PAID;
        } else if(type==6){
            collection = G.collection.TRENDING;
        }
        await G.list({
            category: G.category.GAME,
            collection: collection,
            num: 200,
            lang: 'ko',
            country: 'kr',
            throttle: 10
        }).then(function(list){
            i = 1
            const now = new Date()
            list.forEach((x) => {
                x['rank'] = i
                x['check_date'] = now
                x['check_time'] = now.getHours()
                x['type'] = type
                array.push(Object.values(x))
                savetoDB(pool,Object.values(x))
                i++;
            });   
        }).catch(console.log)
    }

    for(let type=1;type<7;type++){        
        await getList(type)
        await console.log('loop '+type+' done')
    }
    process.exit();
}
let i = 1
let array = []
rankGetStart();

**Comment by icarcal** [comment]
Google changed the way that the data is returned to the store.
Working on a fix.

Apparently the mappings have changed too

**Comment by berrybar** [comment]
Thanks for your answer.
We are waiting for a solution. :)

**Comment by erishig** [comment]
Hi guys, 

I encountered this problem too and have looked at the changed data.

I have made following 2 changes to the scriptData.js:

1)   ```
  // const valueRegex = /data:([\s\S]*?)}\);<\//;
  // changed on 26th Aug
  const valueRegex = /data:([\s\S]*?), sideChannel: {}}\);<\//;  
```

2) Add a try catch block 
```
      try {
        const key = keyMatch[1];
        const value = JSON.parse(valueMatch[1]);

        return R.assoc(key, value, accum);
      }
      catch (e) {
      }
```

This has helped me get going. repo owners/contributors may look at it for detailed fix.

**Comment by berrybar** [comment]
@erishig  You are a genius!

**Comment by icarcal** [comment]
#430 is now up for review
