### ISSUE TITLE
SyntaxError: Unexpected token , in JSON at position 6772

### ISSUE THREAD

**Issue by nan1211** [facundoolano/google-play-scraper#431]
* Operating System:ubuntu18
* Node version:12.18.1
* google-play-scraper version:8.0.1

### Description: 
yntaxError: Unexpected token , in JSON at position 6772
    at JSON.parse (<anonymous>)
    at /google_play/node/node_modules/google-play-scraper/lib/utils/scriptData.js:78:26
    at Array.reduce (<anonymous>)
    at parse (/google_play/node/node_modules/google-play-scraper/lib/utils/scriptData.js:72:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Example code:
```js
var gplay = require('google-play-scraper');
gplay.app({appId: 'com.google.android.apps.translate',lang:'id',country:'id'}).then(console.log, console.log);
```

### Error message:
/google_play/node/node_modules/google-play-scraper/lib/utils/scriptData.js:78:26

**Comment by facundoolano** [comment]
duplicated

**Comment by nan1211** [comment]
ok.thanks
