### ISSUE TITLE
UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by igorfltv** [facundoolano/google-play-scraper#432]
* Operating System: Windows
* Node version: 14.3.0
* google-play-scraper version: 6.2.3

### Description: 
**Hitting /app** method

Result in console:
Getting (node:20268) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token , in JSON at position 6680
node_modules\google-play-scraper\lib\utils\scriptData.js:42:18

Log says issue comes with JSON.parse function. 
### Example code:
```js
var gplay = require('google-play-scraper');

gplay.app({appId: 'ru.myspar'})
  .then(console.log, console.log);
```

### Error message:

```
Put error message here
SyntaxError: Unexpected token , in JSON at position 6038
    at JSON.parse (<anonymous>)
    at C:\Users\igora\Git\Reviews\node_modules\google-play-scraper\lib\utils\scriptData.js:48:26
    at Array.reduce (<anonymous>)
    at parse (C:\Users\igora\Git\Reviews\node_modules\google-play-scraper\lib\utils\scriptData.js:42:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by facundoolano** [comment]
duplicated #428
