### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by alrl2** [facundoolano/google-play-scraper#435]
* Operating System: MacOS 10.14.3
* Node version: 12.14.1
* google-play-scraper version: v8.0.2 

### Description: 
Hello! On August 26, we discovered a problem with the scraper.
Perhaps, the structure of the google play store has changed.

### Example code:
```js
gplay.app({ 
  appId, // any gplay app page
  country: 'eu' 
});
```

### Error message:

```
Error: Cannot read property 'replace' of undefined
```

**Comment by Bukse** [comment]
**WARNING BAD WAY :D THIS ISN'T BEST SOLUTION**

Hi. Same problem, but with reviews module. Also I have no time to wait for a fix, so I used a temporary solution:

1. Go to path _node_modules/google-play-scraper/lib/requesters/reviewsMappedRequests.js_
2. Next step find:
```
function formatReviewsResponse ({
  reviews,
  num,
  token = null
}) {
  const reviewsToResponse = (reviews.length >= num)
    ? reviews.slice(0, num)
    : reviews;

  return {
    data: reviewsToResponse,
    nextPaginationToken: token
  };
}
```

3. Wrap it to try/catch:
```
function formatReviewsResponse ({
  reviews,
  num,
  token = null
}) {
  try {
    const reviewsToResponse = (reviews.length >= num)
      ? reviews.slice(0, num)
      : reviews;

    return {
      data: reviewsToResponse,
      nextPaginationToken: token
    };
  } catch (e) {

  }
}
```

Maybe you can fix it with my example.
In my case it's happened because there are no reviews for some language.

**WARNING BAD WAY :D**

**Comment by marxsk** [comment]
@Bukse 
I have added one more check before checking the length of reviews
```
let reviewsToResponse;

if (typeof reviews === 'undefined') {
  reviewsToResponse = []
} else if (reviews.length >= num) {
...
```

**Comment by KaKi87** [comment]
> Cannot read property 'replace' of undefined
- _at `extractFields` @ [google-play-scraper/lib/utils/scriptData.js](https://unpkg.com/google-play-scraper/lib/utils/scriptData.js):​40:14_
- _at `Object.f2 [as map]` @ [ramda/dist/ramda.js](https://unpkg.com/ramda/dist/ramda.js):​473:22_
- _at `null.<anonymous>` @ [ramda/dist/ramda.js](https://unpkg.com/ramda/dist/ramda.js):​586:23_
- _at `map` @ [ramda/dist/ramda.js](https://unpkg.com/ramda/dist/ramda.js):​5954:20_
- _at `_reduce` @ [ramda/dist/ramda.js](https://unpkg.com/ramda/dist/ramda.js):​5167:24_
- _at `_arrayReduce` @ [ramda/dist/ramda.js](https://unpkg.com/ramda/dist/ramda.js):​5137:46_
- _at `XWrap.@@transducer/step` @ [ramda/dist/ramda.js](https://unpkg.com/ramda/dist/ramda.js):​392:25_
- _at `XWrap.f` @ [ramda/dist/ramda.js](https://unpkg.com/ramda/dist/ramda.js):​5955:28_
- _at `null.<anonymous>` @ [google-play-scraper/lib/utils/scriptData.js](https://unpkg.com/google-play-scraper/lib/utils/scriptData.js):​52:19_
- _at `Object.descriptionText [as fun]` @ [google-play-scraper/lib/mappers/details.js](https://unpkg.com/google-play-scraper/lib/mappers/details.js):​104:51_

---

- [The original Sentry report](https://git.kaki87.net/KaKi87/KPlaySearch/issues/5#issuecomment-329)
- [The source code](https://git.kaki87.net/KaKi87/KPlaySearch/src/branch/master/index.js)

Thanks.

**Comment by dasheck0** [comment]
Is this still open? Ran into the same issue this morning.

**Comment by 1004885516** [comment]
How can this problem be solved？

**Comment by 1004885516** [comment]
> * 操作系统：MacOS 10.14.3
> * 节点版本：12.14.1
> * google-play-scraper 版本：v8.0.2
> 
> ### 描述：
> 你好！8 月 26 日，我们发现了刮板的问题。 或许，google play 商店的结构发生了变化。
> 
> ### 示例代码：
> ```js
> 播放。app ( {  
>   appId ,  // 任何 gplay 应用页面
>   国家: 'eu'  
> } ) ;
> ```
> 
> ### 错误信息：
> ```
> Error: Cannot read property 'replace' of undefined
> ```

**Comment by 1004885516** [comment]
> * 操作系统：MacOS 10.14.3
> * 节点版本：12.14.1
> * google-play-scraper 版本：v8.0.2
> 
> ### 描述：
> 你好！8 月 26 日，我们发现了刮板的问题。 或许，google play 商店的结构发生了变化。
> 
> ### 示例代码：
> ```js
> 播放。app ( {  
>   appId ,  // 任何 gplay 应用页面
>   国家: 'eu'  
> } ) ;
> ```
> 
> ### 错误信息：
> ```
> Error: Cannot read property 'replace' of undefined
> ```

Has this problem been solved？
