### ISSUE TITLE
Will my IP be blocked if I send requests for data too quickly/often?

### ISSUE THREAD

**Issue by EasyGitHub99** [facundoolano/google-play-scraper#44]
Do I need to scrape slowly when using this? I'd hate to have my IP banned from Google Play. Is 5 seconds between each request good enough?

**Comment by facundoolano** [comment]
In my experience, there's a throttling limit so if you do a big amount of requests you start getting 503 responses from google. Once you hit that limit you have to wait to continue making requests (don't remember how much, but I think it was minutes).

I don't know about being banned, but if you manage to avoid that throttling limit I guess you'll be fine. A 5 seconds delay is way too much. Just make some tests and if you don't see any error response I guess you'll be fine.

**Comment by facundoolano** [comment]
FYI added a throttling option to avoid these issues: https://github.com/facundoolano/google-play-scraper#throttling
