### ISSUE TITLE
Full Review not captured

### ISSUE THREAD

**Issue by ayukidawe** [facundoolano/google-play-scraper#442]
* Operating System: All
* Node version:6.14.4
* google-play-scraper version:8.0.2

### Description: 
When getting all Reviews , some of the longer reviews are returned with " ... Full Review"
This means that the scraper was not able to expand the "Full Review" link and get the full text of the review

Ex:
"Very Good App..I apriceate ...You are providing best solution to our businessmans ..It will.surely help to free his minds and time saving App. 1 suggestions is that why always show the Contact list on the main screen. Please hide with an any icon for more space on the main screen. It will be also he...Full Review""

### Example code:
```js
This is reproducible for any app, which has longer review
```

**Comment by icarcal** [comment]
@ayukidawe can you give us a code example?

**Comment by facundoolano** [comment]
no example, closing.
