### ISSUE TITLE
Sorting does not seem to work with NEWEST

### ISSUE THREAD

**Issue by Eightyplus** [facundoolano/google-play-scraper#443]
* Operating System: OSX 10.15.7
* Node version: v12.7.0
* google-play-scraper version: 8.0.2

### Description: 
I'm trying to get the newest google play reviews. However, this does not seem to work.

### Example code:
```js
var gplay = require('./index');

gplay.reviews({
  appId: 'com.strimmobile',
  num: 2
})
  .then(console.log, console.log);
```

I know we have newer reviews. But it seem to highlight some reviews in August. 

![Screenshot 2020-10-27 at 12 34 00](https://user-images.githubusercontent.com/15194982/97296621-31b07e80-1851-11eb-8bc9-dd4e1f75e55b.png)

### Error message:
none

**Comment by icarcal** [comment]
@Eightyplus the newest reviews at gplay **en** language is the same that you are receiving as return
https://play.google.com/store/apps/details?id=com.strimmobile&hl=en&gl=US&showAllReviews=true

This newer reviews that you have (probably at your console) are for the what language?

**Comment by Eightyplus** [comment]
@icarcal - ah, I added `lang: "no"` and now I get the newest reviews. But still sorted like Google would present 'em. 

Ah, but still much better than using default language. Thanks!
