### ISSUE TITLE
[Feature request] Worldwide search

### ISSUE THREAD

**Issue by KaKi87** [facundoolano/google-play-scraper#444]
As the documentation says, the `search` method uses `us` as default value for the `country` parameter.
Would it be possible to remove the filter and search all apps even if they're not available in some countries ?
Thanks.

**Comment by facundoolano** [comment]
That parameter is not a filter, rather it tells google what country the request is coming from. In the browser, if you omit the parameter it's the same to use whatever your local country is. You always make the request from some country, the default us just guarantees that the code works the same for everyone.
