### ISSUE TITLE
Get top free or paid for a specific date?

### ISSUE THREAD

**Issue by Dakshesh10** [facundoolano/google-play-scraper#445]
Can I get charts for a specific category for a specific date? I can see all the sub categories and everything but not sure which day is the data getting fetched belongs to. Can I get top charts from say 6 months ago? Can anyone point me to a scrapper that can do that?

**Comment by facundoolano** [comment]
The scraper makes live requests to Google play, so you get whatever data is currently in the page and, no, there's no way to query for old data.
