### ISSUE TITLE
[FR] Add cloud save filter for searching

### ISSUE THREAD

**Issue by K0media** [facundoolano/google-play-scraper#446]
Cloud saving is an important feature for certain apps and games.

I'd like you to check the possibility on adding this filter as an option to the search engine.

Here's a screenshot of what I'm talking about:

![image](https://user-images.githubusercontent.com/22375465/98566159-34699580-228d-11eb-926e-49ec2bc8c095.png)

If further help is needed, I'll be glad to help.

PS: Currently it is possible to filter by cloud save feature on Google Play Games app. Not sure on Play Store itself.

**Comment by icarcal** [comment]
I looked at the google play page for this [game](https://play.google.com/store/apps/details?id=com.halfbrick.dantheman&hl=pt_BR&gl=US) and found all the info that you mentioned.

We can get all the features like this:
```js
  features: [
    {
      title: 'Uses Google Play Games',
      description: 'For automatic sign-in, leaderboards, achievements, and more.'
    },
    {
      title: 'Achievements',
      description: 'Grants you achievements for completing goals and skill-based challenges.'
    },
    {
      title: 'Leaderboards',
      description: 'Compare your scores with your friends and other Play Games players.'
    },
    {
      title: 'Saved Games',
      description: 'Save your progress and pick up where you left off on any device.'
    }
  ],
```

I'll send a PR with these fields by tomorrow.

**Comment by icarcal** [comment]
@K0media #457 is now up for review
