### ISSUE TITLE
Scraping only showing 200 apps max?

### ISSUE THREAD

**Issue by juantellobop** [facundoolano/google-play-scraper#448]
ENG: I'm looking for a scraping on FINANCE category on Google Play Store, but it only shows me 200 items.

My code is:
`var gplay = require('google-play-scraper');

gplay.list({
    category: gplay.category.FINANCE,
    lang: 'es',
    country: 'ar',
    num: '900',
    collection: gplay.collection.TOP_FREE,
  })
.then(res => {
    console.log('total ' + res.length + ' items')
    for (let i = 0; i < res.length; i++) {
      console.log(res[i])
    }
  }).catch(err => console.error(err));`

How can if fix this?

**Comment by icarcal** [comment]
This is a limit of google play, you can check a little bit more of the discussion, [here](https://github.com/facundoolano/google-play-scraper/issues/333#issuecomment-529290209)
