### ISSUE TITLE
Possible to extend max on gplay.search num 250?

### ISSUE THREAD

**Issue by danpostmail92** [facundoolano/google-play-scraper#451]
Hi There,

Is it possible to extend the max number of retrieves on search.list num? MAX is 250. Hoping to extend it if possible?

Thanks

**Comment by icarcal** [comment]
This is a limit of google play, you can check a little bit more of the discussion, [here](https://github.com/facundoolano/google-play-scraper/issues/333#issuecomment-529290209)
