### ISSUE TITLE
Unable to use in Angular Project

### ISSUE THREAD

**Issue by DATL4G** [facundoolano/google-play-scraper#454]
* Operating System: Pop!_OS 20.10
* Node version: 12.19.0
* Angular: 11.1.0
* Angular CLI: 11.1.1
* Ivy-Workspace: Yes
* google-play-scraper version: 8.0.2
* IDE: WebStrom 2020.3.1

### Description: 
I use Angular and tried using this library. (Typescript)
Before adding this lib: **works fine**
After adding this lib: **works fine**
After importing this lib: **works fine**
After using this lib: **compiler error**
I just added a simple call.

### Example code:
I tried several methods
```typescript
import { developer } from 'google-play-scraper';

developer({ devId: 'DatLag' }).then((data) => console.log(data));
```
```typescript
import * as gplay from 'google-play-scraper';

gplay.developer({ devId: 'DatLag' }).then((data) => console.log(data));
```
```typescript
const gplay = require('google-play-scraper');

gplay.developer({ devId: 'DatLag' }).then((data) => console.log(data));
```

### Testing
I think a plain Angular Project using this library should result in the same

### Error message:

<details>
<summary>Complete Error Message</summary>

Error: ./node_modules/aws-sign2/index.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/aws-sign2'

Error: ./node_modules/aws4/aws4.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/aws4'

Error: ./node_modules/ecc-jsbn/index.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/ecc-jsbn'

Error: ./node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/http-signature/lib'

Error: ./node_modules/http-signature/lib/verify.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/http-signature/lib'

Error: ./node_modules/oauth-sign/index.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/oauth-sign'

Error: ./node_modules/request/lib/helpers.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/request/lib'

Error: ./node_modules/request/lib/oauth.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/request/lib'

Error: ./node_modules/request/lib/hawk.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/request/lib'

Error: ./node_modules/sshpk/lib/key.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib'

Error: ./node_modules/sshpk/lib/fingerprint.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib'

Error: ./node_modules/sshpk/lib/signature.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib'

Error: ./node_modules/sshpk/lib/private-key.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib'

Error: ./node_modules/sshpk/lib/certificate.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib'

Error: ./node_modules/sshpk/lib/identity.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib'

Error: ./node_modules/sshpk/lib/dhe.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib'

Error: ./node_modules/sshpk/lib/utils.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib'

Error: ./node_modules/sshpk/lib/formats/pem.js[[39m0m
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib/formats'

Error: ./node_modules/sshpk/lib/formats/ssh-private.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib/formats'

Error: ./node_modules/sshpk/lib/formats/openssh-cert.js
Module not found: Error: Can't resolve 'crypto' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib/formats'

Error: ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/home/jeff/Projects/Typescript/DatLag/node_modules/request/lib'

Error: ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'http' in '/home/jeff/Projects/Typescript/DatLag/node_modules/forever-agent'

Error: ./node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'http' in '/home/jeff/Projects/Typescript/DatLag/node_modules/http-signature/lib'

Error: ./node_modules/request/request.js
Module not found: Error: Can't resolve 'http' in '/home/jeff/Projects/Typescript/DatLag/node_modules/request'

Error: ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'http' in '/home/jeff/Projects/Typescript/DatLag/node_modules/tunnel-agent'

Error: ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'https' in '/home/jeff/Projects/Typescript/DatLag/node_modules/forever-agent'

Error: ./node_modules/request/request.js
Module not found: Error: Can't resolve 'https' in '/home/jeff/Projects/Typescript/DatLag/node_modules/request'

Error: ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'https' in '/home/jeff/Projects/Typescript/DatLag/node_modules/tunnel-agent'

Error: ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in '/home/jeff/Projects/Typescript/DatLag/node_modules/forever-agent'

Error: ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in '/home/jeff/Projects/Typescript/DatLag/node_modules/tough-cookie/lib'

Error: ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in '/home/jeff/Projects/Typescript/DatLag/node_modules/tunnel-agent'

Error: ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in '/home/jeff/Projects/Typescript/DatLag/node_modules/mime-types'

Error: ./node_modules/assert-plus/assert.js
Module not found: Error: Can't resolve 'stream' in '/home/jeff/Projects/Typescript/DatLag/node_modules/assert-plus'

Error: ./node_modules/combined-stream/lib/combined_stream.js
Module not found: Error: Can't resolve 'stream' in '/home/jeff/Projects/Typescript/DatLag/node_modules/combined-stream/lib'

Error: ./node_modules/delayed-stream/lib/delayed_stream.js
Module not found: Error: Can't resolve 'stream' in '/home/jeff/Projects/Typescript/DatLag/node_modules/delayed-stream/lib'

Error: ./node_modules/isstream/isstream.js
Module not found: Error: Can't resolve 'stream' in '/home/jeff/Projects/Typescript/DatLag/node_modules/isstream'

Error: ./node_modules/request/request.js
Module not found: Error: Can't resolve 'stream' in '/home/jeff/Projects/Typescript/DatLag/node_modules/request'

Error: ./node_modules/sshpk/lib/ed-compat.js
Module not found: Error: Can't resolve 'stream' in '/home/jeff/Projects/Typescript/DatLag/node_modules/sshpk/lib'

Error: ./node_modules/throttled-request/lib/request-middleware.js
Module not found: Error: Can't resolve 'stream' in '/home/jeff/Projects/Typescript/DatLag/node_modules/throttled-request/lib'

Error: ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/home/jeff/Projects/Typescript/DatLag/node_modules/forever-agent'

Error: ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/home/jeff/Projects/Typescript/DatLag/node_modules/tunnel-agent'

Error: ./node_modules/request/request.js
Module not found: Error: Can't resolve 'zlib' in '/home/jeff/Projects/Typescript/DatLag/node_modules/request'

(node:37860) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/home/jeff/.steampath'
(node:37860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:37860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
</details>

**Comment by Winnie4is** [comment]
I cannot use this,too. Do you have any other methods to get the info from Google Play in Angular project?

**Comment by DATL4G** [comment]
> I cannot use this,too. Do you have any other methods to get the info from Google Play in Angular project?

I used the [REST api version](https://github.com/facundoolano/google-play-api) of this project and created a node server which I call using an HttpRequest in Angular

**Comment by andrui** [comment]
Same problem:
```
ERROR in ./node_modules/aws-sign2/index.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/aws-sign2'

ERROR in ./node_modules/aws4/aws4.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/aws4'

ERROR in ./node_modules/ecc-jsbn/index.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/ecc-jsbn'

ERROR in ./node_modules/http-signature/lib/verify.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/http-signature/lib'

ERROR in ./node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/http-signature/lib'

ERROR in ./node_modules/oauth-sign/index.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/oauth-sign'

ERROR in ./node_modules/request/lib/helpers.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/request/lib'

ERROR in ./node_modules/request/lib/oauth.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/request/lib'

ERROR in ./node_modules/request/lib/hawk.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/request/lib'

ERROR in ./node_modules/sshpk/lib/key.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib'

ERROR in ./node_modules/sshpk/lib/fingerprint.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib'

ERROR in ./node_modules/sshpk/lib/signature.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib'

ERROR in ./node_modules/sshpk/lib/private-key.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib'

ERROR in ./node_modules/sshpk/lib/certificate.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib'

ERROR in ./node_modules/sshpk/lib/identity.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib'

ERROR in ./node_modules/sshpk/lib/dhe.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib'

ERROR in ./node_modules/sshpk/lib/utils.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib'

ERROR in ./node_modules/sshpk/lib/formats/pem.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib/formats'

ERROR in ./node_modules/sshpk/lib/formats/ssh-private.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib/formats'

ERROR in ./node_modules/sshpk/lib/formats/openssh-cert.js
Module not found: Error: Can't resolve 'crypto' in '/proj/node_modules/sshpk/lib/formats'

ERROR in ./node_modules/request/lib/har.js
Module not found: Error: Can't resolve 'fs' in '/proj/node_modules/request/lib'

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'http' in '/proj/node_modules/forever-agent'

ERROR in ./node_modules/http-signature/lib/signer.js
Module not found: Error: Can't resolve 'http' in '/proj/node_modules/http-signature/lib'

ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'http' in '/proj/node_modules/request'

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'http' in '/proj/node_modules/tunnel-agent'

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'https' in '/proj/node_modules/forever-agent'

ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'https' in '/proj/node_modules/request'

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'https' in '/proj/node_modules/tunnel-agent'

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'net' in '/proj/node_modules/forever-agent'

ERROR in ./node_modules/tough-cookie/lib/cookie.js
Module not found: Error: Can't resolve 'net' in '/proj/node_modules/tough-cookie/lib'

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'net' in '/proj/node_modules/tunnel-agent'

ERROR in ./node_modules/mime-types/index.js
Module not found: Error: Can't resolve 'path' in '/proj/node_modules/mime-types'

ERROR in ./node_modules/assert-plus/assert.js
Module not found: Error: Can't resolve 'stream' in '/proj/node_modules/assert-plus'

ERROR in ./node_modules/combined-stream/lib/combined_stream.js
Module not found: Error: Can't resolve 'stream' in '/proj/node_modules/combined-stream/lib'

ERROR in ./node_modules/delayed-stream/lib/delayed_stream.js
Module not found: Error: Can't resolve 'stream' in '/proj/node_modules/delayed-stream/lib'

ERROR in ./node_modules/isstream/isstream.js
Module not found: Error: Can't resolve 'stream' in '/proj/node_modules/isstream'

ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'stream' in '/proj/node_modules/request'

ERROR in ./node_modules/sshpk/lib/ed-compat.js
Module not found: Error: Can't resolve 'stream' in '/proj/node_modules/sshpk/lib'

ERROR in ./node_modules/throttled-request/lib/request-middleware.js
Module not found: Error: Can't resolve 'stream' in '/proj/node_modules/throttled-request/lib'

ERROR in ./node_modules/forever-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/proj/node_modules/forever-agent'

ERROR in ./node_modules/tunnel-agent/index.js
Module not found: Error: Can't resolve 'tls' in '/proj/node_modules/tunnel-agent'

ERROR in ./node_modules/request/request.js
Module not found: Error: Can't resolve 'zlib' in '/proj/node_modules/request'
```

**Comment by andrui** [comment]
Looks like that issue is caused by nodejs dependencies.
