### ISSUE TITLE
Unable to retrieve the reviews

### ISSUE THREAD

**Issue by andreasbal** [facundoolano/google-play-scraper#463]
* Operating System: mac

### Description: 
I am trying to run a js script on the terminal to retrieve google play store app reviews. 

### Example code:
I use a simple script.

### Error message:
I receive the following error : at processTicksAndRejections (internal/process/task_queues.js:97:5) { status: 400 }

Can you please help me out? Thank you.

**Comment by icarcal** [comment]
@andreasbal can you check the version of the lib that you are using and give us a little example of the code?

**Comment by andreasbal** [comment]
I am not sure which version I am using. 

`const readline = require('readline')
const fs = require('fs');
var gplay = require('google-play-scraper');

gplay.reviews({
  appId: 'bot.touchkin&hl=en&gl=US',
  sort: gplay.sort.RATING,
  paginate: true,
  nextPaginationToken: null
  
}).then(console.log, console.log);`

**Comment by icarcal** [comment]
For the appId parameter, you should use only the app id.
Include country and lang (`gl` and `hl`) as parameters.

Try this:
```js
gplay.reviews({
  appId: 'bot.touchkin',
  lang: 'en',
  country: 'us',
  sort: gplay.sort.RATING,
  paginate: true,
  nextPaginationToken: null
}).then(console.log, console.log);
```

**Comment by andreasbal** [comment]
Thank you very much! It is solved now! Is it any way to sort the ratings? It downloads only the reviews with 5 stars due to the large number of reviews available. I would like to download reviews from different ratings. Thank you!

**Comment by icarcal** [comment]
You can use the `paginate` parameter set to `true` to receive all the reviews (this may take a while).
Other than that if you still want to use the pagination, be sure to send the `nextPaginationToken` set from the previous request.

If you want, you can also change the sorting by using one of the following: `sort.NEWEST`, `sort.RATING` or `sort.HELPFULNESS`

Be sure to check the [docs](https://github.com/facundoolano/google-play-scraper#reviews) for all the available options

**Comment by andreasbal** [comment]
Thank you very much!
