### ISSUE TITLE
App details get 404

### ISSUE THREAD

**Issue by chickito** [facundoolano/google-play-scraper#468]
* Operating System: Ubuntu 20.04
* Node version: 13
* google-play-scraper version: latest (2.6.3)

### Description: 
Some applications detail get a 404 :  I tested "fr.pmu.poker", "fr.pmu.sports", "com.winamax.winajs", "fr.unibet.sport", "sport.android.betclic.fr", "fr.fdj.enligne", "fr.zebet.zebet", "com.pyrsoftware.pokerstars.fr"
=> all apps with poker or bet services and PEGI-18
=> but dating services like "com.tinder", PEGI-18 too, are not concerned.

That said, a direct cURL gives the same 404. 
But an Advanced REST Client, or a Chrome/FireFox/Edge/Safari request works like a charm : header issues?

Thx.
### Example code:
```js
var gplay = require('google-play-scraper');

gplay.app({appId: 'fr.pmu.poker'}).then(console.log, console.log);
```

### Error message:

```
App not found (404)
```

**Comment by facundoolano** [comment]
Can you try passing the `country` parameter explicitly? Some apps are not available in all countries, and by default this package assumes the 'us' country code.
