### ISSUE TITLE
Replace Request with Axios

### ISSUE THREAD

**Issue by xeinebiu** [facundoolano/google-play-scraper#469]
As far as I can see, Request.js is not supported pretty well these times.

Basically, your work is awesome regarding the library, but when it comes to Proxy is not possible to use since Request.js is buggy there.

https://github.com/request/request/issues?q=Tunneling+socket+error

**Comment by facundoolano** [comment]
Closing this as we already replaced request with got [here](https://github.com/facundoolano/google-play-scraper/pull/494).
