### ISSUE TITLE
Please add apk downloading feature

### ISSUE THREAD

**Issue by pixiboom** [facundoolano/google-play-scraper#475]
* Operating System: 
* Node version:
* google-play-scraper version:

### Description: 
I have seen some website scraping download links directly from the play store, if it's possible please add this feature to the project.
Thanks
### Example code:
```js
// Put code to reproduce the issue here
```

### Error message:

```
Put error message here
```

**Comment by facundoolano** [comment]
This wasn't easy years ago when I considered it, I doubt it has changed. Either way it's not planned.
