### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by MFrat** [facundoolano/google-play-scraper#476]
* Operating System: MacOS Catalina
* Node version: v14.15.3
* google-play-scraper version: 8.0.2

### Description: 
When i try to read app's reviews, the _Cannot read property 'length' of undefined_ is raised.

### Example code:
```js
import { reviews } from 'app-store-scraper';

reviews({ appId: 'br.com.oi.minhafibra', num: 10 })
```

### Error message:

```
at formatReviewsResponse (/Users/xxx/node_modules/google-play-scraper/lib/requesters/reviewsMappedRequests.js:21:38)
    at processReviewsAndGetNextPage (/Users/xxx/node_modules/google-play-scraper/lib/requesters/reviewsMappedRequests.js:73:12)
```

**Comment by icarcal** [comment]
@MFrat I'm unable to replicate this error.

If I run
```js
gplay.reviews({
  appId: 'br.com.oi.minhafibra',
  num: 10,
  paginate: true
}).then(console.log)
```

I receive this response:
`{ data: [], nextPaginationToken: null }`

Can you double-check the scraper version?
