### ISSUE TITLE
Availability in country

### ISSUE THREAD

**Issue by ysb** [facundoolano/google-play-scraper#481]
Hi;

Some apps are available only in some countries. But when we try to get details for an unavailable country, it returns a valid result. So it's impossible to determine it's available or unavailable in specific country.

Is there any workaround about that? I found some mapping for this, will send a PR.

Thanks.

**Comment by ysb** [comment]
Just submitted a PR #482

**Comment by facundoolano** [comment]
merged and published, thanks!
