### ISSUE TITLE
Similar - Error: not found similar link

### ISSUE THREAD

**Issue by tomzweb** [facundoolano/google-play-scraper#483]
Hello,

Have been getting following error since today:

Error: not found similar link
    at ./node_modules/google-play-scraper/lib/similar.js:37:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

It was working yesterday and not today. I also had to resolve this issue too: https://github.com/facundoolano/google-play-scraper/issues/480

Any ideas?

**Comment by ysb** [comment]
Just update to 8.0.3

**Comment by VitaliyRDev** [comment]
@ysb

Seems like similar still isn't working, even after update.

**Comment by fti** [comment]
It doesn't work although update.

**Comment by ysb** [comment]
I understand the problem, I will send a PR about this.

**Comment by lau1944** [comment]
Does v8.0.3 work? It did not work for me.

**Comment by ysb** [comment]
Nope, we're waiting a new release.
cc: @facundoolano

**Comment by facundoolano** [comment]
published
