### ISSUE TITLE
Returned values are wrong 95% of the time

### ISSUE THREAD

**Issue by Giszmo** [facundoolano/google-play-scraper#491]
* Operating System: Ubuntu 21.10
* Node version: v16.11.0
* google-play-scraper version: 8.0.4

### Description: 

As reported earlier in #464, I get wrong results for many of the requests and now for most of them. 

### Example code:
```js
gplay = require('google-play-scraper')
hist={}
for (i=0; i<200; i++) gplay.app({appId: 'africa.bundle.mobile.app', lang: 'en', country: 'cl', throttle: 100}).then(app => {console.log(app.score);hist[app.score] = (hist[app.score] || 0) + 1})
// wait for it to finish …
console.log(hist)
{ '0': 194, '4.4756203': 6 }
```

The same experiment but with different `appId` can yield different values. For `com.google.android.apps.translate` I get for example `{ '4.3922243': 187, '4.457959': 4, '4.4579597': 5, '4.3919253': 4 }`, which notably are values that are all close to each other.

For en/us, `africa.bundle.mobile.app` yields `{ '4.4356437': 197, '4.4756203': 3 }`, which would at least be "close to each other" again.

**Comment by Giszmo** [comment]
I am still very much in the dark about what's going on. It feels like it might not actually be the api itself but the api should probably detect this and throw an error, with instructions on how to work around it if possible.

I added a semaphore to avoid downloading too many images in parallel with the throttled api calls, so with a `Semaphore(10)` and a `throttle: 100` (which effectively finished less than 20 api calls per second) I observed 990 of 1370 () api calls successful but in the second round success rate dropped to 11 of 390.

With a closer look, a pattern emerges. This is the first round, listing successful (`.`) and failed (`X`) api calls:

```
..X....X...X.............X..........X.............
........XX..............X......XXX...X....X.......
..........X..X.X...X.......X...................X..
...X.....XX....X.X..XX......X..X.........XX..X....
..XX..XX...XX.X..X.....X..XX...........XX....X...X
.X.X..XXX..XX.....XX.........X......XX.X.XXX.....X
X...X.........X...X..............X.....XX...XX....
X......XX.X...XXX.X..X....XXX..........X.X..XX....
X...X...X..XX.X.XX..X....X.X........XX..X.........
............XX.X...X.....X..XX....X..X.XX.....X.XX
............X............X.........X...XX.....X...
.......XX.......X......XX............X......X.....
....X...X...............X......X..X.XX............
X........XX..X.X.X......X........X........X...X...
......X......X.X..X........XX.....X....XXXX....X.X
X............XX.....X.............X.X..X....X..X..
.X.........X...........XX...X......X......XX....X.
XX.XX.XX.X..X..X..X....X......X............X......
...........X......X.........XX.........X..........
...XX...X.X...X....X.....X...X.........X..XX.X..X.
.....X...X.....X...X..............XX......X...X.X.
..X.....X....X.X........X.X..XX......X.X.......X..
......XXX...X.X...X.X................X........XX..
..XX..X....XX.X..X..XX...XXX.XXXXXX..XXXX..XXXXXX.
.XX.X.XXXXXXXX.XXXXXXXXXX.X.X.XXX.XX.........X.X.X
X.XXXXXXXXXXXXXXX.X.XXX.XXXXXXXXXX...XXXXXXXXXXXXX
XX.X.XX..XXXXX.XXXX.XX.XXXXXX.XXX.XXX.XXX.XXX..XXX
XXXXX...XXX..X.XXX.X
```

Did things actually get worse after about 1150 calls? As the failed-rate is rather rather high (homogeneously 21%) for the first 1150 calls, I don't think it's some kind of throttling, neither.

Above log, with some `s/\.X/X./g`:

```
XXXXX.............................................
XXXXXXXX..........................................
XXXXXX............................................
XXXXXXXXXXXX......................................
XXXXXXXXXXXXXXX...................................
XXXXXXXXXXXXXXXXX.................................
XXXXXXXXX.........................................
XXXXXXXXXXXXXXXX..................................
XXXXXXXXXXXXXX....................................
XXXXXXXXXXXXXX....................................
XXXXXX............................................
XXXXXXX...........................................
XXXXXXX...........................................
XXXXXXXXXX........................................
XXXXXXXXXXXXX.....................................
XXXXXXXXX.........................................
XXXXXXXXX.........................................
XXXXXXXXXXXXX.....................................
XXXXX.............................................
XXXXXXXXXXXXX.....................................
XXXXXXXXX.........................................
XXXXXXXXXXX.......................................
XXXXXXXXXX........................................
XXXXXXXXXXXXXXXXXXXXXXXXXXXX......................
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...................
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.......
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.............
XXXXXXXXXXXXX.......
```

**Comment by 89z** [comment]
If youre interested, I have an alternative tool that works:

~~~
PS C:\> googleplay -a africa.bundle.mobile.app
{Offer:{FormattedAmount:$0} Details:{AppDetails:{DeveloperName:BundleAfrica
VersionCode:213 Version:3.0.0 InstallationSize:43.440 MB
UploadDate:Jul 15, 2021}} AggregateRating:{OneStar:774 TwoStar:96
ThreeStar:1129 FourStar:677 FiveStar:8940}}
~~~

Its available as a package too, so you can write your own program with it.

https://github.com/89z/googleplay

**Comment by 89z** [comment]
I had a previous comment offering another package, but I deleted it after reading your second comment. This seems to be a pretty clear cut case of API abuse. 20 api calls per second seems unacceptably high, even for some paid options. Im not sure why you think you can pound a free API like this and get away with it.

**Comment by Giszmo** [comment]
So apparently Google rolled out per-country stats gradually, which made me think the initially occasionally missing rating for Chile was a bug or throttling as on subsequent calls I got stats. This issue as created at a point where those stats were not obtainable at all anymore.
