### ISSUE TITLE
Crashing app list (en language)

### ISSUE THREAD

**Issue by Wremeker** [facundoolano/google-play-scraper#505]
* Operating System: Mac os Big Sur
* Node version: 17.01
* google-play-scraper version: last

### Description: 
I get an error when I make a query with the parameters:  `gplay.list({ country: 'en', lang: 'en', collection: 'topselling_free' });`

### Error message:

`Error: Error requesting Google Play: Response code 400 (Bad Request)`

**Comment by facundoolano** [comment]
does this continue with the new version?

**Comment by icarcal** [comment]
@Wremeker try this:

`gplay.list({ country: 'us', lang: 'en', collection: 'topselling_free' }).then(console.log);`

Seems like you are sending the wrong country and the URL that the scrapper is trying to access really give you a 400:
`https://play.google.com/store/apps/top?hl=en&gl=en`

**Comment by Wremeker** [comment]
> @Wremeker try this:
> 
> `gplay.list({ country: 'us', lang: 'en', collection: 'topselling_free' }).then(console.log);`
> 
> Seems like you are sending the wrong country and the URL that the scrapper is trying to access really give you a 400: `https://play.google.com/store/apps/top?hl=en&gl=en`
@icarcal Thank you very much! It works
