### ISSUE TITLE
Is there a way to scrape the featured image for the app too?

### ISSUE THREAD

**Issue by EasyGitHub99** [facundoolano/google-play-scraper#53]
I think not all apps have a featured image but the most popular ones do. Is there a way to be able to scrape the URL for it?

**Comment by facundoolano** [comment]
Can you show an example of a page showing a featured image?

**Comment by EasyGitHub99** [comment]
Actually, it looks like its only meant to be visible in the Google Play app.
https://support.google.com/googleplay/android-developer/answer/6066610?hl=en

So probably can't do this unless theres a hack or something.

**Comment by facundoolano** [comment]
Ok, if someone figures out how to get the url for that image, reopen this.
