### ISSUE TITLE
score, ratings, reviews and histogram appears to be 0 for some apps (for eg - 'snkt.radhe.alllanguagestranslation')

### ISSUE THREAD

**Issue by namanappbroda011** [facundoolano/google-play-scraper#530]
* Operating System:
* Node version:
* google-play-scraper version:

### Description: 
Even though this app has 100k+ downloads and play store showing its rating, scraper can't scrape the data and showing 0 instead.
### Example code:
```js
// Try this
 gplay.app({appId: 'snkt.radhe.alllanguagestranslation'})
  .then(console.log, console.log);
```
### Output
```
  minInstalls: 100000,
  maxInstalls: 244770,
  score: 0,
  scoreText: '0.0',
  ratings: 0,
  reviews: 0,
  histogram: { '1': 0, '2': 0, '3': 0, '4': 0, '5': 0 },
  price: 0,
```

### Error message:

```
Put error message here
```

**Comment by srikanthlogic** [comment]
When you pass country param, it works. Noticed this in few apps, don't know if its related to some developer settings 
![image](https://user-images.githubusercontent.com/126862/160228471-439388cd-3636-46d0-b131-7f8ff0be082e.png)

**Comment by namanappbroda011** [comment]
Yes by inserting the params it worked! Thanks alot
