### ISSUE TITLE
can I get use this module with a proxy？

### ISSUE THREAD

**Issue by oto-tatsuu** [facundoolano/google-play-scraper#531]
For I'm in China. I can only use proxy to access Google Play.Does this project supports proxy?

**Comment by jseparator** [comment]
> 

改的哪块

**Comment by facundoolano** [comment]
我不明白

**Comment by Panda2Chan** [comment]
> ```js
> const gplay = require('google-play-scraper')
> const ProxyAgent = require('proxy-agent')
> const proxy = new ProxyAgent('http://your_proxy_ip:port')
> 
> gplay.app({
>   appId: 'com.miniclip.eightballpool',
>   lang: 'zh_CN',
>   country: 'US',
>   requestOptions: {
>     retry: {limit: 0},
>     agent: {
>       https: proxy,
>       http: proxy,
>       http2: proxy
>     }
>   }
> }).then(console.log)
>   .catch(console.error);
> ```
> 
> 网络层用的是 got, requestOptions 是 got 的 options, 翻源码找到的

有用，感谢

**Comment by Arsh1219** [comment]
> ```js
> const gplay = require('google-play-scraper')
> const ProxyAgent = require('proxy-agent')
> const proxy = new ProxyAgent('http://your_proxy_ip:port')
> 
> gplay.app({
>   appId: 'com.miniclip.eightballpool',
>   lang: 'zh_CN',
>   country: 'US',
>   requestOptions: {
>     retry: {limit: 0},
>     agent: {
>       https: proxy,
>       http: proxy,
>       http2: proxy
>     }
>   }
> }).then(console.log)
>   .catch(console.error);
> ```
> 
> 网络层用的是 got, requestOptions 是 got 的 options, 翻源码找到的

Thank you!
