### ISSUE TITLE
Have same error

### ISSUE THREAD

**Issue by shaindi** [facundoolano/google-play-scraper#541]
my code worked fine till yesterday,
then stopped work.

the same error (Error: Cannot read property 'replace' of undefined)

has something changed in api?
is there new version to fix this?

**Comment by sergeyrepko** [comment]
i have exactly the same problem
how can this be fixed?
<img width="986" alt="image" src="https://user-images.githubusercontent.com/80681063/169237637-305fc17c-7a1a-4119-90b8-c475e1bbeb1d.png">

**Comment by ChayaGel** [comment]
#539 it is the same question.

any answer?

**Comment by VitaliyRDev** [comment]
@icarcal @facundoolano any ideas ?

**Comment by icarcal** [comment]
Looks like google is doing some kind of AB test for the new UI, as folks mentioned in other issues.
I'm taking a look on this now, but seems to me that unless we map both of old and new UI, the scrapper will be indeed randomly failling

**Comment by sandeepscet** [comment]
Duplicate of #https://github.com/facundoolano/google-play-scraper/issues/539
