### ISSUE TITLE
Issue with Country:BR

### ISSUE THREAD

**Issue by sandeepscet** [facundoolano/google-play-scraper#543]
* Operating System: Windows 
* google-play-scraper version: 8.1.0

### Description: 
Multiple Functions are not working with Brazil country code including provided TC in google play scraper.  Below code working for US, IN.

### Example code:
```js
gplay.list({
      country : 'br',
      collection: gplay.collection.NEW_FREE,
      num: 5
    }) 
```

### Error message:

```
The collection topselling_new_free is invalid for the given category, top apps or new apps"
```

**Comment by sandeepscet** [comment]
Randomly this error started for IN also. Seems due to playstore UI rewamp.

**Comment by HeyItsMedz** [comment]
Have also randomly come across this issue with country set to gb

**Comment by sandeepscet** [comment]
Duplicate of https://github.com/facundoolano/google-play-scraper/issues/539
