### ISSUE TITLE
The collection topselling_paid_games is invalid for the given category, top apps or new apps

### ISSUE THREAD

**Issue by Panda2Chan** [facundoolano/google-play-scraper#549]
* Operating System:windows 10
* Node version:14.16.1
* google-play-scraper version:8.1.0

### Description: 
【 gplay.list 】 I can't use all of them，such as 【TOP_FREE_GAMES】，【GAME_ROLE_PLAYING】

### Example code:
```js
 const opts = {
    category: gplay.category[“TOP_FREE_GAMES”],
    lang: "zh-CN",
    fullDetail: true
}
let res = await gplay.list(opts)
```

### Error message:
```
The collection topselling_paid_games is invalid for the given category, top apps or new apps
```

**Comment by lau1944** [comment]
Same here, waiting for update...

**Comment by adtimizer** [comment]
My two cents:
i've found two lists that works but trying to find a pattern - to be continue

https://play.google.com/store/apps/collection/topselling_new_free
https://play.google.com/store/apps/collection/topselling_new_paid

**Comment by Aliaksandr-Kasko-JazzTeam** [comment]
Same here. From all collections listed in `gplay.collection` only one collection (`topselling_new_free`) do not fail but returns empty list.
@adtimizer I suppose that Google changed url from `/store/apps/top/category/{category_name}` to `/store/apps/collection/{category_name}` but it needs to test

**Comment by facundoolano** [comment]
can you check if this still happens with the latest version?

**Comment by Panda2Chan** [comment]
> 

Problem solved, it's perfect, thanks

**Comment by Panda2Chan** [comment]
@facundoolano The problem has been solved, thanks

> can you check if this still happens with the latest version?

The problem has been solved, thanks
