### ISSUE TITLE
Genres/categories incorrect or missing

### ISSUE THREAD

**Issue by archon810** [facundoolano/google-play-scraper#554]
* Operating System: OpenSUSE 15.3
* Node version: v12.20.0
* google-play-scraper version: git+https://github.com/facundoolano/google-play-scraper#pull/545/head"

### Description: 
Let's take https://play.google.com/store/apps/details?id=mytown.home as an example. Both in json and html, we see multiple categories for this game:
https://play.google.com/store/apps/category/GAME_SIMULATION
https://play.google.com/store/apps/category/GAME_CASUAL

However, google-play-scraper returns only `"genre":"Educational","genreId":"GAME_EDUCATIONAL"` which isn't even visible on the page. Both GAME_SIMULATION and GAME_CASUAL are missing from the returned data.

![image](https://user-images.githubusercontent.com/469543/171296645-a650d7f4-67f6-4649-9c76-cd8ef58d6ade.png)

1. Can support be added for more than one genre/category per app?
2. The correct categories should be returned. I suppose, in this case, it should be both of the above plus GAME_EDUCATIONAL?

Another example: https://play.google.com/store/apps/details?id=com.mojang.minecraftpe. This should have https://play.google.com/store/apps/category/GAME_SIMULATION, but we get back `"genre":"Arcade","genreId":"GAME_ARCADE"`.
![image](https://user-images.githubusercontent.com/469543/171297085-7b70a8fc-f9f0-4308-998c-1e907645e0a9.png)

And another: https://play.google.com/store/apps/details?id=com.nianticlabs.pokemongo. This should have https://play.google.com/store/apps/category/GAME_ACTION and https://play.google.com/store/apps/category/GAME_CASUAL, but we get `"genre":"Adventure","genreId":"GAME_ADVENTURE"`.
![image](https://user-images.githubusercontent.com/469543/171297185-7cbb1718-31e6-404c-991c-60664fc51b26.png)

I don't understand why the data mismatches so much. Is the wrong data being looked at?

**Comment by archon810** [comment]
https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox doesn't even show a category in HTML? I can't find it. Yet the scraper returns `"genre":"Tools","genreId":"TOOLS"`. Google, why are you like this?

**Comment by baguse** [comment]
@archon810 the scrapper get the return from javascript data i think

**Comment by archon810** [comment]
> @archon810 the scrapper get the return from javascript data i think

This needs looking at, because the data is there in the JSON too, I think.

**Comment by borgmonitoringzoo** [comment]
PSA. Google released a new version of the Google play UI. Genres are among some of the fields that have changed.

The change started rolling out May 12th per this article: https://chromeunboxed.com/google-play-store-web-app-redesign-begins-rollout-us

You may not have seen the change because Google was doing AB testing.

**Comment by 89z** [comment]
I would recommend closing this issue. @archon810 is a known copyright violator:

https://github.com/illogical-robot/apkmirror-public/issues/200

**Comment by archon810** [comment]
@facundoolano Is this one on your radar as well?

**Comment by 89z** [comment]
I would not help @archon810, as they use open source software like this one, but refuse any information on their own software.

**Comment by archon810** [comment]
> I would not help @archon810, as they use open source software like this one, but refuse any information on their own software.

I'm blocking you because you seem to have some weird vendetta and complete lack of understanding of licenses, like MIT.

**Comment by facundoolano** [comment]
can you check if this still happens with the latest version?

**Comment by srikanthlogic** [comment]
This issue still persists.   "APPLICATION" is the only category that is being returned.
