### ISSUE TITLE
Does this library work?

### ISSUE THREAD

**Issue by AleAmla987** [facundoolano/google-play-scraper#556]
Hello people, this library no longer works? because I downloaded the latest production version and it has an error, I found that the author tells me to download a version with a specific commit but I can't put that in production.

**Comment by marxsk** [comment]
Create your own fork and put it into a production if current situation is not suitable for you

**Comment by aldochaconc** [comment]
I've been using this library and everything works fine. I'm using the one that is on npmjs

**Comment by AleAmla987** [comment]
> Cree su propia bifurcación y póngala en producción si la situación actual no es adecuada para usted

Thanks for the advice, I already did.

**Comment by mukut007** [comment]
> I've been using this library and everything works fine. I'm using the one that is on npmjs

Can you use the list API to get top apps in a category? I keep getting `Error: The collection topselling_free is invalid for the given category, top apps or new apps`

**Comment by aldochaconc** [comment]
> > I've been using this library and everything works fine. I'm using the one that is on npmjs
> 
> Can you use the list API to get top apps in a category? I keep getting `Error: The collection topselling_free is invalid for the given category, top apps or new apps`

Oh, I haven't tried that case, but as the message says, which categories are you using?
