### ISSUE TITLE
Developer information is not getting populated for any  app

### ISSUE THREAD

**Issue by AbhishekOnedigital** [facundoolano/google-play-scraper#558]
![image](https://user-images.githubusercontent.com/17587331/172840653-67d78a33-c91a-4c43-a800-e5f788490c15.png)

**Comment by gilzonme** [comment]
`var gplay = require('google-play-scraper');
gplay.search({
    term: "app",
  }).then((data)=>{
      console.log(data)
//respose is []
  })`

**Comment by facundoolano** [comment]
can you check if this still happens with the latest version?

**Comment by AbhishekOnedigital** [comment]
Yes it working thanks @facundoolano
