### ISSUE TITLE
V9 has bugs

### ISSUE THREAD

**Issue by ChayaGel** [facundoolano/google-play-scraper#563]
Fails "Cannot read property 'map' of undefined" on some cases - problems about new UI that are not fixed:
1.Countries issue seems still not work (I tried with "be")
(https://github.com/facundoolano/google-play-scraper/issues/551#issuecomment-1142043251 - this is the principle of solution, but have to come into the new version)
2. mapping result page with main-app not work, (try "waze" vs "waze_", only "waze_" worked properly) I saw that the code of v9 **is trying** to fix this, but something there is probably wrong.

**Comment by knirpsfass** [comment]
First issue is on me.
I've analyzed it further once again in
https://github.com/facundoolano/google-play-scraper/issues/551#issuecomment-1167466402

**Comment by ChayaGel** [comment]
works
