### ISSUE TITLE
app() no longer returns 'size'

### ISSUE THREAD

**Issue by KaKi87** [facundoolano/google-play-scraper#574]
- Operating System: Debian 10
- Node version: 16.16.0
- google-play-scraper version: [`f4a1cf6`](https://github.com/facundoolano/google-play-scraper/commit/f4a1cf6b04959ec69fc5684036315032206fde6f) (last commit)

### Description:

The `app` method no longer returns the `size` property.

### Example code:

```js
require('google-play-scraper')
    .app({ appId: 'com.github.android' })
    .then(res => console.log(res.size));
```

### Error message:

```js
undefined
```

**Comment by archon810** [comment]
Is the size even present on the page? https://play.google.com/store/apps/details?id=com.github.android. I don't see it.

**Comment by KaKi87** [comment]
If the property disappeared because of this, the documentation should be updated and a changelog written accordingly.

However, the Play Store app on Android still shows the size.

**Comment by archon810** [comment]
I looked around, and I don't see the size on any app I checked on the web. Perhaps the new website obsoleted this info, which is a shame, but it's quite typical Google.

**Comment by KaKi87** [comment]
Are you saying that this package can't get information that the mobile app provides ?

**Comment by archon810** [comment]
This project is a web Play Store scraper.

**Comment by KaKi87** [comment]
This doesn't change the fact that the documentation should have changed accordingly.
A lot of undocumented changes have occured since this major release.

**Comment by facundoolano** [comment]
Feel free to send Pull requests to update the documentation

**Comment by KaKi87** [comment]
I could, [if I knew everything that changed since v9](https://github.com/facundoolano/google-play-scraper/issues/562). But only you do.

**Comment by facundoolano** [comment]
I just manage the project, I don't make every change. The information I have is what's publicly available in the repository, so it's the same information you have.

I don't even use this project, I just maintain it. If you think there are opportunities to improve it, your changes are welcome.
