### ISSUE TITLE
Error: Error requesting Google Play:Response code 429 (Too Many Requests)

### ISSUE THREAD

**Issue by sergeyrepko** [facundoolano/google-play-scraper#575]
Error: Error requesting Google Play:Response code 429 (Too Many Requests)
    at /Users/admin/Desktop/00-scraper 2/node_modules/google-play-scraper/lib/utils/request.js:41:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 429
}

**Comment by facundoolano** [comment]
Try making less requests or using the throttle feature described in the readme
