### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined  seems not fixed

### ISSUE THREAD

**Issue by cf211** [facundoolano/google-play-scraper#586]
@YairLeviMevorach

i still see this error , how can i fix it?
Aug 18 00:21:36 node[867]: TypeError: Cannot read property 'replace' of undefined 
Aug 18 00:21:36 node[867]: at Object.descriptionText [as fun] (/.../node_modules/google-play-scraper/lib/utils/mappingHelpers.js:6:51)
Aug 18 00:21:36 node[867]: at /.../node_modules/google-play-scraper/lib/utils/scriptData.js:52:19 
Aug 18 00:21:36 node[867]: at XWrap.f (/.../node_modules/ramda/dist/ramda.js:5955:28)

the following github actions failed. Maybe deploy not yet?
https://github.com/facundoolano/google-play-scraper/actions/runs/2883376349

**Comment by nadavzipo** [comment]
+1

I think it might be because the version wan't updated after @YairLeviMevorach update.
@facundoolano need publish the change to npm

**Comment by YairLeviMevorach** [comment]
Copy this
`        "google-play-scraper": "git+https://github.com/facundoolano/google-play-scraper#pull/583/head",
`
to your "package.json" file

**Comment by hi-chin-rt** [comment]
@YairLeviMevorach
i copy 
"google-play-scraper": "git+https://github.com/facundoolano/google-play-scraper#pull/583/head",
to my "package.json" file 
then it works

however i want keep that 
"google-play-scraper": "google-play-scraper": "^9.1.0", 
int my "package.json" file 

Could you publish the change to npm like "9.1.1"?

**Comment by cf211** [comment]
@YairLeviMevorach
i copy
"google-play-scraper": "git+https://github.com/facundoolano/google-play-scraper#pull/583/head",
to my "package.json" file
then it works

however i want keep that
"google-play-scraper": "google-play-scraper": "^9.1.0",
int my "package.json" file

Could you publish the change to npm like "9.1.1"?

**Comment by sergeyrepko** [comment]
i also added the line `"google-play-scraper": "git+https://github.com/facundoolano/google-play-scraper#pull/583/head",`
but my problem is not solved :(
Same error

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/80681063/185903346-e91201e4-2a09-4e65-9fa1-b6d58f8b833c.png">
