### ISSUE TITLE
Google play start enforcing rate limitation -  Response code 429 (Too Many Requests)

### ISSUE THREAD

**Issue by ntedgi** [facundoolano/google-play-scraper#590]
looks like something uploaded at `2022-09-12 10:18:43UTC`

* Operating System: ALL
* Node version: ALL 
* google-play-scraper version: ALL

### Description: 
Google play start enforcing rate limitation 

### Error message:

```
Failed scraping url: function url() { [native code] }. Error: Error: Error requesting Google Play:Response code 429 (Too Many Requests)
    at /usr/local/platform-js/dist/apps/server/api/demand/scraper/google-store-scrapper/lib/utils/request.js:35:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 429
```

**Comment by 89z** [comment]
You've given no context, so it could be assumed that you're just abusing the API. If you can provide some more details, people might be able to help you.
