### ISSUE TITLE
Search is again stop working

### ISSUE THREAD

**Issue by rsutariy** [facundoolano/google-play-scraper#596]
* Operating System:MacOS 12.4 and Amazon Linux 2
* Node version:16.16.0
* google-play-scraper version:9.1.1

### Description: 
Search is not working properly. It throws an error more than corrected result for same keyword.
keywords examples : Facebook, Walmart etc..

### Example code:
```js
gplay.search({
    term: "facebook",
    num: 2
  }).then(console.log, console.log);
```

### Error message:

```
Error TypeError: Cannot read properties of undefined (reading 'map')
```

**Comment by ansoncen** [comment]
I suggest u use a try catch and loop the search until you get the results.

**Comment by rsutariy** [comment]
Is there any long term approach?

**Comment by Djip** [comment]
Depends in anyone finds a solution to the problem. @facundoolano

**Comment by Djip** [comment]
https://github.com/facundoolano/google-play-scraper/compare/main...Djip:google-play-scraper:main#diff-5fa3e79ff4f9f5b6d3a08d3abab2c8db53823a6b1e36d9ecd723792890870aaf

I've made these changes in my local fork, and it seems to work fine, but haven't had too much time to test it in different scenarios. 

Note:
Looping only seemed to work for a little bit of time. Perhaps cause some of the servers being hit still were on the old patch, but now most of them is on the "new"

**Comment by CyrilCermak** [comment]
@Djip, how about opening a PR with your change? :)

**Comment by Djip** [comment]
> @Djip, how about opening a PR with your change? :)

As mentioned, i'm not 100% sure this works every time

**Comment by rsutariy** [comment]
@facundoolano Any update?

**Comment by insungson** [comment]
I have a same issue. and fix that with try catch loop when it works.

**Comment by CyrilCermak** [comment]
@Djip, I am happy to give it a test drive if you open a PR with the change. :)

**Comment by CyrilCermak** [comment]
I opened a PR with your change @Djip, it works perfectly fine for me. @facundoolano, can you please look into it?  Thanks a lot! 
https://github.com/facundoolano/google-play-scraper/pull/600

**Comment by facundoolano** [comment]
closing as fixed
