### ISSUE TITLE
404 error returned by specific app

### ISSUE THREAD

**Issue by joyfuI** [facundoolano/google-play-scraper#608]
* Operating System: Windows 11 Home
* Node version: v16.14.2
* google-play-scraper version: 9.1.1

### Description: 
[https://play.google.com/store/apps/details?id=studio.gameberry.Crow](https://play.google.com/store/apps/details?id=studio.gameberry.Crow)
Only this app gives me a 404 error and I can't get any information.

### Example code:
```js
const gplay = require('google-play-scraper');

gplay.app({ appId: 'studio.gameberry.Crow' }).then(console.log, console.log);
```

### Error message:
```
Error: App not found (404)
    at C:\Users\jong9\Desktop\project\test\node_modules\google-play-scraper\lib\utils\request.js:41:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 404
}
```

**Comment by archon810** [comment]
This app is not live on the Play Store.

**Comment by joyfuI** [comment]
thank you. It was not published in the US. I solved it. ("country" option)

[https://play.google.com/store/apps/details?id=studio.gameberry.Crow&gl=kr](https://play.google.com/store/apps/details?id=studio.gameberry.Crow&gl=kr)
[https://play.google.com/store/apps/details?id=studio.gameberry.Crow&gl=us](https://play.google.com/store/apps/details?id=studio.gameberry.Crow&gl=us)
