### ISSUE TITLE
Migrate to ESM

### ISSUE THREAD

**Issue by facundoolano** [facundoolano/google-play-scraper#632]
Replace the old commonjs requires with ESM imports. This is preventing an update of the latest version of the got lib at the moment, and I'm assuming that in general it's the preferred default nowadays.

**Comment by tpwatson** [comment]
I got the migration done just now.
After fixing all the errors one by one it appears to be functioning 100%
The fact that every unit test gave a result without an error tells me the migration is complete.
![Untitled](https://github.com/facundoolano/google-play-scraper/assets/8966870/b73aa366-291b-4fed-9e47-b7302b44f0c2)

I create a seperate branch on my fork of this repo. I'm just trying to figure out how to push to that so I can submit a PR for this.

**Comment by tpwatson** [comment]
https://github.com/facundoolano/google-play-scraper/pull/637

**Comment by facundoolano** [comment]
closed by #651
