### ISSUE TITLE
Get number of records more than 30

### ISSUE THREAD

**Issue by vishal-sarvaiya-origin** [facundoolano/google-play-scraper#642]
Dear Developers

As per Google new UI, Currently we are using max 30 recods. Thats not enough for mostoff.
Here I am sharing you google's old serach url

https://play.google.com/work/search?q=whatsapp

Can you update this URL for search data?

**Comment by abhi9726** [comment]
i agree.

please add support for this url.

+1

**Comment by vishal-sarvaiya-origin** [comment]
@abhi9726 

I already add old URL for serach apps
Again I'm sharing URL

https://play.google.com/work/search?q=whatsapp

**Comment by DevinXiaoBai** [comment]
When will the new version be released? How about solving this problem?

**Comment by DevinXiaoBai** [comment]
> 
What can I do if an error is displayed when I modify the link directly

**Comment by vinniec** [comment]
Confirmed, I can't see too more than 30 results either, though updating the link in line 26 of `search.js` file is not enough because this other search page has a different layout.
Could this be updated?

**Comment by tarasovladislav** [comment]
Any luck on this? Maybe anyone made a fork and fixed?

**Comment by EzequielAdrianM** [comment]
We really need this to be fixed.

**Comment by abhi9726** [comment]
@vishal-sarvaiya-origin   vishal bhai, kai med padyo?

**Comment by abhi9726** [comment]
@facundoolano its working! I’m getting 250 results.

**Comment by abhi9726** [comment]
@sgilroy thanks brother 😄
