### ISSUE TITLE
What is `updated` time zone (if any fixed)?

### ISSUE THREAD

**Issue by Benjamin-Loison** [facundoolano/google-play-scraper#655]
[`updated` field I'm referring to](https://github.com/facundoolano/google-play-scraper/blob/89202849f6054f6ac64790a385abc3c18ae98df1/README.md?plain=1#L96).

**Comment by srikanthlogic** [comment]
updated is the seconds since [epoch](https://en.wikipedia.org/wiki/Epoch_(computing)).
