### ISSUE TITLE
There was an error fetching the reviews!

### ISSUE THREAD

**Issue by simplatek** [facundoolano/google-play-scraper#67]
Can't get app reviews working using your example.  Tried using many different appId's and this is the same error each time:  [Error: Error requesting Google Play]

**Comment by facundoolano** [comment]
Hi @simplatek, there was an error in the README example (I've changed sort values to use constants now, and the example was outdated). Please check again and past the code you're trying in case it still fails.

Thanks!

**Comment by santhoshlfms** [comment]
I used this to get reviews   **sort: gplay.sort.RATING** , Rating is not defined. and also i'm getting "There was an error fetching the application!" error.

**Comment by facundoolano** [comment]
@santhoshlfms this change is in the current dev branch, not on the latest relase you get through npm (I'll release in the next couple of days, after making sure nothing fails). If you installed with npm, use [these instructions](npmjs.com/package/google-play-scraper).

If you are using the dev branch and it still fails, please paste the code here.

**Comment by simplatek** [comment]
That link 'these instructions' is broken.  Just do this to get the latest dev version.   Works for me, thx.

npm install https://github.com/facundoolano/google-play-scraper.git#dev

**Comment by facundoolano** [comment]
fixed the link. 

I'm closing this, if anyone still has issues, please reopen.
