### ISSUE TITLE
Variable number of reviews returned

### ISSUE THREAD

**Issue by gianlucascoccia** [facundoolano/google-play-scraper#676]
The reviews methods seems to return a different number of reviews on each call.
I slightly modified the example in the documentation to reproduce the issue:

```
import gplay from "google-play-scraper";

gplay.reviews({
  appId: 'com.facebook.katana',
  num: 3000
}).then(function(apps){
  console.log(apps.data.length);
}, console.log);
```

When called multiple times the output is :

```
300
300
150
150
150
150
1200
```

This  used to work in the past, getting hundreds of thousands of reviews in a single call

**Comment by sheldon0711** [comment]
Experience the same issue. Now reviews_all function only returns very limited reviews, instead of all reviews in the past.

**Comment by gianlucascoccia** [comment]
In [this sister project](https://github.com/JoMingyu/google-play-scraper/) they have encountered the same issue.
[Here](https://github.com/JoMingyu/google-play-scraper/issues/209#issuecomment-2036302883) I provided  a workaround around the issue that appears to be working.
I would submit a PR to fix the issue but my JavaScript skills are fairly limited.

**Comment by petskratt** [comment]
Looks like Google has implemented limit of 150 items per response, so paging is needed. And with paging comes need to provide `NID` cookie so loadbalancer sends your request to proper backend that knows about `nextPaginationToken` from pervious request (if not, then I rarely get more than 4-5 pages of 150 items).

To validate my theory I modified https://github.com/facundoolano/google-play-scraper/blob/main/lib/reviews.js#L154 adding `NID` value from my browser ... and got paging working:

```javascript
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
      'Cookie': 'NID=[cookie value from browser];'
    }
```

Real solution means implementing `cookieJar`, perhaps in https://github.com/facundoolano/google-play-scraper/blob/main/lib/utils/request.js

```javascript
import gplay from "google-play-scraper";

const fetchAllReviews = (appId, nextPaginationToken) => {
    return gplay.reviews({appId: appId, paginate: true,  nextPaginationToken: nextPaginationToken})
        .then (
            (res) => res.nextPaginationToken
                ? fetchAllReviews (appId, res.nextPaginationToken).then (fullData => [...res.data, ...fullData])
                : res.data
        )
}

fetchAllReviews ('com.some.thing', null)
    .then (console.log)
    .catch (console.warn)
```
