### ISSUE TITLE
Error using app function

### ISSUE THREAD

**Issue by mlatif01** [facundoolano/google-play-scraper#681]
* Operating System: Mac OS Sonoma 14.5
* Node version: 16.20.1
* google-play-scraper version: 9.0.0

### Description: 
Error when using .app function

### Example code:
```js
return gplay.app({ appId: appId }).then(function(info) {
            return info;
        })
        .catch(function(err) {
            return null;
        });
```

### Error message:

```
"Error requesting Google Play:The \"listener\" argument must be of type function. Received an instance of Object"
```

I was previously getting this [error](https://github.com/facundoolano/google-play-scraper/issues/582) on version 6.0.3. I upgraded to 9.0.0 as it still allows for using require however I am now getting the error above. I would be grateful if anyone has any ideas on how to fix this.

**Comment by jonathansampson** [comment]
I'm not able to reproduce this issue.

I confirmed that version 16.20.1 of Node was being used, and executed the following script:

```js
const results = gplay.app({ appId: 'com.brave.browser' })
  .then(function (info) { return info; })
  .catch(function () { return null; });

console.log(await results);
```

![image](https://github.com/user-attachments/assets/5d0ea1e9-26f6-4779-891e-290e031a1224)
