### ISSUE TITLE
Access short description from app listing

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [facundoolano/google-play-scraper#687]
The library provides an API to fetch data about an app. The app detail object returned by this API contains the full description of the app, but not the short description. 

Is there a reason why the short description is not included? I can see it if I inspect the source code of the Play Store page.

**Comment by PierfrancescoSoffritti** [comment]
Sure, every app has one [see screenshot from Google Play](https://github.com/user-attachments/assets/37bf1a43-5462-4de1-93d6-4b077d68321b).

It looks like they are only visible from Google Play's mobile UI, not from the desktop UI. [See screenshot from mobile UI](https://dl3.pushbulletusercontent.com/VsNemFfQhiRgHqNjV2xDJO1W45z33eUw/Screenshot_20240809-193119.png).

Somewhat annoyingly the source code of the web page only mentioned it as "description". You can search for "AI video editor with music!" in the source of [this page](https://play.google.com/store/apps/details?id=com.camerasideas.instashot).

**Comment by jonathansampson** [comment]
Looks like the short description is just adjacent to the long description, so trivial to include. I've issued a PR to add the property and data, @PierfrancescoSoffritti. Nice suggestion :)

**Comment by PierfrancescoSoffritti** [comment]
Nice, thanks for the very fast PR!

**Comment by jonathansampson** [comment]
It looks like `summary` has the value you're seeking.

**Comment by facundoolano** [comment]
@PierfrancescoSoffritti you are looking for the `summary` property. Closing this as it's already implemented.
