### ISSUE TITLE
Why is the max index 500?

### ISSUE THREAD

**Issue by kmicinski** [facundoolano/google-play-scraper#74]
Does the API not give a way to see more apps?

**Comment by facundoolano** [comment]
That's correct, when I first wrote the scraper Google play would return empty results for start values higher than 500.

Please let me know if you find evidence that this limit has increased.

**Comment by kmicinski** [comment]
Understood. Thanks for the answer.

**Comment by abhidec1** [comment]
is it possible to fetch more than 500 now or still a nono ?

**Comment by facundoolano** [comment]
It's a matter of [removing these lines](https://github.com/facundoolano/google-play-scraper/blob/dev/lib/list.js#L48-L50) and trying to see if there are more results after 500. I don't have time for this, but feel free to try yourself.

**Comment by kmicinski** [comment]
This won't work. Google disallows this by design because they want to make it extremely hard to make app scrapers. You need to write a crawler instead to do this. It is not too hard using a mix of selenium and rate limiting to crawl through a web of links, but it is nontrivial and needs a few days worth of hacking to get working.

**Comment by abhidec1** [comment]
@facundoolano  yea i already tried that before commenting didnt work 😅 . @kmicinski  good stuff thanks for the tip 😉 .
