### ISSUE TITLE
Google changed

### ISSUE THREAD

**Issue by johnipiresrodrigues** [facundoolano/google-play-scraper#76]
Html has changed, now you have one more class.

File : **google-play-scraper\lib\reviews.js**
**before**:
var reviewContent = $(this).find('div[class=review-body]');
**now**
reviewContent = $(this).find('div[class^="review-body **with-review-wrapper**"]');

**Comment by facundoolano** [comment]
Would you send a PR for this?

**Comment by pattonjh** [comment]
Thanks @johnipiresrodrigues for the fix!

**Comment by johnipiresrodrigues** [comment]
sorry, I'm starting now working with github, I do not know yet make a pr.

**Comment by mahemoff** [comment]
Came here after seeing empty reviews, the fix worked, thanks @johnipiresrodrigues. PR created.

**Comment by facundoolano** [comment]
Hi, I didn't receive your Pull Request. Anyway I just tried the current dev branch and it seems to work ok without changes. Can you show me exactly what request are you making (what appId, in what country/language) and make sure you test it with the latest dev code? I've merged [another PR](https://github.com/facundoolano/google-play-scraper/pull/75) related to this a couple of days ago, so my guess is that fixed it.

**Comment by mahemoff** [comment]
Sorry, I didn't end up making the PR. It looks like your change fixes it fine.

**Comment by facundoolano** [comment]
Cool, closing then.
