### ISSUE TITLE
Reviews text & title

### ISSUE THREAD

**Issue by zhuchinskyi** [facundoolano/google-play-scraper#77]
I took your basic sample and cant receive reviews fields: title and text. 
They are empty every time for any package including 'com.mojang.minecraftpe'.

console.log('userId: ' + apps[i].userId );
console.log('userName: ' + apps[i].userName );
console.log('date: ' + apps[i].date );
console.log('score: ' + apps[i].score );
console.log('title: ' + apps[i].title );
console.log('text: ' + apps[i].text');

**Comment by facundoolano** [comment]
Hi, this is a bug that was fixed recently, I just published a new version (0.3.1) including that fix, can you try again with that version and let me know if it works?

**Comment by zhuchinskyi** [comment]
Amazing, works like a charm, thanks for quick fix!
