### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by johnipiresrodrigues** [facundoolano/google-play-scraper#85]
Error: Cannot find module 'lodash'

![image](https://cloud.githubusercontent.com/assets/17652458/15366779/4f6002b6-1cfc-11e6-8d4b-faa59b99b8e1.png)

**Comment by facundoolano** [comment]
thanks for reporting, I'll fix it later today

**Comment by facundoolano** [comment]
@johnipiresrodrigues just published a patched version, let me know if works for you.
