### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by tarifhaque** [facundoolano/google-play-scraper#87]
After requiring the google-play-store module, node spits out this syntax error:

```
const request = require('request-promise');
^^^^^
SyntaxError: Use of const in strict mode.
```

This may also be reproduced when the scraper is [tested in the browser](https://tonicdev.com/npm/google-play-scraper).

**Comment by facundoolano** [comment]
I'm not sure how tonic works, but v1and above are using es6 features available in the latest node versions. Maybe you need to use Babel or something to support them (I'm not big on browser js so I don't know the specifics). Or you can stick to pre 1 versions of this module.

**Comment by tarifhaque** [comment]
Thanks. Updgrading my local installation of node did the trick.

**Comment by facundoolano** [comment]
Great!
