### ISSUE TITLE
Facing Google Captcha while fetching apps

### ISSUE THREAD

**Issue by VasanthPorcheziyan** [facundoolano/google-play-scraper#89]
Hello,
Thanks for providing this feature in nodejs. I find that using your service for about an hour and sustained fetching resulted app causing  Google Captcha problem. Please Do let as know how to overcome this issue.

Thanks in advance,
P.Vasanthkumar
![googlecaptcha](https://cloud.githubusercontent.com/assets/19526707/15462643/bee6d356-20e1-11e6-80c4-eb2003fc9720.jpeg)

**Comment by facundoolano** [comment]
I'm afraid there's not much to do once you hit their throttling limit, other than reduce the frequency in which you make requests to their site. One way to go would be introducing a little delay between one request and the next, although I don't have real proof that that would work.

Do you have a rough idea of how much requests per second are you making to hit that limit?

**Comment by VasanthPorcheziyan** [comment]
Thanks for the reply. If i use search module with 250 records, then after continues trying to hitting URL 8th or 9th time, getting Google Captcha. Also i had tried List, App modules. Also tried to delay my each request. But fetching 250 records at a time cause this problem. if their any possibility for me to overcome this issue. Do let me know.

**Comment by facundoolano** [comment]
I don't have any way around is other than delays between requests. I'll reopen in case I find out anything.

**Comment by facundoolano** [comment]
FYI added a throttling option to avoid these issues: https://github.com/facundoolano/google-play-scraper#throttling
