### ISSUE TITLE
Feature request: Add URL to collected data for reviews

### ISSUE THREAD

**Issue by pattonjh** [facundoolano/google-play-scraper#92]
Google Play provides a direct URL for each review. You can see an example here: https://play.google.com/store/apps/details?id=com.rlg.guesstheemoji&reviewId=Z3A6QU9xcFRPSE9IcWt4LXVXYTIzcnViS05PaDAxeFF3STJFMk50MDJaMW1Mc2lHdFpPd21TYV8wOFFjN29NM191UlZlNGpqTzNzS0VTWXFCOHdzWTVBZlJB

Scroll down a bit to see the review from a user named Summer Williams.

This can be found in the code for the page at:

```
<div class="review-info">
<a class="reviews-permalink" href="/store/apps/details?id=com.rlg.guesstheemoji&amp;reviewId=Z3A6QU9xcFRPSE9IcWt4LXVXYTIzcnViS05PaDAxeFF3STJFMk50MDJaMW1Mc2lHdFpPd21TYV8wOFFjN29NM191UlZlNGpqTzNzS0VTWXFCOHdzWTVBZlJB" title=" Link to this review "></a>
```

You would need to prepend "https://play.google.com" to the href data for a valid link. Also convert "`&amp;`" to just a &.

Thanks!

**Comment by facundoolano** [comment]
Thanks, I'll take a look when I get some time (pull requests are welcome in case you want to give it a shot ;) )

**Comment by facundoolano** [comment]
@pattonjh added the review url to the latest version (1.1.0). Thanks for providing all the details to implement it.
